/**
 * WIB hospitals — single source of truth.
 * Loaded by /hospitals/, /hospital-detail.html, and per-city /hospitals/[city]/ pages.
 *
 * Fields:
 *   n  name                  c  city                t  type (Government|Private|Trust)
 *   r  rating (0-5)          b  beds                e  established (year)
 *   s  specialities []       i  insurance []        a  accreditation
 *   er emergency 24/7 (0|1)  w  official website
 *   addr  street address (optional, for map embed)
 *   phone main phone number (optional)
 *
 * Uniqueness key: name + city. Two hospitals can share a name across cities
 * (e.g. HCG Cancer Centre exists in Bangalore AND Ahmedabad).
 */
window.WIB_HOSPITALS = [

// DELHI NCR (20)
{n:"AIIMS Delhi",c:"Delhi",t:"Government",r:4.8,b:2478,e:1956,s:["Cardiology","Neurology","Oncology","Orthopedics","Transplant"],i:["CGHS","ECHS","Ayushman Bharat"],a:"NABH, NABL",er:1,w:"https://www.aiims.edu",addr:"Sri Aurobindo Marg, Ansari Nagar, New Delhi 110029",phone:"+91-11-26588500"},
{n:"Sir Ganga Ram Hospital",c:"Delhi",t:"Private",r:4.6,b:675,e:1921,s:["Gastroenterology","Nephrology","Cardiology","Oncology"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.sgrh.com",addr:"Rajinder Nagar, New Delhi 110060",phone:"+91-11-25750000"},
{n:"Max Super Speciality Saket",c:"Delhi",t:"Private",r:4.5,b:500,e:2006,s:["Cardiac Sciences","Neurosciences","Oncology","Orthopedics"],i:["Most TPA","CGHS","Star Health"],a:"NABH, JCI",er:1,w:"https://www.maxhealthcare.in",addr:"1, Press Enclave Marg, Saket, New Delhi 110017",phone:"+91-11-26515050"},
{n:"Fortis Escorts Heart Institute",c:"Delhi",t:"Private",r:4.6,b:310,e:1988,s:["Cardiac Surgery","Cardiology","Vascular Surgery"],i:["Most TPA","CGHS"],a:"NABH, JCI",er:1,w:"https://www.fortisescorts.in",addr:"Okhla Road, New Delhi 110025",phone:"+91-11-47135000"},
{n:"BLK-Max Super Speciality",c:"Delhi",t:"Private",r:4.4,b:700,e:1959,s:["Bone Marrow Transplant","Oncology","Liver Transplant","Cardiology"],i:["Most TPA","CGHS"],a:"NABH, NABL",er:1,w:"https://www.blkmaxhospital.com",addr:"Pusa Road, Rajinder Nagar, New Delhi 110005",phone:"+91-11-30403040"},
{n:"Safdarjung Hospital",c:"Delhi",t:"Government",r:4.2,b:1600,e:1942,s:["General Medicine","Surgery","Orthopedics","Burns"],i:["CGHS","ECHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://www.vmmc-sjh.nic.in",addr:"Ansari Nagar West, New Delhi 110029",phone:"+91-11-26165060"},
{n:"Indraprastha Apollo",c:"Delhi",t:"Private",r:4.5,b:710,e:1996,s:["Cardiology","Oncology","Transplant","Robotic Surgery"],i:["Most TPA","CGHS","Star Health"],a:"NABH, JCI",er:1,w:"https://www.apollohospitals.com",addr:"Mathura Road, Sarita Vihar, New Delhi 110076",phone:"+91-11-71791090"},
{n:"RML Hospital",c:"Delhi",t:"Government",r:4.1,b:1531,e:1932,s:["General Medicine","Surgery","Paediatrics","Psychiatry"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://rmlh.nic.in",addr:"Baba Kharak Singh Marg, New Delhi 110001",phone:"+91-11-23365525"},
{n:"Lok Nayak Hospital",c:"Delhi",t:"Government",r:4.0,b:2000,e:1932,s:["General Medicine","Surgery","Burns","Trauma"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://lnjp.delhi.gov.in",addr:"Jawaharlal Nehru Marg, New Delhi 110002",phone:"+91-11-23230531"},
{n:"Moolchand Hospital",c:"Delhi",t:"Private",r:4.3,b:250,e:1962,s:["Gynaecology","IVF","Orthopedics","Cardiology"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.moolchandhealthcare.com",addr:"Lajpat Nagar III, New Delhi 110024",phone:"+91-11-42000000"},
{n:"Rajiv Gandhi Cancer Institute",c:"Delhi",t:"Trust",r:4.6,b:302,e:1996,s:["Oncology","Surgical Oncology","Radiation Oncology"],i:["CGHS","Most TPA"],a:"NABH, NABL",er:1,w:"https://www.rgcirc.org",addr:"Sector 5, Rohini, New Delhi 110085",phone:"+91-11-47022222"},
{n:"Dharamshila Narayana",c:"Delhi",t:"Private",r:4.4,b:300,e:1994,s:["Oncology","Bone Marrow Transplant","Radiation Oncology"],i:["Most TPA","CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://www.narayanahealth.org",addr:"Vasundhara Enclave, New Delhi 110096",phone:"+91-11-47024444"},
{n:"Primus Super Speciality",c:"Delhi",t:"Private",r:4.3,b:150,e:2006,s:["Bariatric Surgery","Orthopedics","Spine","Urology"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.primushospital.com",addr:"2 Chandragupta Marg, Chanakyapuri, New Delhi 110021",phone:"+91-11-66206620"},
{n:"Venkateshwar Hospital",c:"Delhi",t:"Private",r:4.3,b:350,e:2012,s:["Cardiac Sciences","Neurology","Joint Replacement","IVF"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.venkateshwarhospitals.com",addr:"Sector 18A, Dwarka, New Delhi 110075",phone:"+91-11-43030303"},
{n:"LHMC & Sucheta Kriplani",c:"Delhi",t:"Government",r:4.2,b:800,e:1916,s:["Gynaecology","Paediatrics","General Medicine"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://lhmc-hosp.gov.in",addr:"Bangla Sahib Marg, Connaught Place, New Delhi 110001",phone:"+91-11-23345525"},
{n:"GTB Hospital",c:"Delhi",t:"Government",r:4.0,b:1800,e:1955,s:["General Medicine","Surgery","Trauma","Burns"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://health.delhigovt.nic.in",addr:"Dilshad Garden, New Delhi 110095",phone:"+91-11-22586262"},
{n:"Medanta Gurugram",c:"Gurugram",t:"Private",r:4.5,b:1500,e:2009,s:["Cardiac Surgery","Liver Transplant","Neuroscience","Oncology","Robotic Surgery"],i:["Most TPA","Star Health","CGHS"],a:"NABH, JCI",er:1,w:"https://www.medanta.org",addr:"CH Baktawar Singh Road, Sector 38, Gurugram 122001",phone:"+91-124-4141414"},
{n:"Fortis Memorial Gurugram",c:"Gurugram",t:"Private",r:4.4,b:1000,e:2013,s:["Oncology","Neurosciences","Orthopedics","Renal Sciences"],i:["Most TPA","CGHS"],a:"NABH, JCI",er:1,w:"https://www.fortishealthcare.com",addr:"Sector 44, Gurugram 122002",phone:"+91-124-4962200"},
{n:"Artemis Hospital Gurugram",c:"Gurugram",t:"Private",r:4.3,b:400,e:2007,s:["Cardiac Sciences","Neurology","Oncology","Gastroenterology","Kidney Transplant"],i:["Most TPA","CGHS"],a:"NABH, JCI",er:1,w:"https://www.artemishospitals.com",addr:"Sector 51, Gurugram 122001",phone:"+91-124-4511111"},
{n:"Amrita Hospital Faridabad",c:"Faridabad",t:"Trust",r:4.3,b:2600,e:2022,s:["Cardiology","Oncology","Neurology","Transplant","Robotic Surgery"],i:["Most TPA","CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://www.amritahospital.org",addr:"Sector 88, Faridabad 121002",phone:"+91-129-2851000"},

// MUMBAI (20)
{n:"Tata Memorial Hospital",c:"Mumbai",t:"Government",r:4.7,b:629,e:1941,s:["Oncology","Surgical Oncology","Radiation Oncology"],i:["CGHS","ECHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://tmc.gov.in",addr:"Dr E Borges Road, Parel, Mumbai 400012",phone:"+91-22-24177000"},
{n:"Kokilaben Dhirubhai Ambani",c:"Mumbai",t:"Private",r:4.5,b:750,e:2009,s:["Cardiac Sciences","Neuroscience","Oncology","Bone Marrow Transplant","Robotic Surgery"],i:["Most TPA","Star Health"],a:"NABH, JCI",er:1,w:"https://www.kokilabenhospital.com",addr:"Rao Saheb Achutrao Patwardhan Marg, Andheri West, Mumbai 400053",phone:"+91-22-42696969"},
{n:"Lilavati Hospital",c:"Mumbai",t:"Trust",r:4.5,b:314,e:1978,s:["Cardiology","Oncology","Neurology","Gastroenterology","Orthopedics"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.lilavatihospital.com",addr:"A-791, Bandra Reclamation, Bandra West, Mumbai 400050",phone:"+91-22-26751000"},
{n:"Jaslok Hospital",c:"Mumbai",t:"Trust",r:4.4,b:364,e:1973,s:["Cardiology","Oncology","Nephrology","Neurology","Transplant"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.jaslokhospital.net",addr:"15, Dr Gopalrao Deshmukh Marg, Pedder Road, Mumbai 400026",phone:"+91-22-66573000"},
{n:"Hinduja Hospital Mahim",c:"Mumbai",t:"Trust",r:4.5,b:351,e:1951,s:["Cardiology","Gastroenterology","Nephrology","Neurology","Oncology"],i:["Most TPA","CGHS"],a:"NABH, NABL",er:1,w:"https://www.hindujahospital.com",addr:"Veer Savarkar Marg, Mahim West, Mumbai 400016",phone:"+91-22-24447000"},
{n:"KEM Hospital",c:"Mumbai",t:"Government",r:4.3,b:1800,e:1926,s:["General Medicine","Surgery","Trauma","Burns","Paediatrics"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://www.kem.edu",addr:"Acharya Donde Marg, Parel East, Mumbai 400012",phone:"+91-22-24107000"},
{n:"Nanavati Max Hospital",c:"Mumbai",t:"Private",r:4.4,b:450,e:1950,s:["Cardiac Sciences","Neurology","Oncology","Gastroenterology","Joint Replacement"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.maxhealthcare.in",addr:"SV Road, Vile Parle West, Mumbai 400056",phone:"+91-22-26267500"},
{n:"Bombay Hospital",c:"Mumbai",t:"Trust",r:4.3,b:750,e:1950,s:["Cardiology","Gastroenterology","Neurology","Oncology","Orthopedics"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.bombayhospital.com",addr:"12, New Marine Lines, Mumbai 400020",phone:"+91-22-22067676"},
{n:"HN Reliance Foundation",c:"Mumbai",t:"Trust",r:4.5,b:345,e:2014,s:["Oncology","Transplant","Cardiac Sciences","Neurology","IVF"],i:["Most TPA"],a:"NABH, JCI",er:1,w:"https://www.rfhospital.org",addr:"Raja Rammohan Roy Road, Prarthana Samaj, Girgaon, Mumbai 400004",phone:"+91-22-69869869"},
{n:"Breach Candy Hospital",c:"Mumbai",t:"Trust",r:4.4,b:190,e:1950,s:["Cardiology","Orthopedics","General Surgery","Internal Medicine"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.breachcandyhospital.org",addr:"60A, Bhulabhai Desai Road, Breach Candy, Mumbai 400026",phone:"+91-22-23667800"},
{n:"Wockhardt Hospital",c:"Mumbai",t:"Private",r:4.2,b:350,e:1998,s:["Cardiac Sciences","Neurology","Spine","Minimal Invasive Surgery"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.wockhardthospitals.com",addr:"1877, Dr Anand Rao Nair Marg, Mumbai Central, Mumbai 400011",phone:"+91-22-61784444"},
{n:"Hiranandani Hospital Powai",c:"Mumbai",t:"Private",r:4.3,b:240,e:2004,s:["Orthopedics","Cardiac Sciences","Gastroenterology","Urology","Gynaecology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.hiranandanihospital.org",addr:"Hill Side Avenue, Powai, Mumbai 400076",phone:"+91-22-25763300"},
{n:"Saifee Hospital",c:"Mumbai",t:"Trust",r:4.3,b:210,e:1954,s:["Bariatric Surgery","Orthopedics","Cardiac Sciences","General Medicine"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.saifeehospital.com",addr:"15/17 Maharshi Karve Road, Charni Road, Mumbai 400004",phone:"+91-22-67570111"},
{n:"Jupiter Hospital Thane",c:"Mumbai",t:"Private",r:4.3,b:300,e:2007,s:["Cardiac Sciences","Neurology","Oncology","Transplant","Joint Replacement"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.jupiterhospital.com",addr:"Eastern Express Highway, Thane 400601",phone:"+91-22-21725555"},
{n:"Apollo Navi Mumbai",c:"Mumbai",t:"Private",r:4.4,b:260,e:2011,s:["Cardiac Sciences","Neurology","Oncology","Orthopedics","Transplant"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.apollohospitals.com",addr:"Plot 13, Sector 23, CBD Belapur, Navi Mumbai 400614",phone:"+91-22-33503350"},
{n:"Fortis Mulund",c:"Mumbai",t:"Private",r:4.3,b:300,e:2005,s:["Cardiac Sciences","Neurology","Gastroenterology","Orthopedics","Oncology"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.fortishealthcare.com",addr:"Mulund Goregaon Link Road, Mulund West, Mumbai 400078",phone:"+91-22-67994444"},
{n:"Global Hospital Mumbai",c:"Mumbai",t:"Private",r:4.2,b:300,e:2010,s:["Liver Transplant","Kidney Transplant","Gastroenterology","Hepatology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.globalhospitals.com",addr:"35 Dr E Borges Road, Hospital Avenue, Parel, Mumbai 400012",phone:"+91-22-67670101"},
{n:"Seven Hills Hospital",c:"Mumbai",t:"Private",r:4.1,b:350,e:2004,s:["Cardiac Sciences","Neurology","Orthopedics","Gastroenterology","General Medicine"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.7hillshospital.com",addr:"Marol Maroshi Road, Andheri East, Mumbai 400059",phone:"+91-22-67676767"},
{n:"Holy Spirit Hospital",c:"Mumbai",t:"Trust",r:4.2,b:220,e:1973,s:["General Medicine","Orthopedics","Gynaecology","Paediatrics"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.holyspirithosp.com",addr:"Mahakali Road, Andheri East, Mumbai 400093",phone:"+91-22-29209999"},
{n:"SL Raheja Mahim",c:"Mumbai",t:"Private",r:4.1,b:200,e:1984,s:["Diabetology","Cardiac Sciences","Neurology","Orthopedics"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.rahejahospital.com",addr:"Raheja Rugnalaya Marg, Mahim West, Mumbai 400016",phone:"+91-22-66529888"},

// CHENNAI & TN (20)
{n:"Apollo Greams Road",c:"Chennai",t:"Private",r:4.6,b:710,e:1983,s:["Cardiology","Oncology","Transplant","Orthopedics","Neurology"],i:["Most TPA","Star Health","CGHS"],a:"NABH, JCI",er:1,w:"https://www.apollohospitals.com",addr:"21 Greams Lane, Off Greams Road, Chennai 600006",phone:"+91-44-28293333"},
{n:"CMC Vellore",c:"Vellore",t:"Trust",r:4.7,b:2700,e:1900,s:["General Medicine","Oncology","Haematology","Nephrology","Neurology"],i:["CGHS","Most TPA","Ayushman Bharat"],a:"NABH, NABL",er:1,w:"https://www.cmch-vellore.edu",addr:"Ida Scudder Road, Vellore 632004",phone:"+91-416-2281000"},
{n:"Sankara Nethralaya",c:"Chennai",t:"Trust",r:4.8,b:400,e:1978,s:["Ophthalmology","Retina","Glaucoma","Cornea"],i:["Most TPA","CGHS"],a:"NABH",er:0,w:"https://www.sankaranethralaya.org",addr:"18, College Road, Nungambakkam, Chennai 600006",phone:"+91-44-28271616"},
{n:"MIOT International",c:"Chennai",t:"Private",r:4.5,b:600,e:1999,s:["Orthopedics","Joint Replacement","Spine","Sports Medicine","Cardiac Sciences"],i:["Most TPA","Star Health"],a:"NABH, JCI",er:1,w:"https://www.miothospitals.com",addr:"4/112, Mount Poonamallee Road, Manapakkam, Chennai 600089",phone:"+91-44-42002288"},
{n:"Fortis Malar Hospital",c:"Chennai",t:"Private",r:4.3,b:180,e:1992,s:["Cardiac Sciences","Neurology","Gastroenterology","Kidney Transplant"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.fortismalar.com",addr:"52 1st Main Road, Gandhi Nagar, Adyar, Chennai 600020",phone:"+91-44-42892222"},
{n:"Madras Medical Mission",c:"Chennai",t:"Trust",r:4.5,b:350,e:1990,s:["Cardiac Surgery","Cardiology","Paediatric Cardiac"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.mmm.org.in",addr:"4-A, Dr J Jayalalithaa Nagar, Mogappair, Chennai 600037",phone:"+91-44-26561801"},
{n:"Stanley Medical College Hospital",c:"Chennai",t:"Government",r:4.2,b:1650,e:1938,s:["General Medicine","Surgery","Orthopedics","Trauma"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://www.smc.tn.gov.in",addr:"Old Jail Road, Royapuram, Chennai 600001",phone:"+91-44-25281347"},
{n:"Rajiv Gandhi GGH",c:"Chennai",t:"Government",r:4.1,b:2400,e:1664,s:["General Medicine","Surgery","Trauma","Burns","Paediatrics"],i:["Ayushman Bharat"],a:"NABH",er:1,w:"https://rfrgggh.tn.nic.in",addr:"Park Town, EVR Periyar Salai, Chennai 600003",phone:"+91-44-25305000"},
{n:"Sri Ramachandra Hospital",c:"Chennai",t:"Private",r:4.4,b:800,e:1985,s:["Cardiac Sciences","Neurology","Gastroenterology","Oncology","Transplant"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.sriramachandra.edu.in",addr:"1, Ramachandra Nagar, Porur, Chennai 600116",phone:"+91-44-24768027"},
{n:"Kauvery Hospital",c:"Chennai",t:"Private",r:4.4,b:350,e:1999,s:["Cardiac Sciences","Neurology","Gastroenterology","Orthopedics","Oncology"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.kauveryhospital.com",addr:"199, Luz Church Road, Mylapore, Chennai 600004",phone:"+91-44-40006000"},
{n:"MGM Healthcare",c:"Chennai",t:"Private",r:4.3,b:400,e:2019,s:["Cardiac Sciences","Neurology","Transplant","Oncology","Robotic Surgery"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://mgmhealthcare.in",addr:"72, Nelson Manickam Road, Aminjikarai, Chennai 600029",phone:"+91-44-45242424"},
{n:"Gleneagles Global Chennai",c:"Chennai",t:"Private",r:4.4,b:1000,e:1999,s:["Transplant","Cardiac Sciences","Neurology","Oncology","Robotic Surgery"],i:["Most TPA","Star Health"],a:"NABH, JCI",er:1,w:"https://www.gleneagleshealth.in",addr:"439, Cheran Nagar, Perumbakkam, Chennai 600100",phone:"+91-44-44777000"},
{n:"Global Hospital Chennai",c:"Chennai",t:"Private",r:4.3,b:350,e:2009,s:["Liver Transplant","Gastroenterology","Hepatology","Kidney Transplant"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.globalhospitalsindia.com",addr:"439, Cheran Nagar, Perumbakkam, Chennai 600100",phone:"+91-44-44777000"},
{n:"Apollo Children's Hospital",c:"Chennai",t:"Private",r:4.6,b:180,e:1997,s:["Paediatrics","Paediatric Surgery","Neonatology","PICU"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.apollochildrenshospitals.com",addr:"15, Shafee Mohammed Road, Thousand Lights, Chennai 600006",phone:"+91-44-28290200"},
{n:"Billroth Hospitals",c:"Chennai",t:"Private",r:4.2,b:300,e:1990,s:["Cardiac Sciences","Neurology","Orthopedics","Gastroenterology","IVF"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.billrothhospitals.com",addr:"43, Lakshmi Talkies Road, Shenoy Nagar, Chennai 600030",phone:"+91-44-26411000"},
{n:"Vijaya Hospital",c:"Chennai",t:"Private",r:4.2,b:300,e:1972,s:["Cardiac Sciences","Neurology","Orthopedics","Gastroenterology","General Medicine"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.vijayahospital.com",addr:"180, NSK Salai, Vadapalani, Chennai 600026",phone:"+91-44-23601111"},
{n:"Dr. Mehta's Hospitals",c:"Chennai",t:"Private",r:4.2,b:250,e:1933,s:["Orthopedics","Joint Replacement","Spine","Sports Medicine"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.mehtahospital.com",addr:"2, McNichols Road, Chetpet, Chennai 600031",phone:"+91-44-66264563"},
{n:"Prashanth Hospitals",c:"Chennai",t:"Private",r:4.2,b:250,e:1989,s:["Gastroenterology","Hepatology","Liver Transplant","Renal Sciences"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.prashanthhospitals.com",addr:"Lloyds Road, Chennai 600014",phone:"+91-44-43545454"},
{n:"Chettinad Hospital",c:"Chennai",t:"Private",r:4.1,b:400,e:2006,s:["General Medicine","Surgery","Orthopedics","Cardiac Sciences","Neurology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.chettinadhealthcity.com",addr:"Rajiv Gandhi Salai, Kelambakkam, Chennai 603103",phone:"+91-44-47429000"},
{n:"Aravind Eye Hospital",c:"Madurai",t:"Trust",r:4.7,b:500,e:1976,s:["Ophthalmology","Cataract","Retina","Glaucoma","Cornea"],i:["Most TPA","CGHS"],a:"NABH",er:0,w:"https://www.aravind.org",addr:"1, Anna Nagar, Madurai 625020",phone:"+91-452-4356100"},

// BANGALORE (20)
{n:"Narayana Health City",c:"Bangalore",t:"Private",r:4.5,b:3200,e:2001,s:["Cardiology","Cardiac Surgery","Oncology","Nephrology","Transplant"],i:["Most TPA","Star Health","Ayushman Bharat"],a:"NABH, JCI",er:1,w:"https://www.narayanahealth.org",addr:"258/A, Bommasandra Industrial Area, Hosur Road, Bangalore 560099",phone:"+91-80-71222222"},
{n:"NIMHANS",c:"Bangalore",t:"Government",r:4.6,b:897,e:1925,s:["Psychiatry","Neurology","Neurosurgery","Clinical Psychology"],i:["CGHS","ECHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://nimhans.ac.in",addr:"Hosur Road, Lakkasandra, Wilson Garden, Bangalore 560029",phone:"+91-80-26995001"},
{n:"Manipal Hospital Old Airport Rd",c:"Bangalore",t:"Private",r:4.4,b:650,e:1991,s:["Transplant","Oncology","Cardiology","Neurology","Gastroenterology"],i:["Most TPA","Star Health","CGHS"],a:"NABH",er:1,w:"https://www.manipalhospitals.com",addr:"98, HAL Old Airport Road, Kodihalli, Bangalore 560017",phone:"+91-80-25024444"},
{n:"Aster CMI Hospital",c:"Bangalore",t:"Private",r:4.4,b:500,e:2014,s:["Cardiac Sciences","Neurology","Oncology","Gastroenterology","Transplant"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.asterbangalore.com",addr:"43/2, NH-7, Hebbal Sahakar Nagar, Bangalore 560092",phone:"+91-80-43420100"},
{n:"Fortis Bannerghatta",c:"Bangalore",t:"Private",r:4.3,b:400,e:2007,s:["Cardiac Sciences","Neurology","Oncology","Orthopedics","Transplant"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.fortishealthcare.com",addr:"154/9, Bannerghatta Road, Opp IIM, Bangalore 560076",phone:"+91-80-66214444"},
{n:"Apollo Bannerghatta",c:"Bangalore",t:"Private",r:4.4,b:300,e:2007,s:["Cardiac Sciences","Neurology","Oncology","Transplant","Robotic Surgery"],i:["Most TPA","Star Health"],a:"NABH, JCI",er:1,w:"https://www.apollohospitals.com",addr:"154/11, Bannerghatta Road, Opp IIM, Bangalore 560076",phone:"+91-80-26304050"},
{n:"Sakra World Hospital",c:"Bangalore",t:"Private",r:4.3,b:300,e:2014,s:["Orthopedics","Cardiac Sciences","Neurology","Oncology","Gastroenterology"],i:["Most TPA","Star Health"],a:"NABH, JCI",er:1,w:"https://www.sakraworldhospital.com",addr:"SY No 52/2 & 52/3, Devarabeesanahalli, Marathahalli, Bangalore 560103",phone:"+91-80-49694969"},
{n:"Jayadeva Institute",c:"Bangalore",t:"Government",r:4.5,b:700,e:1992,s:["Cardiology","Cardiac Surgery","Paediatric Cardiac"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://www.jayadevacardiology.com",addr:"Bannerghatta Road, Jayanagar 9th Block, Bangalore 560069",phone:"+91-80-22977000"},
{n:"Kidwai Memorial Hospital",c:"Bangalore",t:"Government",r:4.2,b:650,e:1973,s:["Oncology","Surgical Oncology","Radiation Oncology"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://kidwai.karnataka.gov.in",addr:"Dr MH Marigowda Road, Bangalore 560029",phone:"+91-80-26094000"},
{n:"St. Johns Medical College",c:"Bangalore",t:"Trust",r:4.4,b:1250,e:1963,s:["General Medicine","Surgery","Paediatrics","Cardiac Sciences","Oncology"],i:["CGHS","Most TPA"],a:"NABH",er:1,w:"https://www.stjohns.in",addr:"Sarjapur Road, John Nagar, Koramangala, Bangalore 560034",phone:"+91-80-22065000"},
{n:"HCG Cancer Centre",c:"Bangalore",t:"Private",r:4.5,b:200,e:1989,s:["Oncology","Radiation Oncology","Bone Marrow Transplant","Surgical Oncology"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.hcgoncology.com",addr:"HCG Tower, 8, P Kalinga Rao Road, Sampangi Rama Nagar, Bangalore 560027",phone:"+91-80-40206000"},
{n:"BGS Gleneagles",c:"Bangalore",t:"Private",r:4.3,b:500,e:2011,s:["Cardiac Sciences","Neurology","Orthopedics","Oncology","Gastroenterology"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.bgsgleneagles.com",addr:"67, Uttarahalli Road, Kengeri, Bangalore 560060",phone:"+91-80-26255555"},
{n:"MS Ramaiah Memorial",c:"Bangalore",t:"Private",r:4.3,b:800,e:1979,s:["General Medicine","Surgery","Cardiac Sciences","Neurology","Oncology"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.msrmh.com",addr:"MSR Nagar, Mathikere, Bangalore 560054",phone:"+91-80-22183000"},
{n:"Mazumdar Shaw Medical Centre",c:"Bangalore",t:"Trust",r:4.5,b:1400,e:2001,s:["Oncology","Bone Marrow Transplant","Cardiac Sciences","Neurology","Transplant"],i:["Most TPA","Ayushman Bharat"],a:"NABH, JCI",er:1,w:"https://www.narayanahealth.org",addr:"258/A, Bommasandra Industrial Area, Bangalore 560099",phone:"+91-80-71222222"},
{n:"Sparsh Hospital",c:"Bangalore",t:"Private",r:4.3,b:200,e:2004,s:["Orthopedics","Joint Replacement","Spine","Sports Medicine","Trauma"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.sparshhospital.com",addr:"146, Infantry Road, Bangalore 560001",phone:"+91-80-49006000"},
{n:"Columbia Asia Whitefield",c:"Bangalore",t:"Private",r:4.2,b:150,e:2008,s:["General Medicine","Orthopedics","Gastroenterology","Gynaecology","Paediatrics"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.columbiaasia.com",addr:"Survey No 10P & 12P, Ramagondanahalli, Whitefield, Bangalore 560066",phone:"+91-80-61656666"},
{n:"Vikram Hospital",c:"Bangalore",t:"Private",r:4.2,b:200,e:2001,s:["Cardiac Sciences","Neurology","Orthopedics","Gastroenterology","Renal Sciences"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.vikramhospital.com",addr:"71/1, Millers Road, Vasanth Nagar, Bangalore 560052",phone:"+91-80-71222222"},
{n:"Sagar Hospitals",c:"Bangalore",t:"Private",r:4.2,b:250,e:2004,s:["Cardiac Sciences","Neurology","Orthopedics","Gastroenterology","Oncology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.sagarhospitals.in",addr:"Shavige Malleshwara Hills, Kumaraswamy Layout, Bangalore 560078",phone:"+91-80-46255555"},
{n:"Bangalore Baptist Hospital",c:"Bangalore",t:"Trust",r:4.3,b:400,e:1973,s:["General Medicine","Surgery","Orthopedics","Gynaecology","Paediatrics"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.bbh.org.in",addr:"Bellary Road, Hebbal, Bangalore 560024",phone:"+91-80-22024700"},
{n:"Ramaiah Narayana Heart Centre",c:"Bangalore",t:"Private",r:4.4,b:250,e:2012,s:["Cardiac Surgery","Cardiology","Vascular Surgery"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.narayanahealth.org",addr:"MSR Nagar, MSRIT Post, Bangalore 560054",phone:"+91-80-66660000"},

// KOLKATA (20)
{n:"AMRI Hospital Salt Lake",c:"Kolkata",t:"Private",r:4.4,b:450,e:1996,s:["Cardiac Sciences","Neurology","Oncology","Orthopedics","Gastroenterology"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.amrihospitals.in",addr:"JC-16 & 17, Salt Lake City, Sector III, Kolkata 700098",phone:"+91-33-66800000"},
{n:"Fortis Anandapur",c:"Kolkata",t:"Private",r:4.3,b:400,e:2008,s:["Cardiac Sciences","Neurology","Oncology","Renal Sciences","Transplant"],i:["Most TPA","Star Health"],a:"NABH, JCI",er:1,w:"https://www.fortishealthcare.com",addr:"730 EM Bypass, Anandapur, Kolkata 700107",phone:"+91-33-66284444"},
{n:"Apollo Gleneagles Kolkata",c:"Kolkata",t:"Private",r:4.4,b:510,e:2003,s:["Cardiac Sciences","Neurology","Oncology","Transplant","Gastroenterology"],i:["Most TPA","Star Health"],a:"NABH, JCI",er:1,w:"https://kolkata.apollohospitals.com",addr:"58, Canal Circular Road, Kadapara, Kolkata 700054",phone:"+91-33-23203040"},
{n:"Medica Superspecialty",c:"Kolkata",t:"Private",r:4.3,b:400,e:2010,s:["Cardiac Sciences","Neurology","Transplant","Oncology","Orthopedics"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.medicasynergie.in",addr:"127 Mukundapur, EM Bypass, Kolkata 700099",phone:"+91-33-66520000"},
{n:"Tata Medical Center",c:"Kolkata",t:"Trust",r:4.6,b:460,e:2011,s:["Oncology","Bone Marrow Transplant","Surgical Oncology","Paediatric Oncology"],i:["Most TPA","CGHS"],a:"NABH, JCI",er:1,w:"https://www.tatamedicalbr.com",addr:"14 MAR (E-W), New Town, Rajarhat, Kolkata 700160",phone:"+91-33-66057000"},
{n:"BM Birla Heart Research",c:"Kolkata",t:"Private",r:4.5,b:200,e:1989,s:["Cardiology","Cardiac Surgery","Vascular Surgery","Paediatric Cardiac"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.bmbirlaheart.com",addr:"1/1 National Library Avenue, Alipore, Kolkata 700027",phone:"+91-33-30403040"},
{n:"Peerless Hospital",c:"Kolkata",t:"Private",r:4.2,b:350,e:1988,s:["Cardiac Sciences","Neurology","Gastroenterology","Orthopedics","Renal Sciences"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.peerlesshospital.com",addr:"360 Panchasayar, Kolkata 700094",phone:"+91-33-40111222"},
{n:"Woodlands Hospital",c:"Kolkata",t:"Private",r:4.2,b:350,e:1988,s:["Cardiac Sciences","Neurology","Gastroenterology","General Medicine","Gynaecology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.woodlandshospital.in",addr:"8/5 Alipore Road, Kolkata 700027",phone:"+91-33-40337000"},
{n:"SSKM Hospital",c:"Kolkata",t:"Government",r:4.2,b:2000,e:1945,s:["General Medicine","Surgery","Trauma","Burns","Paediatrics"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://www.sskm.org",addr:"244 AJC Bose Road, Bhowanipore, Kolkata 700020",phone:"+91-33-22041101"},
{n:"RN Tagore International",c:"Kolkata",t:"Private",r:4.3,b:300,e:2002,s:["Cardiac Sciences","Neurology","Orthopedics","Gastroenterology","Oncology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.rfrntihkolkata.com",addr:"Premises 1489, Mukundapur, EM Bypass, Kolkata 700099",phone:"+91-33-66060606"},
{n:"Belle Vue Clinic",c:"Kolkata",t:"Private",r:4.3,b:180,e:1979,s:["General Medicine","Cardiac Sciences","Neurology","Gastroenterology","Gynaecology"],i:["Most TPA"],a:"NABH",er:1,w:"https://bellevueclinic.com",addr:"9 Dr UN Brahmachari Street, Kolkata 700017",phone:"+91-33-22872321"},
{n:"Ruby General Hospital",c:"Kolkata",t:"Private",r:4.2,b:350,e:2002,s:["Cardiac Sciences","Neurology","Orthopedics","Oncology","Gastroenterology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.rubyhospital.com",addr:"576 Anandapur, EM Bypass, Kolkata 700107",phone:"+91-33-39849000"},
{n:"Narayana Multispeciality Howrah",c:"Kolkata",t:"Private",r:4.3,b:300,e:2013,s:["Cardiac Sciences","Neurology","Orthopedics","Gastroenterology","Paediatrics"],i:["Most TPA","Ayushman Bharat"],a:"NABH",er:1,w:"https://www.narayanahealth.org",addr:"120/1 Andul Road, Howrah 711103",phone:"+91-33-71222222"},
{n:"CMRI Kolkata",c:"Kolkata",t:"Private",r:4.2,b:300,e:1969,s:["Cardiac Sciences","Neurology","Gastroenterology","Orthopedics","Urology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.cmaborneandcmri.com",addr:"7/2 Diamond Harbour Road, Alipore, Kolkata 700027",phone:"+91-33-30903090"},
{n:"Chittaranjan Cancer Institute",c:"Kolkata",t:"Government",r:4.3,b:350,e:1950,s:["Oncology","Surgical Oncology","Radiation Oncology","Gynae Oncology"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://www.cnci.ac.in",addr:"37 SP Mukherjee Road, Kolkata 700026",phone:"+91-33-24765101"},
{n:"NRS Medical College",c:"Kolkata",t:"Government",r:4.0,b:1600,e:1873,s:["General Medicine","Surgery","Trauma","Paediatrics"],i:["Ayushman Bharat"],a:"NABH",er:1,w:"https://nrsmc.edu.in",addr:"138 AJC Bose Road, Sealdah, Kolkata 700014",phone:"+91-33-22841182"},
{n:"ILS Hospital Dumdum",c:"Kolkata",t:"Private",r:4.1,b:250,e:2005,s:["Cardiac Sciences","Neurology","Gastroenterology","Orthopedics","General Medicine"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.ilshospitals.com",addr:"DD-6, Sector 1, Salt Lake City, Kolkata 700064",phone:"+91-33-40209000"},
{n:"Desun Hospital",c:"Kolkata",t:"Private",r:4.2,b:200,e:2004,s:["Cardiac Sciences","Neurology","Orthopedics","Gastroenterology","Critical Care"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.desunhospital.com",addr:"Desun More, Kasba Golpark, EM Bypass, Kolkata 700107",phone:"+91-33-71414141"},
{n:"Manipal Hospital Kolkata",c:"Kolkata",t:"Private",r:4.3,b:350,e:2016,s:["Cardiac Sciences","Neurology","Oncology","Transplant","Gastroenterology"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.manipalhospitals.com",addr:"Plot No 130, Action Area III, Newtown, Kolkata 700156",phone:"+91-33-66888888"},
{n:"EKO Superspeciality",c:"Kolkata",t:"Private",r:4.1,b:200,e:2006,s:["Cardiac Sciences","Neurology","Gastroenterology","Orthopedics","Urology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.ekosuperspeciality.com",addr:"Diamond Harbour Road, Kolkata 700053",phone:"+91-33-30404040"},

// HYDERABAD (14)
{n:"AIG Hospitals",c:"Hyderabad",t:"Private",r:4.7,b:450,e:2006,s:["Gastroenterology","Liver Transplant","Hepatology","Surgical Gastro"],i:["Most TPA","Star Health","CGHS"],a:"NABH",er:1,w:"https://www.aighospitals.com",addr:"Mindspace Road, Gachibowli, Hyderabad 500032",phone:"+91-40-49099999"},
{n:"KIMS Hospitals",c:"Hyderabad",t:"Private",r:4.5,b:1000,e:2000,s:["Cardiac Sciences","Neurology","Orthopedics","Oncology","Transplant"],i:["Most TPA","Star Health","CGHS"],a:"NABH, JCI",er:1,w:"https://www.kimshospitals.com",addr:"1-8-31/1, Minister Road, Krishna Nagar Colony, Begumpet, Secunderabad 500003",phone:"+91-40-44885000"},
{n:"Apollo Jubilee Hills",c:"Hyderabad",t:"Private",r:4.5,b:500,e:1988,s:["Cardiology","Oncology","Neurosciences","Transplant"],i:["Most TPA","Star Health","CGHS"],a:"NABH, JCI",er:1,w:"https://www.apollohospitals.com",addr:"Road No 72, Opp Bharatiya Vidya Bhavan School, Film Nagar, Jubilee Hills, Hyderabad 500033",phone:"+91-40-23607777"},
{n:"Yashoda Hospitals",c:"Hyderabad",t:"Private",r:4.4,b:500,e:1989,s:["Neuroscience","Cardiac Sciences","Gastroenterology","Orthopedics"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.yashodahospitals.com",addr:"Behind Hari Hara Kala Bhavan, SP Road, Secunderabad 500003",phone:"+91-40-27713333"},
{n:"Continental Hospitals",c:"Hyderabad",t:"Private",r:4.4,b:750,e:2013,s:["Orthopedics","Transplant","Cardiac Sciences","Robotic Surgery"],i:["Most TPA","Star Health"],a:"NABH, JCI",er:1,w:"https://www.continentalhospitals.com",addr:"IT and Financial District, Nanakramguda, Gachibowli, Hyderabad 500032",phone:"+91-40-67000000"},
{n:"Care Hospitals",c:"Hyderabad",t:"Private",r:4.4,b:435,e:1997,s:["Cardiac Sciences","Neuroscience","Oncology","Orthopedics"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.carehospitals.com",addr:"Road No 1, Banjara Hills, Hyderabad 500034",phone:"+91-40-30418888"},
{n:"Basavatarakam Cancer Hospital",c:"Hyderabad",t:"Trust",r:4.6,b:300,e:2001,s:["Oncology","Surgical Oncology","Radiation Oncology","Chemotherapy"],i:["Most TPA","CGHS"],a:"NABH",er:0,w:"https://www.basavatarakam.org",addr:"Road No 14, Banjara Hills, Hyderabad 500034",phone:"+91-40-23551235"},
{n:"LV Prasad Eye Institute",c:"Hyderabad",t:"Trust",r:4.8,b:200,e:1987,s:["Ophthalmology","Cornea","Retina","Glaucoma"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.lvpei.org",addr:"LV Prasad Marg, Banjara Hills, Hyderabad 500034",phone:"+91-40-30612345"},
{n:"NIMS Hyderabad",c:"Hyderabad",t:"Government",r:4.3,b:1500,e:1960,s:["Cardiac Sciences","Neurology","Nephrology","General Surgery"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"https://nims.ap.nic.in",addr:"Punjagutta, Hyderabad 500082",phone:"+91-40-23489000"},
{n:"Osmania General Hospital",c:"Hyderabad",t:"Government",r:4.1,b:1168,e:1919,s:["General Medicine","Surgery","Orthopedics","Trauma"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"",addr:"Afzal Gunj, Hyderabad 500012",phone:"+91-40-24600121"},
{n:"Star Hospitals",c:"Hyderabad",t:"Private",r:4.5,b:200,e:2014,s:["Cardiac Surgery","Interventional Cardiology","Vascular Surgery"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.starhospitals.in",addr:"Road No 10, Banjara Hills, Hyderabad 500034",phone:"+91-40-44777777"},
{n:"Global Hospitals Hyderabad",c:"Hyderabad",t:"Private",r:4.4,b:500,e:1998,s:["Liver Transplant","Gastroenterology","Renal Transplant"],i:["Most TPA","Star Health"],a:"NABH, JCI",er:1,w:"https://www.globalhospitalsindia.com",addr:"6-1-1070, Lakdi-ka-pul, Hyderabad 500004",phone:"+91-40-23244444"},
{n:"Fernandez Hospital",c:"Hyderabad",t:"Private",r:4.6,b:200,e:1967,s:["Maternity","Neonatology","Gynaecology","Fertility"],i:["Most TPA"],a:"NABH",er:0,w:"https://www.fernandezhospital.com",addr:"Bogulkunta, Hyderguda, Hyderabad 500001",phone:"+91-40-40632222"},
{n:"Sunshine Hospitals",c:"Hyderabad",t:"Private",r:4.3,b:250,e:2000,s:["Orthopedics","Joint Replacement","Sports Medicine"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.sunshinehospitals.com",addr:"PG Road, Paradise Circle, Secunderabad 500003",phone:"+91-40-44550000"},
{n:"MaxCure Hospitals",c:"Hyderabad",t:"Private",r:4.3,b:300,e:2005,s:["Cardiac Sciences","Orthopedics","Neurology","Urology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.maxcurehospitals.com",addr:"Behind Cyber Towers, Hi-Tech City Main Road, Madhapur, Hyderabad 500081",phone:"+91-40-46444444"},

// PUNE (13)
{n:"Ruby Hall Clinic",c:"Pune",t:"Private",r:4.5,b:750,e:1959,s:["Cardiac Sciences","Neurology","Oncology","Transplant","Orthopedics"],i:["Most TPA","Star Health","CGHS"],a:"NABH, JCI",er:1,w:"https://www.rubyhall.com",addr:"40, Sassoon Road, Pune 411001",phone:"+91-20-26163391"},
{n:"Sahyadri Hospital",c:"Pune",t:"Private",r:4.4,b:500,e:1984,s:["Cardiac Sciences","Neuroscience","Orthopedics","Oncology"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.sahyadrihospital.com",addr:"Plot No 9-C, Erandwane, Pune 411004",phone:"+91-20-67213000"},
{n:"Jehangir Hospital",c:"Pune",t:"Private",r:4.4,b:350,e:1946,s:["Cardiac Sciences","Orthopedics","Neurology","IVF"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.jehangirhospital.com",addr:"32, Sassoon Road, Pune 411001",phone:"+91-20-66819999"},
{n:"Deenanath Mangeshkar Hospital",c:"Pune",t:"Trust",r:4.5,b:800,e:1995,s:["Cardiac Sciences","Oncology","Neuroscience","Transplant"],i:["Most TPA","Star Health","CGHS"],a:"NABH",er:1,w:"https://www.dmhospital.org",addr:"Near Mhatre Bridge, Erandawane, Pune 411004",phone:"+91-20-49153000"},
{n:"KEM Hospital Pune",c:"Pune",t:"Trust",r:4.3,b:500,e:1912,s:["General Medicine","Surgery","Paediatrics","Obstetrics"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.kemhospitalpune.org",addr:"489 Rasta Peth, Sardar Moodliar Road, Pune 411011",phone:"+91-20-66037300"},
{n:"Sassoon General Hospital",c:"Pune",t:"Government",r:4.0,b:1300,e:1867,s:["General Medicine","Surgery","Trauma","Burns"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"",addr:"Near Pune Railway Station, Pune 411001",phone:"+91-20-26128000"},
{n:"Aditya Birla Memorial Hospital",c:"Pune",t:"Private",r:4.3,b:500,e:2003,s:["Cardiac Sciences","Oncology","Robotic Surgery","Transplant"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.adityabirlahospital.com",addr:"Aditya Birla Hospital Marg, Thergaon, Chinchwad, Pune 411033",phone:"+91-20-30717500"},
{n:"Jupiter Hospital Pune",c:"Pune",t:"Private",r:4.3,b:350,e:2002,s:["Cardiac Sciences","Orthopedics","Urology","Nephrology"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.jupiterhospital.com",addr:"Baner-Pashan Link Road, Baner, Pune 411045",phone:"+91-20-27290700"},
{n:"Sancheti Hospital",c:"Pune",t:"Private",r:4.4,b:200,e:1975,s:["Orthopedics","Joint Replacement","Sports Medicine","Spine"],i:["Most TPA","Star Health"],a:"NABH",er:0,w:"https://www.sanchetihospital.com",addr:"16, Shivaji Nagar, Pune 411005",phone:"+91-20-25533333"},
{n:"Noble Hospital Pune",c:"Pune",t:"Private",r:4.2,b:300,e:2000,s:["Cardiac Sciences","Orthopedics","General Surgery","Gastroenterology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.noblehospital.com",addr:"153, Magarpatta City Road, Hadapsar, Pune 411013",phone:"+91-20-66285600"},
{n:"Command Hospital Pune",c:"Pune",t:"Government",r:4.3,b:1000,e:1941,s:["General Medicine","Surgery","Orthopedics","Cardiac Sciences"],i:["ECHS","CGHS"],a:"NABH",er:1,w:"",addr:"Wanowrie, Pune 411040",phone:"+91-20-26050100"},
{n:"Bharati Hospital Pune",c:"Pune",t:"Trust",r:4.1,b:600,e:1989,s:["General Medicine","Surgery","Orthopedics","Dental"],i:["Most TPA","CGHS"],a:"NABH",er:1,w:"https://www.bharatihospital.com",addr:"Bharati Vidyapeeth Campus, Dhankawadi, Pune 411043",phone:"+91-20-40555555"},
{n:"Inamdar Hospital Pune",c:"Pune",t:"Private",r:4.2,b:300,e:1993,s:["Cardiac Sciences","Orthopedics","Neurology","Gastroenterology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.inamdarhospital.com",addr:"Sr No 15, Fatima Nagar, Wanowrie, Pune 411040",phone:"+91-20-26836661"},

// AHMEDABAD (12)
{n:"Zydus Hospital",c:"Ahmedabad",t:"Private",r:4.4,b:550,e:2010,s:["Cardiac Sciences","Neuroscience","Oncology","Transplant","Robotic Surgery"],i:["Most TPA","Star Health"],a:"NABH, JCI",er:1,w:"https://www.zydushospitals.com",addr:"Nr Sola Bridge, SG Highway, Thaltej, Ahmedabad 380054",phone:"+91-79-66670000"},
{n:"Sterling Hospital",c:"Ahmedabad",t:"Private",r:4.3,b:400,e:2001,s:["Cardiac Sciences","Orthopedics","Neurology","Urology"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.sterlinghospitals.com",addr:"Sterling Hospital Road, Memnagar, Ahmedabad 380052",phone:"+91-79-40011111"},
{n:"Apollo Hospitals Ahmedabad",c:"Ahmedabad",t:"Private",r:4.4,b:400,e:2005,s:["Cardiac Sciences","Transplant","Oncology","Orthopedics"],i:["Most TPA","Star Health","CGHS"],a:"NABH",er:1,w:"https://www.apollohospitals.com",addr:"Plot No 1A, Bhat GIDC Estate, Gandhinagar 382428",phone:"+91-79-66701800"},
{n:"HCG Cancer Centre",c:"Ahmedabad",t:"Private",r:4.5,b:200,e:2003,s:["Oncology","Radiation Therapy","Surgical Oncology","Bone Marrow Transplant"],i:["Most TPA","Star Health"],a:"NABH",er:0,w:"https://www.hcgoncology.com",addr:"Sola Science City Road, Off SG Highway, Sola, Ahmedabad 380060",phone:"+91-79-67770000"},
{n:"Civil Hospital Ahmedabad",c:"Ahmedabad",t:"Government",r:4.1,b:2500,e:1879,s:["General Medicine","Surgery","Paediatrics","Psychiatry"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"",addr:"Asarwa, Ahmedabad 380016",phone:"+91-79-22680074"},
{n:"CIMS Hospital",c:"Ahmedabad",t:"Private",r:4.4,b:350,e:2006,s:["Cardiac Sciences","Neurology","Gastroenterology","Transplant"],i:["Most TPA","Star Health"],a:"NABH",er:1,w:"https://www.cimshospital.org",addr:"Off Science City Road, Sola, Ahmedabad 380060",phone:"+91-79-30101000"},
{n:"Shalby Hospital",c:"Ahmedabad",t:"Private",r:4.3,b:300,e:1994,s:["Joint Replacement","Orthopedics","Spine","Sports Medicine"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.shalbyhospitals.com",addr:"Opp Karnavati Club, SG Highway, Ahmedabad 380015",phone:"+91-79-40203000"},
{n:"UN Mehta Institute of Cardiology",c:"Ahmedabad",t:"Government",r:4.5,b:450,e:1997,s:["Cardiac Surgery","Cardiology","Paediatric Cardiac","Heart Transplant"],i:["CGHS","Most TPA"],a:"NABH",er:1,w:"https://www.unmicrc.org",addr:"Civil Hospital Campus, Asarwa, Ahmedabad 380016",phone:"+91-79-22682115"},
{n:"KD Hospital",c:"Ahmedabad",t:"Private",r:4.2,b:250,e:1997,s:["Cardiac Sciences","Neurology","Gastroenterology","Orthopedics"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.kdhospital.co.in",addr:"Vaishnodevi Circle, SG Highway, Ahmedabad 382421",phone:"+91-79-66770000"},
{n:"Narayana Multispeciality Ahmedabad",c:"Ahmedabad",t:"Private",r:4.3,b:300,e:2012,s:["Cardiac Sciences","Orthopedics","Neurology","Renal Sciences"],i:["Most TPA","Ayushman Bharat"],a:"NABH",er:1,w:"https://www.narayanahealth.org",addr:"Opp Rakhial Police Station, Rakhial, Ahmedabad 380023",phone:"+91-79-71222222"},
{n:"SAL Hospital",c:"Ahmedabad",t:"Private",r:4.2,b:200,e:2009,s:["General Medicine","Surgery","Orthopedics","Gynaecology"],i:["Most TPA"],a:"NABH",er:1,w:"https://www.salhospital.com",addr:"Opp Doordarshan Tower, Drive-in Road, Thaltej, Ahmedabad 380054",phone:"+91-79-26858090"},
{n:"VS General Hospital",c:"Ahmedabad",t:"Government",r:4.0,b:1200,e:1915,s:["General Medicine","Surgery","Trauma","Orthopedics"],i:["CGHS","Ayushman Bharat"],a:"NABH",er:1,w:"",addr:"Ellis Bridge, Ahmedabad 380006",phone:"+91-79-26577621"}

];

// Specialty category groups for filter UI
window.WIB_HOSPITAL_SPEC_CATEGORIES = {
  'Cardiac & Vascular': ['Cardiac','Cardiology','Cardiac Surgery','Cardiac Sciences','Interventional Cardiology','Vascular','Vascular Surgery','Paediatric Cardiac','Heart Transplant'],
  'Cancer & Oncology': ['Oncology','Surgical Oncology','Radiation Oncology','Radiation','Radiation Therapy','BMT','Bone Marrow Transplant','Chemotherapy','Paediatric Oncology','Gynae Oncology','Haematology'],
  'Brain & Spine': ['Neurology','Neurosciences','Neuroscience','Neurosurgery','Spine'],
  'Bones & Joints': ['Orthopedics','Joint Replacement','Sports Medicine','Trauma'],
  'Digestive & Liver': ['Gastroenterology','Hepatology','Liver Transplant','Surgical Gastro'],
  'Kidney & Urology': ['Nephrology','Renal Sciences','Renal Transplant','Kidney Transplant','Urology'],
  'Women & Children': ['Gynaecology','IVF','Maternity','Neonatal','Obstetrics','Fertility','Paediatrics','Paediatric Surgery','Neonatology','PICU'],
  'Eye Care': ['Ophthalmology','Cataract','Retina','Glaucoma','Cornea'],
  'Mental Health': ['Psychiatry','Clinical Psychology'],
  'Transplant & Robotics': ['Transplant','Robotic Surgery','Robotics','Minimal Invasive Surgery','Bariatric Surgery'],
  'General Medicine': ['General Medicine','Surgery','Internal Medicine','General Surgery','General','Critical Care','Emergency','Burns','Diabetology','Dental']
};

// Helper: get the category for a raw specialty string
window.WIB_getHospitalCategory = function(spec){
  for (var cat in window.WIB_HOSPITAL_SPEC_CATEGORIES) {
    if (window.WIB_HOSPITAL_SPEC_CATEGORIES[cat].indexOf(spec) !== -1) return cat;
  }
  return 'Other';
};

// Helper: build a Practo hospital-search URL (real, not Google)
// Practo URL pattern: https://www.practo.com/[city-slug]/hospitals?q=[name]
window.WIB_practoUrl = function(name, city){
  var citySlug = (city||'').toLowerCase().replace(/\s+/g,'-');
  return 'https://www.practo.com/' + encodeURIComponent(citySlug) + '/hospitals?q=' + encodeURIComponent(name||'');
};
