window.WIB_RESTAURANTS = [
// Delhi
{n:"Bukhara",c:"Delhi",cu:["North Indian","Mughlai","Fine Dining"],r:4.7,b:3,a:"ITC Maurya, Sardar Patel Marg",v:1,z:"bukhara-itc-maurya-chanakyapuri-new-delhi"},
{n:"Indian Accent",c:"Delhi",cu:["Modern Indian","Fine Dining"],r:4.8,b:3,a:"The Lodhi, Lodhi Road",v:1,z:"indian-accent-the-lodhi-new-delhi"},
{n:"Karim's",c:"Delhi",cu:["Mughlai","North Indian","Street Food"],r:4.5,b:1,a:"Jama Masjid, Old Delhi",v:1,z:"karims-jama-masjid-old-delhi"},
{n:"Paranthe Wali Gali",c:"Delhi",cu:["North Indian","Street Food","Vegetarian"],r:4.2,b:1,a:"Chandni Chowk, Old Delhi",v:0,z:"paranthe-wali-gali-chandni-chowk"},
{n:"Saravana Bhavan",c:"Delhi",cu:["South Indian","Vegetarian"],r:4.4,b:1,a:"Connaught Place, New Delhi",v:1,z:"saravana-bhavan-connaught-place"},
{n:"SodaBottleOpenerWala",c:"Delhi",cu:["Parsi","Cafe","Continental"],r:4.3,b:2,a:"Khan Market, New Delhi",v:1,z:"sodabottleopenerwala-khan-market"},
{n:"Moti Mahal",c:"Delhi",cu:["North Indian","Mughlai"],r:4.3,b:2,a:"Daryaganj, Old Delhi",v:1,z:"moti-mahal-delux-daryaganj"},
{n:"Farzi Cafe",c:"Delhi",cu:["Modern Indian","Continental","Cafe"],r:4.4,b:2,a:"Connaught Place",v:1,z:"farzi-cafe-connaught-place"},
// Mumbai
{n:"Trishna",c:"Mumbai",cu:["Seafood","South Indian","Crab"],r:4.6,b:2,a:"Kala Ghoda, Fort",v:1,z:"trishna-kala-ghoda-fort"},
{n:"Leopold Cafe",c:"Mumbai",cu:["Continental","Cafe","North Indian"],r:4.3,b:2,a:"Colaba Causeway",v:1,z:"leopold-cafe-colaba"},
{n:"Bademiya",c:"Mumbai",cu:["Mughlai","Street Food","Kebabs"],r:4.4,b:1,a:"Tulloch Road, Colaba",v:0,z:"bademiya-colaba"},
{n:"The Bombay Canteen",c:"Mumbai",cu:["Modern Indian","Continental"],r:4.6,b:3,a:"Kamala Mills, Lower Parel",v:1,z:"the-bombay-canteen-lower-parel"},
{n:"Britannia & Co",c:"Mumbai",cu:["Parsi","Iranian","Cafe"],r:4.5,b:1,a:"Ballard Estate, Fort",v:1,z:"britannia-and-co-ballard-estate"},
{n:"Swati Snacks",c:"Mumbai",cu:["Street Food","Vegetarian","Gujarati"],r:4.5,b:1,a:"Tardeo, Mumbai",v:1,z:"swati-snacks-tardeo"},
{n:"Peshawri",c:"Mumbai",cu:["North Indian","Mughlai","Fine Dining"],r:4.6,b:3,a:"ITC Maratha, Andheri",v:1,z:"peshawri-itc-maratha-andheri"},
{n:"Bastian",c:"Mumbai",cu:["Seafood","Continental","Fine Dining"],r:4.5,b:3,a:"Bandra West",v:1,z:"bastian-bandra-west"},
// Chennai
{n:"Murugan Idli Shop",c:"Chennai",cu:["South Indian","Vegetarian"],r:4.5,b:1,a:"T Nagar, Chennai",v:1,z:"murugan-idli-shop-t-nagar"},
{n:"Saravana Bhavan",c:"Chennai",cu:["South Indian","Vegetarian"],r:4.5,b:1,a:"Cathedral Road, Chennai",v:1,z:"saravana-bhavan-cathedral-road-chennai"},
{n:"Ponnusamy Hotel",c:"Chennai",cu:["Chettinad","South Indian","Non-Veg"],r:4.4,b:2,a:"Egmore, Chennai",v:1,z:"ponnusamy-hotel-egmore"},
{n:"Dakshin",c:"Chennai",cu:["South Indian","Fine Dining","Chettinad"],r:4.6,b:3,a:"ITC Grand Chola, Guindy",v:1,z:"dakshin-itc-grand-chola-guindy"},
{n:"Dhaba Express",c:"Chennai",cu:["North Indian","Punjabi"],r:4.2,b:1,a:"Anna Nagar, Chennai",v:1,z:"dhaba-express-anna-nagar"},
{n:"Junior Kuppanna",c:"Chennai",cu:["South Indian","Biryani","Chettinad"],r:4.3,b:2,a:"Egmore, Chennai",v:1,z:"junior-kuppanna-egmore"},
{n:"Benjarong",c:"Chennai",cu:["Thai","Fine Dining"],r:4.5,b:3,a:"Dakshin Hotel, TTK Road",v:1,z:"benjarong-ttk-road-chennai"},
{n:"Anjappar",c:"Chennai",cu:["Chettinad","South Indian"],r:4.3,b:2,a:"Multiple outlets, Chennai",v:1,z:"anjappar-chettinad-restaurant-chennai"},
// Bangalore
{n:"MTR (Mavalli Tiffin Rooms)",c:"Bangalore",cu:["South Indian","Vegetarian"],r:4.6,b:1,a:"Lalbagh Road, Bangalore",v:1,z:"mavalli-tiffin-rooms-basavanagudi"},
{n:"Vidyarthi Bhavan",c:"Bangalore",cu:["South Indian","Vegetarian"],r:4.5,b:1,a:"Gandhi Bazaar, Basavanagudi",v:1,z:"vidyarthi-bhavan-gandhi-bazaar"},
{n:"Karavalli",c:"Bangalore",cu:["Coastal","Seafood","Fine Dining"],r:4.6,b:3,a:"The Gateway Hotel, Residency Road",v:1,z:"karavalli-gateway-hotel-residency-road"},
{n:"Meghana Foods",c:"Bangalore",cu:["Biryani","Andhra","South Indian"],r:4.4,b:1,a:"Multiple outlets, Bangalore",v:1,z:"meghana-foods-koramangala"},
{n:"Truffles",c:"Bangalore",cu:["Continental","Cafe","Burgers"],r:4.4,b:2,a:"St. Marks Road, Bangalore",v:1,z:"truffles-st-marks-road"},
{n:"Empire Restaurant",c:"Bangalore",cu:["Biryani","North Indian","Kebabs"],r:4.3,b:1,a:"Church Street, Bangalore",v:1,z:"empire-restaurant-church-street"},
{n:"The Only Place",c:"Bangalore",cu:["Continental","Steaks"],r:4.4,b:2,a:"Museum Road, Bangalore",v:1,z:"the-only-place-museum-road"},
{n:"Toit Brewpub",c:"Bangalore",cu:["Continental","Cafe","Brewery"],r:4.4,b:2,a:"100 Feet Road, Indiranagar",v:1,z:"toit-indiranagar"},
// Kolkata
{n:"Peter Cat",c:"Kolkata",cu:["Continental","North Indian"],r:4.5,b:2,a:"Park Street, Kolkata",v:1,z:"peter-cat-park-street"},
{n:"6 Ballygunge Place",c:"Kolkata",cu:["Bengali","Fine Dining"],r:4.5,b:2,a:"Ballygunge, Kolkata",v:1,z:"6-ballygunge-place"},
{n:"Arsalan",c:"Kolkata",cu:["Biryani","Mughlai"],r:4.5,b:1,a:"Park Circus, Kolkata",v:1,z:"arsalan-park-circus"},
{n:"Oh! Calcutta",c:"Kolkata",cu:["Bengali","Fine Dining"],r:4.4,b:3,a:"Forum Mall, Elgin Road",v:1,z:"oh-calcutta-elgin-road"},
{n:"Kewpie's",c:"Kolkata",cu:["Bengali","Home-style"],r:4.6,b:2,a:"Elgin Lane, Kolkata",v:1,z:"kewpies-kitchen-elgin-lane"},
{n:"Flurys",c:"Kolkata",cu:["Cafe","Bakery","Continental"],r:4.4,b:2,a:"Park Street, Kolkata",v:1,z:"flurys-park-street"},
// Hyderabad
{n:"Paradise Biryani",c:"Hyderabad",cu:["Biryani","Mughlai"],r:4.5,b:1,a:"MG Road, Secunderabad",v:1,z:"paradise-biryani-secunderabad"},
{n:"Bawarchi",c:"Hyderabad",cu:["Biryani","North Indian"],r:4.3,b:1,a:"RTC X Roads, Hyderabad",v:1,z:"bawarchi-rtc-x-roads"},
{n:"Shah Ghouse",c:"Hyderabad",cu:["Biryani","Mughlai","Haleem"],r:4.4,b:1,a:"Tolichowki, Hyderabad",v:1,z:"shah-ghouse-tolichowki"},
{n:"Chutneys",c:"Hyderabad",cu:["South Indian","Vegetarian"],r:4.4,b:1,a:"Banjara Hills, Hyderabad",v:1,z:"chutneys-banjara-hills"},
{n:"Ohri's Jiva Imperia",c:"Hyderabad",cu:["Fine Dining","Continental","North Indian"],r:4.3,b:3,a:"Banjara Hills, Hyderabad",v:1,z:"ohris-jiva-imperia-banjara-hills"},
{n:"Absolute Barbecues",c:"Hyderabad",cu:["BBQ","Continental","North Indian"],r:4.4,b:2,a:"Jubilee Hills, Hyderabad",v:1,z:"absolute-barbecues-jubilee-hills"},
{n:"Kritunga",c:"Hyderabad",cu:["Andhra","South Indian"],r:4.3,b:1,a:"Kukatpally, Hyderabad",v:1,z:"kritunga-kukatpally"},
{n:"Pista House",c:"Hyderabad",cu:["Biryani","Haleem","Mughlai"],r:4.3,b:1,a:"Nampally, Hyderabad",v:1,z:"pista-house-nampally"},
// Bangalore — additions (high-demand city, expanded)
{n:"Corner House",c:"Bangalore",cu:["Ice Cream","Desserts"],r:4.5,b:1,a:"Residency Road, Bangalore",v:1,z:"corner-house-residency-road"},
{n:"Nagarjuna",c:"Bangalore",cu:["Andhra","South Indian","Biryani"],r:4.4,b:2,a:"Residency Road, Bangalore",v:1,z:"nagarjuna-residency-road"},
{n:"Brahmin's Coffee Bar",c:"Bangalore",cu:["South Indian","Vegetarian","Breakfast"],r:4.5,b:1,a:"Shankarapuram, Bangalore",v:1,z:"brahmins-coffee-bar-shankarapuram"},
{n:"Koshy's",c:"Bangalore",cu:["Continental","Anglo-Indian","Cafe"],r:4.4,b:2,a:"St. Marks Road, Bangalore",v:1,z:"koshys-st-marks-road"},
{n:"CTR (Central Tiffin Room)",c:"Bangalore",cu:["South Indian","Breakfast","Vegetarian"],r:4.5,b:1,a:"Malleshwaram, Bangalore",v:1,z:"sri-sagar-ctr-malleshwaram"},
{n:"Rajdhani",c:"Bangalore",cu:["Gujarati","Rajasthani","Thali"],r:4.3,b:2,a:"Forum Mall, Koramangala",v:1,z:"rajdhani-forum-koramangala"},
{n:"Barbeque Nation",c:"Bangalore",cu:["BBQ","North Indian","Buffet"],r:4.3,b:2,a:"Koramangala, Bangalore",v:1,z:"barbeque-nation-koramangala"},
{n:"Hard Rock Cafe",c:"Bangalore",cu:["Continental","American","Bar"],r:4.3,b:3,a:"St. Marks Road, Bangalore",v:1,z:"hard-rock-cafe-st-marks-road"},
{n:"Fava",c:"Bangalore",cu:["Mediterranean","Continental"],r:4.4,b:3,a:"UB City, Vittal Mallya Road",v:1,z:"fava-ub-city"},
{n:"Olive Beach",c:"Bangalore",cu:["Mediterranean","Fine Dining"],r:4.4,b:3,a:"Wood Street, Bangalore",v:1,z:"olive-beach-wood-street"},
{n:"Windmills Craftworks",c:"Bangalore",cu:["Continental","Brewery","Jazz"],r:4.4,b:3,a:"Whitefield, Bangalore",v:1,z:"windmills-craftworks-whitefield"},
{n:"Arbor Brewing Company",c:"Bangalore",cu:["American","Brewery","Pizza"],r:4.3,b:2,a:"Magrath Road, Bangalore",v:1,z:"arbor-brewing-magrath-road"},
// Pune (new city)
{n:"Vaishali",c:"Pune",cu:["South Indian","Vegetarian","Breakfast"],r:4.5,b:1,a:"FC Road, Pune",v:1,z:"vaishali-fc-road"},
{n:"Shabree",c:"Pune",cu:["Maharashtrian","Thali","Vegetarian"],r:4.4,b:2,a:"Karve Road, Pune",v:1,z:"shabree-karve-road"},
{n:"Malaka Spice",c:"Pune",cu:["Pan-Asian","Thai","Fine Dining"],r:4.4,b:3,a:"Koregaon Park, Pune",v:1,z:"malaka-spice-koregaon-park"},
{n:"German Bakery",c:"Pune",cu:["Cafe","Continental","Bakery"],r:4.3,b:2,a:"Koregaon Park, Pune",v:1,z:"german-bakery-koregaon-park"},
{n:"Blue Nile",c:"Pune",cu:["Mughlai","Biryani","North Indian"],r:4.3,b:2,a:"Camp, Pune",v:1,z:"blue-nile-camp-pune"},
{n:"Durga",c:"Pune",cu:["Maharashtrian","Indian","Thali"],r:4.2,b:1,a:"Tilak Road, Pune",v:1,z:"durga-restaurant-tilak-road"},
{n:"Marz-o-rin",c:"Pune",cu:["Cafe","Bakery","Continental"],r:4.3,b:2,a:"MG Road, Camp, Pune",v:1,z:"marz-o-rin-mg-road-pune"},
{n:"Dario's",c:"Pune",cu:["Italian","Fine Dining"],r:4.5,b:3,a:"Koregaon Park, Pune",v:1,z:"darios-koregaon-park"},
// Ahmedabad (new city)
{n:"Agashiye",c:"Ahmedabad",cu:["Gujarati","Thali","Fine Dining"],r:4.6,b:3,a:"The House of MG, Lal Darwaja",v:1,z:"agashiye-house-of-mg"},
{n:"Vishalla",c:"Ahmedabad",cu:["Gujarati","Thali","Traditional"],r:4.4,b:2,a:"Vasna, Ahmedabad",v:1,z:"vishalla-vasna"},
{n:"Gopi Dining Hall",c:"Ahmedabad",cu:["Gujarati","Thali","Vegetarian"],r:4.4,b:1,a:"Ellis Bridge, Ahmedabad",v:1,z:"gopi-dining-hall-ellis-bridge"},
{n:"Chandravilas",c:"Ahmedabad",cu:["Gujarati","Snacks","Vegetarian"],r:4.3,b:1,a:"Gandhi Road, Ahmedabad",v:1,z:"chandravilas-gandhi-road"},
{n:"Tomato's",c:"Ahmedabad",cu:["Italian","Cafe","Pizza"],r:4.3,b:2,a:"CG Road, Ahmedabad",v:0,z:"tomatos-cg-road"},
{n:"Swati Snacks",c:"Ahmedabad",cu:["Gujarati","Chaat","Vegetarian"],r:4.4,b:1,a:"Law Garden, Ahmedabad",v:1,z:"swati-snacks-law-garden"},
// Coimbatore (new city)
{n:"Annapoorna Gowrishankar",c:"Coimbatore",cu:["South Indian","Vegetarian"],r:4.4,b:1,a:"RS Puram, Coimbatore",v:1,z:"annapoorna-rs-puram"},
{n:"Junior Kuppanna",c:"Coimbatore",cu:["Chettinad","South Indian","Biryani"],r:4.4,b:2,a:"Race Course, Coimbatore",v:1,z:"junior-kuppanna-race-course"},
{n:"Hotel Sree Annapoorna",c:"Coimbatore",cu:["South Indian","Vegetarian"],r:4.3,b:1,a:"Puliakulam, Coimbatore",v:1,z:"hotel-sree-annapoorna-puliakulam"},
{n:"Angannan Biryani",c:"Coimbatore",cu:["Biryani","Chettinad","Non-Veg"],r:4.3,b:1,a:"Gandhipuram, Coimbatore",v:0,z:"angannan-biryani-gandhipuram"},
{n:"The Black Tomato",c:"Coimbatore",cu:["Continental","Cafe","Pizza"],r:4.3,b:2,a:"RS Puram, Coimbatore",v:1,z:"the-black-tomato-rs-puram"},
{n:"On The Go",c:"Coimbatore",cu:["Cafe","Burgers","Continental"],r:4.2,b:2,a:"Race Course, Coimbatore",v:1,z:"on-the-go-race-course"},
// Jaipur (new city)
{n:"Laxmi Misthan Bhandar (LMB)",c:"Jaipur",cu:["Rajasthani","Sweets","Vegetarian"],r:4.4,b:2,a:"Johari Bazaar, Jaipur",v:1,z:"lmb-johari-bazaar"},
{n:"Rawat Mishthan Bhandar",c:"Jaipur",cu:["Rajasthani","Snacks","Vegetarian"],r:4.5,b:1,a:"Station Road, Jaipur",v:1,z:"rawat-mishthan-bhandar-station-road"},
{n:"1135 AD",c:"Jaipur",cu:["Rajasthani","Fine Dining","Royal"],r:4.5,b:3,a:"Amer Fort, Jaipur",v:1,z:"1135-ad-amer-fort"},
{n:"Chokhi Dhani",c:"Jaipur",cu:["Rajasthani","Thali","Folk"],r:4.4,b:2,a:"Tonk Road, Jaipur",v:1,z:"chokhi-dhani-tonk-road"},
{n:"Suvarna Mahal",c:"Jaipur",cu:["Indian","Fine Dining","Royal"],r:4.6,b:3,a:"Rambagh Palace, Jaipur",v:0,z:"suvarna-mahal-rambagh-palace"},
{n:"Tapri Central",c:"Jaipur",cu:["Cafe","Chai","Snacks"],r:4.4,b:1,a:"C Scheme, Jaipur",v:1,z:"tapri-central-c-scheme"},
// Lucknow (new city)
{n:"Tunday Kababi",c:"Lucknow",cu:["Awadhi","Kebabs","Mughlai"],r:4.5,b:1,a:"Aminabad, Lucknow",v:0,z:"tunday-kababi-aminabad"},
{n:"Idris Biryani",c:"Lucknow",cu:["Awadhi","Biryani","Mughlai"],r:4.5,b:1,a:"Chowk, Lucknow",v:0,z:"idris-biryani-chowk"},
{n:"Dastarkhwan",c:"Lucknow",cu:["Awadhi","Mughlai","Kebabs"],r:4.4,b:2,a:"Hazratganj, Lucknow",v:0,z:"dastarkhwan-hazratganj"},
{n:"Moti Mahal",c:"Lucknow",cu:["Mughlai","North Indian"],r:4.3,b:2,a:"Hazratganj, Lucknow",v:0,z:"moti-mahal-hazratganj-lucknow"},
{n:"Royal Cafe",c:"Lucknow",cu:["Chaat","Awadhi","Snacks"],r:4.3,b:1,a:"Hazratganj, Lucknow",v:1,z:"royal-cafe-hazratganj"},
{n:"Oudhyana (Taj Mahal Lucknow)",c:"Lucknow",cu:["Awadhi","Fine Dining"],r:4.5,b:3,a:"Gomti Nagar, Lucknow",v:0,z:"oudhyana-taj-lucknow"},
// Chandigarh (new city)
{n:"Pal Dhaba",c:"Chandigarh",cu:["North Indian","Punjabi","Non-Veg"],r:4.4,b:1,a:"Sector 28, Chandigarh",v:0,z:"pal-dhaba-sector-28"},
{n:"Virgin Courtyard",c:"Chandigarh",cu:["Italian","Continental","Fine Dining"],r:4.4,b:3,a:"Sector 7, Chandigarh",v:1,z:"virgin-courtyard-sector-7"},
{n:"Ghazal",c:"Chandigarh",cu:["North Indian","Mughlai"],r:4.3,b:2,a:"Sector 17, Chandigarh",v:0,z:"ghazal-sector-17"},
{n:"Swagath",c:"Chandigarh",cu:["South Indian","Chettinad","Biryani"],r:4.3,b:2,a:"Sector 26, Chandigarh",v:0,z:"swagath-sector-26"},
{n:"Whistling Duck",c:"Chandigarh",cu:["Continental","Brewery","Pizza"],r:4.3,b:2,a:"Elante Mall, Chandigarh",v:1,z:"whistling-duck-elante"},
{n:"Nik Baker's",c:"Chandigarh",cu:["Cafe","Bakery","Continental"],r:4.3,b:2,a:"Sector 9, Chandigarh",v:1,z:"nik-bakers-sector-9"},
// Kochi (new city)
{n:"Dhe Puttu",c:"Kochi",cu:["Kerala","South Indian","Traditional"],r:4.4,b:1,a:"Panampilly Nagar, Kochi",v:0,z:"dhe-puttu-panampilly-nagar"},
{n:"Fort House Restaurant",c:"Kochi",cu:["Kerala","Seafood","Fine Dining"],r:4.4,b:3,a:"Fort Kochi",v:0,z:"fort-house-restaurant-fort-kochi"},
{n:"Kashi Art Cafe",c:"Kochi",cu:["Cafe","Continental","Breakfast"],r:4.3,b:2,a:"Burgher Street, Fort Kochi",v:1,z:"kashi-art-cafe-fort-kochi"},
{n:"Ariya Nivaas",c:"Kochi",cu:["Kerala","South Indian","Vegetarian"],r:4.3,b:1,a:"MG Road, Ernakulam",v:1,z:"ariya-nivaas-mg-road"},
{n:"The Old Harbour Hotel",c:"Kochi",cu:["Seafood","Kerala","Fine Dining"],r:4.5,b:3,a:"Fort Kochi",v:0,z:"old-harbour-hotel-fort-kochi"},
{n:"Frys Village Restaurant",c:"Kochi",cu:["Kerala","Traditional","Seafood"],r:4.3,b:2,a:"Kadavanthra, Kochi",v:0,z:"frys-village-kadavanthra"},
// Indore (new city)
{n:"Sarafa Bazaar (Street Food)",c:"Indore",cu:["Street Food","Chaat","Indori"],r:4.6,b:1,a:"Sarafa Bazaar, Indore",v:1,z:"sarafa-bazaar-street-food"},
{n:"Chappan Dukan",c:"Indore",cu:["Street Food","Chaat","Indori"],r:4.5,b:1,a:"New Palasia, Indore",v:1,z:"chappan-dukan-new-palasia"},
{n:"Nafees Restaurant",c:"Indore",cu:["Mughlai","Biryani","Kebabs"],r:4.3,b:2,a:"South Tukoganj, Indore",v:0,z:"nafees-south-tukoganj"},
{n:"Indori Zaika",c:"Indore",cu:["Indori","Street Food","Vegetarian"],r:4.3,b:1,a:"Vijay Nagar, Indore",v:1,z:"indori-zaika-vijay-nagar"},
{n:"Mehfil",c:"Indore",cu:["North Indian","Mughlai"],r:4.3,b:2,a:"AB Road, Indore",v:0,z:"mehfil-ab-road"},
{n:"Apna Sweets",c:"Indore",cu:["Sweets","Indori","Snacks"],r:4.4,b:1,a:"Rajmohalla, Indore",v:1,z:"apna-sweets-rajmohalla"},
// Visakhapatnam / Vizag (new city)
{n:"Dharani",c:"Visakhapatnam",cu:["Andhra","South Indian","Seafood"],r:4.4,b:2,a:"Beach Road, Vizag",v:0,z:"dharani-beach-road-vizag"},
{n:"Barbeque Nation",c:"Visakhapatnam",cu:["BBQ","Buffet","Continental"],r:4.3,b:2,a:"Jagadamba Junction, Vizag",v:1,z:"barbeque-nation-jagadamba"},
{n:"Sea Inn Restaurant",c:"Visakhapatnam",cu:["Andhra","Seafood","South Indian"],r:4.3,b:2,a:"Ramakrishna Beach, Vizag",v:0,z:"sea-inn-ramakrishna-beach"},
{n:"Saptagiri",c:"Visakhapatnam",cu:["South Indian","Vegetarian"],r:4.3,b:1,a:"Dwaraka Nagar, Vizag",v:1,z:"saptagiri-dwaraka-nagar"},
{n:"Pulla Reddy Sweets",c:"Visakhapatnam",cu:["Sweets","Snacks","Andhra"],r:4.4,b:1,a:"Asilmetta, Vizag",v:1,z:"pulla-reddy-asilmetta"},
{n:"Bombay Anand Bhavan",c:"Visakhapatnam",cu:["South Indian","North Indian","Chinese"],r:4.2,b:1,a:"Siripuram, Vizag",v:1,z:"bombay-anand-bhavan-siripuram"},

// === EXPANSION BATCH 1 (Apr 2026) — researched real restaurants, +336 ===

// Delhi (22 more)
{n:"Gulati Restaurant",c:"Delhi",cu:["North Indian","Mughlai","Kebabs"],r:4.3,b:2,a:"Pandara Road, New Delhi",v:1,z:"gulati-pandara-road-new-delhi"},
{n:"Havemore",c:"Delhi",cu:["North Indian","Mughlai","Tandoor"],r:4.2,b:2,a:"Pandara Road, New Delhi",v:1,z:"havemore-pandara-road-new-delhi"},
{n:"Big Chill Cafe",c:"Delhi",cu:["Italian","Continental","Cafe"],r:4.4,b:2,a:"Khan Market, New Delhi",v:1,z:"big-chill-khan-market-new-delhi"},
{n:"Mamagoto",c:"Delhi",cu:["Asian","Thai","Pan-Asian"],r:4.3,b:2,a:"Khan Market, New Delhi",v:1,z:"mamagoto-khan-market-new-delhi"},
{n:"Perch Wine and Coffee Bar",c:"Delhi",cu:["Cafe","Continental","Bar"],r:4.4,b:2,a:"Khan Market, New Delhi",v:1,z:"perch-wine-coffee-bar-khan-market-new-delhi"},
{n:"Sagar Ratna",c:"Delhi",cu:["South Indian","Vegetarian"],r:4.1,b:1,a:"Defence Colony, New Delhi",v:1,z:"sagar-ratna-defence-colony-new-delhi"},
{n:"Swagath Restaurant",c:"Delhi",cu:["South Indian","Coastal","Seafood"],r:4.2,b:2,a:"Defence Colony, New Delhi",v:1,z:"swagath-defence-colony-new-delhi"},
{n:"Andhra Bhavan Canteen",c:"Delhi",cu:["Andhra","South Indian","Non-Veg"],r:4.4,b:1,a:"Ashoka Road, New Delhi",v:1,z:"andhra-bhavan-canteen-ashoka-road-new-delhi"},
{n:"Naturals Ice Cream",c:"Delhi",cu:["Ice Cream","Desserts"],r:4.5,b:1,a:"Connaught Place, New Delhi",v:1,z:"naturals-ice-cream-connaught-place-new-delhi"},
{n:"Wenger's",c:"Delhi",cu:["Bakery","Desserts"],r:4.4,b:1,a:"Connaught Place, New Delhi",v:1,z:"wengers-connaught-place-new-delhi"},
{n:"United Coffee House",c:"Delhi",cu:["North Indian","Continental","Cafe"],r:4.3,b:2,a:"Connaught Place, New Delhi",v:1,z:"united-coffee-house-connaught-place-new-delhi"},
{n:"Embassy Restaurant",c:"Delhi",cu:["North Indian","Continental"],r:4.2,b:2,a:"Connaught Place, New Delhi",v:1,z:"embassy-connaught-place-new-delhi"},
{n:"Kake Da Hotel",c:"Delhi",cu:["North Indian","Punjabi"],r:4.2,b:1,a:"Connaught Place, New Delhi",v:1,z:"kake-da-hotel-connaught-place-new-delhi"},
{n:"Dum Pukht",c:"Delhi",cu:["Mughlai","Awadhi","Fine Dining"],r:4.6,b:3,a:"ITC Maurya, Chanakyapuri",v:1,z:"dum-pukht-itc-maurya-chanakyapuri-new-delhi"},
{n:"Varq",c:"Delhi",cu:["Modern Indian","Fine Dining"],r:4.5,b:3,a:"Taj Mahal Hotel, Mansingh Road",v:1,z:"varq-taj-mahal-hotel-new-delhi"},
{n:"Megu",c:"Delhi",cu:["Japanese","Sushi","Fine Dining"],r:4.5,b:3,a:"The Leela Palace, Chanakyapuri",v:1,z:"megu-leela-palace-chanakyapuri-new-delhi"},
{n:"Olive Bar Kitchen",c:"Delhi",cu:["Italian","Mediterranean","Fine Dining"],r:4.4,b:3,a:"Mehrauli, New Delhi",v:1,z:"olive-bar-kitchen-mehrauli-new-delhi"},
{n:"Qla",c:"Delhi",cu:["Modern Indian","Continental","Fine Dining"],r:4.5,b:3,a:"Mehrauli, New Delhi",v:1,z:"qla-mehrauli-new-delhi"},
{n:"Diggin",c:"Delhi",cu:["Italian","Cafe","Continental"],r:4.3,b:2,a:"Anand Lok, New Delhi",v:1,z:"diggin-anand-lok-new-delhi"},
{n:"Rose Cafe",c:"Delhi",cu:["Cafe","Continental","Brunch"],r:4.4,b:2,a:"Saket, New Delhi",v:1,z:"rose-cafe-saket-new-delhi"},
{n:"Pind Balluchi",c:"Delhi",cu:["North Indian","Punjabi","Tandoor"],r:4.0,b:2,a:"Pitampura, New Delhi",v:1,z:"pind-balluchi-pitampura-new-delhi"},
{n:"Carnatic Cafe",c:"Delhi",cu:["South Indian","Vegetarian"],r:4.3,b:1,a:"Lodhi Colony, New Delhi",v:1,z:"carnatic-cafe-lodhi-colony-new-delhi"},

// Mumbai (22 more)
{n:"Jimmy Boy",c:"Mumbai",cu:["Parsi","Iranian"],r:4.3,b:2,a:"Fort, Mumbai",v:1,z:"jimmy-boy-fort-mumbai"},
{n:"Cafe Mondegar",c:"Mumbai",cu:["Continental","Cafe","Bar"],r:4.4,b:2,a:"Colaba, Mumbai",v:1,z:"cafe-mondegar-colaba-mumbai"},
{n:"Theobroma",c:"Mumbai",cu:["Bakery","Desserts","Cafe"],r:4.5,b:1,a:"Colaba Causeway, Colaba",v:1,z:"theobroma-colaba-mumbai"},
{n:"Kala Ghoda Cafe",c:"Mumbai",cu:["Cafe","Continental","Brunch"],r:4.4,b:2,a:"Kala Ghoda, Fort",v:1,z:"kala-ghoda-cafe-fort-mumbai"},
{n:"Gallops",c:"Mumbai",cu:["Continental","North Indian"],r:4.2,b:2,a:"Mahalaxmi Race Course",v:1,z:"gallops-mahalaxmi-mumbai"},
{n:"Soam",c:"Mumbai",cu:["Gujarati","Vegetarian","Jain"],r:4.4,b:2,a:"Babulnath, Chowpatty",v:1,z:"soam-babulnath-mumbai"},
{n:"New Kulfi Centre",c:"Mumbai",cu:["Desserts","Ice Cream"],r:4.5,b:1,a:"Chowpatty, Mumbai",v:1,z:"new-kulfi-centre-chowpatty-mumbai"},
{n:"Bademiya Seekh Kabab",c:"Mumbai",cu:["Mughlai","Kebabs","Street Food"],r:4.3,b:1,a:"Colaba, Mumbai",v:1,z:"bademiya-seekh-kabab-colaba-mumbai"},
{n:"Gajalee",c:"Mumbai",cu:["Coastal","Seafood","Maharashtrian"],r:4.3,b:2,a:"Vile Parle West, Mumbai",v:1,z:"gajalee-vile-parle-mumbai"},
{n:"Mahesh Lunch Home",c:"Mumbai",cu:["Coastal","Seafood","Mangalorean"],r:4.4,b:2,a:"Fort, Mumbai",v:1,z:"mahesh-lunch-home-fort-mumbai"},
{n:"Highway Gomantak",c:"Mumbai",cu:["Goan","Coastal","Seafood"],r:4.3,b:2,a:"Bandra East, Mumbai",v:1,z:"highway-gomantak-bandra-east-mumbai"},
{n:"Pali Village Cafe",c:"Mumbai",cu:["Italian","Mediterranean","Continental"],r:4.4,b:3,a:"Pali Hill, Bandra West",v:1,z:"pali-village-cafe-bandra-west-mumbai"},
{n:"Bastian at the Top",c:"Mumbai",cu:["Asian","Seafood","Fine Dining"],r:4.6,b:3,a:"Worli, Mumbai",v:1,z:"bastian-at-the-top-worli-mumbai"},
{n:"Masque",c:"Mumbai",cu:["Modern Indian","Fine Dining"],r:4.7,b:3,a:"Mathuradas Mills, Lower Parel",v:1,z:"masque-lower-parel-mumbai"},
{n:"Americano",c:"Mumbai",cu:["Italian","Mediterranean","Fine Dining"],r:4.6,b:3,a:"Kala Ghoda, Fort",v:1,z:"americano-kala-ghoda-mumbai"},
{n:"Hakkasan",c:"Mumbai",cu:["Chinese","Asian","Fine Dining"],r:4.5,b:3,a:"Bandra West, Mumbai",v:1,z:"hakkasan-bandra-west-mumbai"},
{n:"Yauatcha",c:"Mumbai",cu:["Chinese","Asian","Fine Dining"],r:4.5,b:3,a:"Bandra Kurla Complex, Mumbai",v:1,z:"yauatcha-bkc-mumbai"},
{n:"Social Khar",c:"Mumbai",cu:["Continental","Bar","Pub"],r:4.3,b:2,a:"Khar West, Mumbai",v:1,z:"social-khar-mumbai"},
{n:"Gateway Taproom",c:"Mumbai",cu:["Brewery","Continental","Pub"],r:4.3,b:2,a:"Andheri West, Mumbai",v:1,z:"gateway-taproom-andheri-west-mumbai"},
{n:"Persian Darbar",c:"Mumbai",cu:["Mughlai","Biryani","Kebabs"],r:4.2,b:2,a:"Bandra West, Mumbai",v:1,z:"persian-darbar-bandra-west-mumbai"},
{n:"Shree Thaker Bhojanalay",c:"Mumbai",cu:["Gujarati","Vegetarian"],r:4.4,b:2,a:"Kalbadevi, Mumbai",v:1,z:"shree-thaker-bhojanalay-kalbadevi-mumbai"},
{n:"Cafe Madras",c:"Mumbai",cu:["South Indian","Vegetarian"],r:4.4,b:1,a:"Matunga, Mumbai",v:1,z:"cafe-madras-matunga-mumbai"},

// Bangalore (10 more)
{n:"The Permit Room",c:"Bangalore",cu:["South Indian","Modern Indian","Bar"],r:4.4,b:2,a:"Lavelle Road, Bangalore",v:1,z:"the-permit-room-lavelle-road-bangalore"},
{n:"SodaBottleOpenerWala Bangalore",c:"Bangalore",cu:["Parsi","Iranian","Cafe"],r:4.3,b:2,a:"Lavelle Road, Bangalore",v:1,z:"sodabottleopenerwala-lavelle-road-bangalore"},
{n:"Smoke House Deli",c:"Bangalore",cu:["Continental","Italian","Cafe"],r:4.3,b:2,a:"Indiranagar, Bangalore",v:1,z:"smoke-house-deli-indiranagar-bangalore"},
{n:"Glen's Bakehouse",c:"Bangalore",cu:["Bakery","Cafe","Desserts"],r:4.5,b:2,a:"Indiranagar, Bangalore",v:1,z:"glens-bakehouse-indiranagar-bangalore"},
{n:"Byg Brewski Brewing Company",c:"Bangalore",cu:["Brewery","Continental","Pub"],r:4.5,b:2,a:"Sarjapur Road, Bangalore",v:1,z:"byg-brewski-brewing-company-sarjapur-bangalore"},
{n:"Communiti",c:"Bangalore",cu:["Brewery","Continental","Pub"],r:4.4,b:2,a:"Koramangala, Bangalore",v:1,z:"communiti-koramangala-bangalore"},
{n:"Plan B Loaded",c:"Bangalore",cu:["American","Burgers","Pub"],r:4.3,b:2,a:"Indiranagar, Bangalore",v:1,z:"plan-b-loaded-indiranagar-bangalore"},
{n:"Konark Restaurant",c:"Bangalore",cu:["Andhra","Biryani","Non-Veg"],r:4.2,b:1,a:"Jayanagar, Bangalore",v:1,z:"konark-jayanagar-bangalore"},
{n:"Farzi Cafe Bangalore",c:"Bangalore",cu:["Modern Indian","Bar","Lounge"],r:4.3,b:2,a:"UB City, Bangalore",v:1,z:"farzi-cafe-ub-city-bangalore"},
{n:"Hari Super Sandwich",c:"Bangalore",cu:["South Indian","Street Food","Vegetarian"],r:4.3,b:1,a:"Jayanagar, Bangalore",v:1,z:"hari-super-sandwich-jayanagar-bangalore"},

// Chennai (22 more)
{n:"Peshawri Chennai",c:"Chennai",cu:["North Indian","Tandoor","Fine Dining"],r:4.5,b:3,a:"ITC Grand Chola, Guindy",v:1,z:"peshawri-itc-grand-chola-guindy-chennai"},
{n:"Southern Spice",c:"Chennai",cu:["South Indian","Chettinad","Fine Dining"],r:4.6,b:3,a:"Taj Coromandel, Nungambakkam",v:1,z:"southern-spice-taj-coromandel-nungambakkam-chennai"},
{n:"Avartana",c:"Chennai",cu:["Modern Indian","South Indian","Fine Dining"],r:4.7,b:3,a:"ITC Grand Chola, Guindy",v:1,z:"avartana-itc-grand-chola-guindy-chennai"},
{n:"The Flying Elephant",c:"Chennai",cu:["Continental","Asian","Fine Dining"],r:4.5,b:3,a:"Park Hyatt, Velachery",v:1,z:"the-flying-elephant-park-hyatt-velachery-chennai"},
{n:"Royal Vega",c:"Chennai",cu:["Vegetarian","North Indian","Fine Dining"],r:4.6,b:3,a:"ITC Grand Chola, Guindy",v:1,z:"royal-vega-itc-grand-chola-guindy-chennai"},
{n:"Buhari Hotel",c:"Chennai",cu:["Biryani","North Indian","Kebabs"],r:4.2,b:2,a:"Anna Salai, Mount Road",v:1,z:"buhari-hotel-anna-salai-chennai"},
{n:"Ente Keralam",c:"Chennai",cu:["Kerala","South Indian","Seafood"],r:4.4,b:2,a:"Poes Garden, Teynampet",v:1,z:"ente-keralam-poes-garden-chennai"},
{n:"Kaaraikudi",c:"Chennai",cu:["Chettinad","South Indian","Biryani"],r:4.3,b:2,a:"T Nagar",v:1,z:"kaaraikudi-t-nagar-chennai"},
{n:"Sangeetha Veg Restaurant",c:"Chennai",cu:["South Indian","North Indian","Vegetarian"],r:4.2,b:2,a:"Nungambakkam",v:1,z:"sangeetha-veg-restaurant-nungambakkam-chennai"},
{n:"Adyar Ananda Bhavan",c:"Chennai",cu:["South Indian","Vegetarian","Desserts"],r:4.3,b:1,a:"Adyar",v:1,z:"adyar-ananda-bhavan-adyar-chennai"},
{n:"Copper Chimney",c:"Chennai",cu:["North Indian","Tandoor","Kebabs"],r:4.3,b:2,a:"Greams Road",v:1,z:"copper-chimney-greams-road-chennai"},
{n:"Cream Centre",c:"Chennai",cu:["Vegetarian","Continental","Mexican"],r:4.2,b:2,a:"RA Puram",v:1,z:"cream-centre-ra-puram-chennai"},
{n:"Tuscana Pizzeria",c:"Chennai",cu:["Italian","Pizza","Continental"],r:4.4,b:2,a:"Khader Nawaz Khan Road, Nungambakkam",v:1,z:"tuscana-pizzeria-khader-nawaz-khan-road-chennai"},
{n:"Amethyst Cafe",c:"Chennai",cu:["Cafe","Continental","Brunch"],r:4.4,b:2,a:"Royapettah",v:1,z:"amethyst-cafe-royapettah-chennai"},
{n:"Writer's Cafe",c:"Chennai",cu:["Cafe","Continental","Bakery"],r:4.5,b:2,a:"Gopalapuram",v:1,z:"writers-cafe-gopalapuram-chennai"},
{n:"Ciclo Cafe",c:"Chennai",cu:["Cafe","Continental","Italian"],r:4.4,b:2,a:"RA Puram",v:1,z:"ciclo-cafe-ra-puram-chennai"},
{n:"Madras Pavilion",c:"Chennai",cu:["South Indian","North Indian","Family"],r:4.3,b:3,a:"ITC Grand Chola, Guindy",v:1,z:"madras-pavilion-itc-grand-chola-chennai"},
{n:"Zaitoon",c:"Chennai",cu:["North Indian","Biryani","Kebabs"],r:4.2,b:2,a:"OMR, Thoraipakkam",v:1,z:"zaitoon-omr-chennai"},
{n:"Yumbox",c:"Chennai",cu:["Asian","Continental","Cafe"],r:4.3,b:2,a:"Anna Nagar",v:1,z:"yumbox-anna-nagar-chennai"},
{n:"Eden Chennai",c:"Chennai",cu:["Continental","Asian","Fine Dining"],r:4.4,b:3,a:"The Park, Nungambakkam",v:1,z:"eden-the-park-nungambakkam-chennai"},
{n:"Zara Tapas Bar",c:"Chennai",cu:["Continental","Bar","Mexican"],r:4.3,b:3,a:"Khader Nawaz Khan Road, Nungambakkam",v:1,z:"zara-tapas-bar-nungambakkam-chennai"},
{n:"Ministry of Beer Chennai",c:"Chennai",cu:["Brewery","Continental","Bar"],r:4.2,b:2,a:"Phoenix Marketcity, Velachery",v:1,z:"ministry-of-beer-phoenix-marketcity-chennai"},

// Hyderabad (22 more)
{n:"Jewel of Nizam",c:"Hyderabad",cu:["Hyderabadi","Biryani","Fine Dining"],r:4.6,b:3,a:"The Golkonda, Masab Tank",v:1,z:"jewel-of-nizam-the-golkonda-hyderabad"},
{n:"Firdaus",c:"Hyderabad",cu:["Hyderabadi","Mughlai","Fine Dining"],r:4.5,b:3,a:"Taj Krishna, Banjara Hills",v:1,z:"firdaus-taj-krishna-banjara-hills-hyderabad"},
{n:"Adaa",c:"Hyderabad",cu:["Hyderabadi","North Indian","Fine Dining"],r:4.6,b:3,a:"Taj Falaknuma Palace",v:1,z:"adaa-taj-falaknuma-palace-hyderabad"},
{n:"Celeste",c:"Hyderabad",cu:["Italian","Continental","Fine Dining"],r:4.5,b:3,a:"Taj Falaknuma Palace",v:1,z:"celeste-taj-falaknuma-palace-hyderabad"},
{n:"Dakshin Hyderabad",c:"Hyderabad",cu:["South Indian","Chettinad","Fine Dining"],r:4.5,b:3,a:"ITC Kakatiya, Begumpet",v:1,z:"dakshin-itc-kakatiya-begumpet-hyderabad"},
{n:"Cafe Bahar",c:"Hyderabad",cu:["Biryani","Hyderabadi","Kebabs"],r:4.3,b:2,a:"Basheerbagh",v:1,z:"cafe-bahar-basheerbagh-hyderabad"},
{n:"Hotel Shadab",c:"Hyderabad",cu:["Biryani","Hyderabadi","Mughlai"],r:4.3,b:2,a:"Ghansi Bazar, Charminar",v:1,z:"hotel-shadab-charminar-hyderabad"},
{n:"Mehfil Restaurant Hyderabad",c:"Hyderabad",cu:["North Indian","Biryani","Mughlai"],r:4.2,b:2,a:"Ameerpet",v:1,z:"mehfil-restaurant-ameerpet-hyderabad"},
{n:"Olive Bistro",c:"Hyderabad",cu:["Italian","Mediterranean","Fine Dining"],r:4.5,b:3,a:"Durgam Cheruvu, Jubilee Hills",v:1,z:"olive-bistro-jubilee-hills-hyderabad"},
{n:"Fusion 9",c:"Hyderabad",cu:["Continental","Asian","Italian"],r:4.4,b:3,a:"Road No 1, Banjara Hills",v:1,z:"fusion-9-banjara-hills-hyderabad"},
{n:"Barbeque Nation Hyderabad",c:"Hyderabad",cu:["BBQ","North Indian","Family"],r:4.3,b:2,a:"Banjara Hills",v:1,z:"barbeque-nation-banjara-hills-hyderabad"},
{n:"Deccan Pavilion",c:"Hyderabad",cu:["North Indian","South Indian","Family"],r:4.3,b:3,a:"ITC Kakatiya, Begumpet",v:1,z:"deccan-pavilion-itc-kakatiya-hyderabad"},
{n:"Ulavacharu Hyderabad",c:"Hyderabad",cu:["Andhra","South Indian","Biryani"],r:4.3,b:2,a:"Jubilee Hills",v:1,z:"ulavacharu-jubilee-hills-hyderabad"},
{n:"Spicy Venue",c:"Hyderabad",cu:["Andhra","Hyderabadi","Biryani"],r:4.2,b:2,a:"Jubilee Hills",v:1,z:"spicy-venue-jubilee-hills-hyderabad"},
{n:"Southern Spice Hyderabad",c:"Hyderabad",cu:["Andhra","South Indian","Chettinad"],r:4.3,b:2,a:"Banjara Hills",v:1,z:"southern-spice-banjara-hills-hyderabad"},
{n:"Sahib's Barbeque",c:"Hyderabad",cu:["BBQ","North Indian","Kebabs"],r:4.2,b:2,a:"Gachibowli",v:1,z:"sahibs-barbeque-gachibowli-hyderabad"},
{n:"Roastery Coffee House",c:"Hyderabad",cu:["Cafe","Continental","Bakery"],r:4.5,b:2,a:"Banjara Hills",v:1,z:"roastery-coffee-house-banjara-hills-hyderabad"},
{n:"Concu",c:"Hyderabad",cu:["Cafe","Bakery","Desserts"],r:4.6,b:2,a:"Jubilee Hills",v:1,z:"concu-jubilee-hills-hyderabad"},
{n:"Prost Brew Pub",c:"Hyderabad",cu:["Brewery","Continental","Bar"],r:4.3,b:3,a:"Gachibowli",v:1,z:"prost-brew-pub-gachibowli-hyderabad"},
{n:"Hard Rock Cafe Hyderabad",c:"Hyderabad",cu:["Continental","American","Bar"],r:4.4,b:3,a:"GVK One Mall, Banjara Hills",v:1,z:"hard-rock-cafe-banjara-hills-hyderabad"},
{n:"Mainland China Hyderabad",c:"Hyderabad",cu:["Chinese","Asian","Family"],r:4.3,b:3,a:"Banjara Hills",v:1,z:"mainland-china-banjara-hills-hyderabad"},
{n:"Tatva",c:"Hyderabad",cu:["Vegetarian","North Indian","Fine Dining"],r:4.3,b:3,a:"Jubilee Hills",v:1,z:"tatva-jubilee-hills-hyderabad"},

// Pune (22 more)
{n:"Le Plaisir",c:"Pune",cu:["French","Continental","Fine Dining"],r:4.5,b:3,a:"Koregaon Park",v:1,z:"le-plaisir-koregaon-park-pune"},
{n:"Arthur's Theme",c:"Pune",cu:["Continental","Italian","Fine Dining"],r:4.5,b:3,a:"Koregaon Park",v:1,z:"arthurs-theme-koregaon-park-pune"},
{n:"The Flour Works",c:"Pune",cu:["Cafe","Bakery","Continental"],r:4.5,b:2,a:"Koregaon Park",v:1,z:"the-flour-works-koregaon-park-pune"},
{n:"Prem's",c:"Pune",cu:["North Indian","Continental","Family"],r:4.3,b:2,a:"Koregaon Park",v:1,z:"prems-koregaon-park-pune"},
{n:"ABC Farms",c:"Pune",cu:["Continental","Italian","Family"],r:4.2,b:2,a:"Koregaon Park",v:1,z:"abc-farms-koregaon-park-pune"},
{n:"Sigree Global Grill",c:"Pune",cu:["BBQ","North Indian","Kebabs"],r:4.3,b:2,a:"Viman Nagar",v:1,z:"sigree-global-grill-viman-nagar-pune"},
{n:"The Great Punjab",c:"Pune",cu:["North Indian","Tandoor","Family"],r:4.3,b:2,a:"Aundh",v:1,z:"the-great-punjab-aundh-pune"},
{n:"Poona Guest House",c:"Pune",cu:["Maharashtrian","Seafood","Coastal"],r:4.3,b:2,a:"Narayan Peth",v:1,z:"poona-guest-house-narayan-peth-pune"},
{n:"Janseva Bhojanalay",c:"Pune",cu:["Maharashtrian","Vegetarian","Family"],r:4.3,b:1,a:"Sadashiv Peth",v:1,z:"janseva-bhojanalay-sadashiv-peth-pune"},
{n:"Sukanta",c:"Pune",cu:["Vegetarian","Maharashtrian","Family"],r:4.2,b:2,a:"Shivaji Nagar",v:1,z:"sukanta-shivaji-nagar-pune"},
{n:"Goodluck Cafe",c:"Pune",cu:["Iranian","Cafe","Bakery"],r:4.3,b:1,a:"Deccan Gymkhana",v:1,z:"goodluck-cafe-deccan-gymkhana-pune"},
{n:"Wadeshwar",c:"Pune",cu:["South Indian","Maharashtrian","Vegetarian"],r:4.3,b:1,a:"FC Road",v:1,z:"wadeshwar-fc-road-pune"},
{n:"Kayani Bakery",c:"Pune",cu:["Bakery","Cafe","Desserts"],r:4.5,b:1,a:"East Street, Camp",v:1,z:"kayani-bakery-east-street-camp-pune"},
{n:"Cafe 1730",c:"Pune",cu:["Cafe","Continental","Brunch"],r:4.4,b:2,a:"Koregaon Park",v:1,z:"cafe-1730-koregaon-park-pune"},
{n:"The Place Touche the Sizzler",c:"Pune",cu:["Continental","Family"],r:4.4,b:2,a:"Moledina Road, Camp",v:1,z:"the-place-touche-the-sizzler-camp-pune"},
{n:"Pasha",c:"Pune",cu:["Continental","Asian","Fine Dining"],r:4.3,b:3,a:"JW Marriott, Senapati Bapat Road",v:1,z:"pasha-jw-marriott-pune"},
{n:"Spice Kitchen",c:"Pune",cu:["North Indian","Asian","Fine Dining"],r:4.4,b:3,a:"JW Marriott, Senapati Bapat Road",v:1,z:"spice-kitchen-jw-marriott-pune"},
{n:"Effingut Brewerkz",c:"Pune",cu:["Brewery","Continental","Bar"],r:4.4,b:3,a:"Koregaon Park",v:1,z:"effingut-brewerkz-koregaon-park-pune"},
{n:"Independence Brewing Company",c:"Pune",cu:["Brewery","Continental","Pub"],r:4.4,b:3,a:"Koregaon Park",v:1,z:"independence-brewing-company-koregaon-park-pune"},
{n:"Toit Pune",c:"Pune",cu:["Brewery","Continental","Bar"],r:4.4,b:3,a:"Viman Nagar",v:1,z:"toit-viman-nagar-pune"},
{n:"Euriska",c:"Pune",cu:["Continental","Italian","Fine Dining"],r:4.4,b:3,a:"Baner",v:1,z:"euriska-baner-pune"},
{n:"Savya Rasa",c:"Pune",cu:["South Indian","Chettinad","Kerala"],r:4.5,b:2,a:"Koregaon Park",v:1,z:"savya-rasa-koregaon-park-pune"},

// Kolkata (24 more)
{n:"Bhojohori Manna",c:"Kolkata",cu:["Bengali","Family","Casual"],r:4.3,b:2,a:"Ekdalia Road, Ballygunge",v:1,z:"bhojohori-manna-ballygunge-kolkata"},
{n:"Aminia",c:"Kolkata",cu:["Biryani","Mughlai","Kebabs"],r:4.2,b:2,a:"New Market, Esplanade",v:1,z:"aminia-new-market-area-kolkata"},
{n:"Royal Indian Hotel",c:"Kolkata",cu:["Mughlai","Biryani","Kebabs"],r:4.4,b:2,a:"Chitpur, Rabindra Sarani",v:1,z:"royal-indian-hotel-chitpur-kolkata"},
{n:"Shiraz Golden Restaurant",c:"Kolkata",cu:["Biryani","Mughlai","Kebabs"],r:4.2,b:2,a:"Park Circus",v:1,z:"shiraz-golden-restaurant-park-circus-area-kolkata"},
{n:"Mocambo",c:"Kolkata",cu:["Continental","Chinese"],r:4.4,b:3,a:"Park Street",v:1,z:"mocambo-park-street-area-kolkata"},
{n:"Trincas",c:"Kolkata",cu:["Continental","Chinese","Bar"],r:4.3,b:2,a:"Park Street",v:1,z:"trincas-park-street-area-kolkata"},
{n:"Balaram Mullick and Radharaman Mullick",c:"Kolkata",cu:["Sweets","Desserts","Bengali"],r:4.5,b:2,a:"Bhowanipore",v:1,z:"balaram-mullick-radharaman-mullick-bhowanipore-kolkata"},
{n:"K C Das",c:"Kolkata",cu:["Sweets","Desserts","Bengali"],r:4.3,b:1,a:"Esplanade",v:1,z:"kc-das-esplanade-kolkata"},
{n:"Tung Nam",c:"Kolkata",cu:["Chinese","Asian"],r:4.3,b:1,a:"Tiretti Bazaar",v:1,z:"tung-nam-tiretta-bazar-kolkata"},
{n:"Eau Chew",c:"Kolkata",cu:["Chinese","Asian","Family"],r:4.4,b:2,a:"Ganesh Chandra Avenue",v:1,z:"eau-chew-esplanade-kolkata"},
{n:"Kim Ling",c:"Kolkata",cu:["Chinese","Asian"],r:4.2,b:2,a:"Tangra",v:1,z:"kim-ling-tangra-kolkata"},
{n:"Beijing Restaurant",c:"Kolkata",cu:["Chinese","Asian","Family"],r:4.3,b:2,a:"Tangra",v:1,z:"beijing-tangra-kolkata"},
{n:"Bar-B-Q",c:"Kolkata",cu:["Chinese","Continental","Bar"],r:4.3,b:3,a:"Park Street",v:1,z:"bar-b-q-park-street-area-kolkata"},
{n:"Kasturi Restaurant",c:"Kolkata",cu:["Bengali","Family"],r:4.3,b:2,a:"Mirza Ghalib Street",v:1,z:"kasturi-restaurant-new-market-area-kolkata"},
{n:"Kookie Jar",c:"Kolkata",cu:["Bakery","Desserts","Cafe"],r:4.5,b:2,a:"Rawdon Street",v:1,z:"kookie-jar-elgin-kolkata"},
{n:"Nahoum and Sons",c:"Kolkata",cu:["Bakery","Desserts"],r:4.5,b:1,a:"New Market",v:1,z:"nahoum-and-sons-new-market-area-kolkata"},
{n:"The Bhoj Company",c:"Kolkata",cu:["Bengali","Family"],r:4.3,b:2,a:"Salt Lake",v:1,z:"the-bhoj-company-salt-lake-kolkata"},
{n:"Saptapadi",c:"Kolkata",cu:["Bengali","Family"],r:4.2,b:2,a:"Salt Lake Sector V",v:1,z:"saptapadi-salt-lake-kolkata"},
{n:"Marco Polo Kolkata",c:"Kolkata",cu:["Continental","Chinese","Bar"],r:4.2,b:2,a:"Sarat Bose Road",v:1,z:"marco-polo-bhowanipore-kolkata"},
{n:"Mainland China Kolkata",c:"Kolkata",cu:["Chinese","Asian","Fine Dining"],r:4.4,b:3,a:"Gurusaday Road",v:1,z:"mainland-china-ballygunge-kolkata"},
{n:"Oudh 1590",c:"Kolkata",cu:["Mughlai","Biryani","Kebabs"],r:4.5,b:3,a:"Deshapriya Park",v:1,z:"oudh-1590-deshapriya-park-kolkata"},
{n:"Sienna Cafe",c:"Kolkata",cu:["Cafe","Continental","Bakery"],r:4.5,b:2,a:"Hindustan Park",v:1,z:"sienna-cafe-hindustan-park-kolkata"},
{n:"Paris Cafe Kolkata",c:"Kolkata",cu:["Cafe","Continental","Italian"],r:4.4,b:2,a:"Park Street",v:1,z:"paris-cafe-park-street-area-kolkata"},
{n:"Zaranj",c:"Kolkata",cu:["North Indian","Mughlai","Fine Dining"],r:4.3,b:3,a:"AJC Bose Road",v:1,z:"zaranj-park-street-area-kolkata"},

// Ahmedabad (24 more)
{n:"Gordhan Thal",c:"Ahmedabad",cu:["Gujarati","Vegetarian","Family"],r:4.4,b:2,a:"Ambawadi",v:1,z:"gordhan-thal-ambawadi-ahmedabad"},
{n:"Rajwadu",c:"Ahmedabad",cu:["Gujarati","Vegetarian","Family"],r:4.3,b:2,a:"Vasna",v:1,z:"rajwadu-vasna-ahmedabad"},
{n:"Toran Dining Hall",c:"Ahmedabad",cu:["Gujarati","Vegetarian","Family"],r:4.2,b:2,a:"Ashram Road",v:1,z:"toran-dining-hall-ashram-road-ahmedabad"},
{n:"Atithi Dining Hall",c:"Ahmedabad",cu:["Gujarati","Vegetarian","Family"],r:4.3,b:2,a:"Khanpur",v:1,z:"atithi-dining-hall-khanpur-ahmedabad"},
{n:"Patang Revolving Restaurant",c:"Ahmedabad",cu:["Gujarati","North Indian","Fine Dining"],r:4.1,b:3,a:"Lal Darwaja",v:1,z:"patang-the-revolving-restaurant-lal-darwaja-ahmedabad"},
{n:"Manek Chowk",c:"Ahmedabad",cu:["Street Food","Vegetarian"],r:4.4,b:1,a:"Manek Chowk, Old City",v:1,z:"manek-chowk-khadia-ahmedabad"},
{n:"Das Khaman House",c:"Ahmedabad",cu:["Street Food","Gujarati","Vegetarian"],r:4.5,b:1,a:"Raipur",v:1,z:"das-khaman-house-raipur-ahmedabad"},
{n:"Asharfi Kulfi",c:"Ahmedabad",cu:["Desserts","Sweets"],r:4.5,b:1,a:"Manek Chowk",v:1,z:"asharfi-kulfi-manek-chowk-ahmedabad"},
{n:"Jassi De Parathe",c:"Ahmedabad",cu:["North Indian","Street Food"],r:4.3,b:1,a:"Drive-In Road",v:1,z:"jassi-de-parathe-drive-in-road-ahmedabad"},
{n:"Cafe Upper Crust",c:"Ahmedabad",cu:["Cafe","Continental","Italian"],r:4.4,b:2,a:"CG Road",v:1,z:"upper-crust-cafe-cg-road-ahmedabad"},
{n:"Mocha Ahmedabad",c:"Ahmedabad",cu:["Cafe","Continental"],r:4.2,b:2,a:"Navrangpura",v:1,z:"mocha-navrangpura-ahmedabad"},
{n:"Tomato's",c:"Ahmedabad",cu:["Italian","Continental","Family"],r:4.3,b:2,a:"Satellite",v:1,z:"tomatos-satellite-ahmedabad"},
{n:"Sankalp Ahmedabad",c:"Ahmedabad",cu:["South Indian","Vegetarian","Family"],r:4.2,b:2,a:"CG Road",v:1,z:"sankalp-cg-road-ahmedabad"},
{n:"Havmor",c:"Ahmedabad",cu:["Desserts","Cafe","Family"],r:4.3,b:1,a:"Law Garden",v:1,z:"havmor-restaurant-law-garden-ahmedabad"},
{n:"Mirch Masala",c:"Ahmedabad",cu:["North Indian","Street Food"],r:4.2,b:2,a:"SG Highway",v:1,z:"mirch-masala-sg-road-ahmedabad"},
{n:"The Project Cafe",c:"Ahmedabad",cu:["Continental","Cafe","Italian"],r:4.3,b:2,a:"Bodakdev",v:1,z:"the-project-cafe-bodakdev-ahmedabad"},
{n:"Seven Seas",c:"Ahmedabad",cu:["Continental","Chinese","Italian"],r:4.2,b:2,a:"Vastrapur",v:1,z:"seven-seas-vastrapur-ahmedabad"},
{n:"Punjab Honey",c:"Ahmedabad",cu:["North Indian","Family"],r:4.2,b:2,a:"Naranpura",v:1,z:"punjab-honey-naranpura-ahmedabad"},
{n:"Gwalia Sweets",c:"Ahmedabad",cu:["Sweets","Desserts","Street Food"],r:4.4,b:1,a:"CG Road",v:1,z:"gwalia-sweets-cg-road-ahmedabad"},
{n:"Honest Restaurant",c:"Ahmedabad",cu:["Street Food","Vegetarian","Family"],r:4.3,b:1,a:"Income Tax Circle",v:1,z:"honest-restaurant-ashram-road-ahmedabad"},
{n:"Cafe Piano",c:"Ahmedabad",cu:["Cafe","Continental","Italian"],r:4.3,b:2,a:"CG Road",v:1,z:"cafe-piano-cg-road-ahmedabad"},
{n:"Zen Ahmedabad",c:"Ahmedabad",cu:["Asian","Chinese","Thai"],r:4.3,b:3,a:"Bodakdev",v:1,z:"zen-bodakdev-ahmedabad"},
{n:"Krishna Dining Hall",c:"Ahmedabad",cu:["Gujarati","Vegetarian","Family"],r:4.2,b:2,a:"Sabarmati",v:1,z:"krishna-dining-hall-sabarmati-ahmedabad"},
{n:"Pakwan Dining Hall",c:"Ahmedabad",cu:["Gujarati","Vegetarian","Family"],r:4.3,b:2,a:"SG Highway",v:1,z:"pakwan-dining-hall-sg-road-ahmedabad"},

// Coimbatore (24 more)
{n:"Hotel Shree Anandhaas",c:"Coimbatore",cu:["South Indian","Vegetarian","Family"],r:4.3,b:1,a:"RS Puram",v:1,z:"hotel-shree-anandhaas-rs-puram-coimbatore"},
{n:"Geo Marina Buhari",c:"Coimbatore",cu:["South Indian","Biryani","Family"],r:4.2,b:2,a:"Race Course",v:1,z:"geo-marina-buhari-race-course-coimbatore"},
{n:"Hyderabad Briyani House",c:"Coimbatore",cu:["Biryani","Mughlai"],r:4.2,b:2,a:"Peelamedu",v:1,z:"hyderabad-briyani-house-peelamedu-coimbatore"},
{n:"Kovai Ulagam",c:"Coimbatore",cu:["South Indian","Chettinad","Family"],r:4.3,b:2,a:"Avinashi Road",v:1,z:"kovai-ulagam-avinashi-road-coimbatore"},
{n:"Ulundu Vadai",c:"Coimbatore",cu:["South Indian","Street Food"],r:4.2,b:1,a:"Saibaba Colony",v:1,z:"ulundu-vadai-saibaba-colony-coimbatore"},
{n:"Cafe Diem",c:"Coimbatore",cu:["Cafe","Continental","Italian"],r:4.3,b:2,a:"Race Course",v:1,z:"cafe-diem-race-course-coimbatore"},
{n:"Brewista",c:"Coimbatore",cu:["Cafe","Continental","Bakery"],r:4.4,b:2,a:"RS Puram",v:1,z:"brewista-rs-puram-coimbatore"},
{n:"Thalappakatti Coimbatore",c:"Coimbatore",cu:["Biryani","Chettinad","Family"],r:4.2,b:2,a:"Avinashi Road",v:1,z:"thalappakatti-restaurant-avinashi-road-coimbatore"},
{n:"Kebab Studio",c:"Coimbatore",cu:["Kebabs","North Indian","BBQ"],r:4.3,b:2,a:"Race Course",v:1,z:"kebab-studio-race-course-coimbatore"},
{n:"Hotel Aryaas",c:"Coimbatore",cu:["South Indian","Vegetarian","Family"],r:4.2,b:1,a:"Gandhipuram",v:1,z:"hotel-aryaas-gandhipuram-coimbatore"},
{n:"Madras Coffee House Cbe",c:"Coimbatore",cu:["South Indian","Cafe","Vegetarian"],r:4.3,b:1,a:"RS Puram",v:1,z:"madras-coffee-house-rs-puram-coimbatore"},
{n:"Vinayaga Bhavan",c:"Coimbatore",cu:["South Indian","Vegetarian","Family"],r:4.2,b:1,a:"Gandhipuram",v:1,z:"vinayaga-bhavan-gandhipuram-coimbatore"},
{n:"Royal Hindu",c:"Coimbatore",cu:["South Indian","Vegetarian","Family"],r:4.2,b:1,a:"Town Hall",v:1,z:"royal-hindu-town-hall-coimbatore"},
{n:"Sree Shakthi",c:"Coimbatore",cu:["South Indian","Vegetarian","Family"],r:4.2,b:1,a:"RS Puram",v:1,z:"sree-shakthi-rs-puram-coimbatore"},
{n:"Hotel Krishna Bhavan",c:"Coimbatore",cu:["South Indian","Vegetarian","Family"],r:4.1,b:1,a:"Saibaba Colony",v:1,z:"hotel-krishna-bhavan-saibaba-colony-coimbatore"},
{n:"Zara Hatke",c:"Coimbatore",cu:["Continental","Italian","Cafe"],r:4.3,b:2,a:"Race Course",v:1,z:"zara-hatke-race-course-coimbatore"},
{n:"The Residency Coffee Shop",c:"Coimbatore",cu:["Continental","Cafe","Family"],r:4.2,b:2,a:"Avinashi Road",v:1,z:"the-residency-avinashi-road-coimbatore"},
{n:"Latest Recipe Le Meridien",c:"Coimbatore",cu:["Continental","Asian","Fine Dining"],r:4.4,b:3,a:"Le Meridien, Race Course",v:1,z:"latest-recipe-le-meridien-race-course-coimbatore"},
{n:"Bamboo Hut",c:"Coimbatore",cu:["Chinese","Asian"],r:4.2,b:2,a:"Peelamedu",v:1,z:"bamboo-hut-peelamedu-coimbatore"},
{n:"Mainland China Coimbatore",c:"Coimbatore",cu:["Chinese","Asian","Fine Dining"],r:4.3,b:3,a:"Avinashi Road",v:1,z:"mainland-china-avinashi-road-coimbatore"},
{n:"Hot Breads",c:"Coimbatore",cu:["Bakery","Cafe","Desserts"],r:4.2,b:1,a:"RS Puram",v:1,z:"hot-breads-rs-puram-coimbatore"},
{n:"Kapikala Coffee House",c:"Coimbatore",cu:["Cafe","Bakery","Continental"],r:4.4,b:2,a:"Saibaba Colony",v:1,z:"kapikala-coffee-house-saibaba-colony-coimbatore"},
{n:"Absolute Barbecues Coimbatore",c:"Coimbatore",cu:["BBQ","North Indian","Family"],r:4.4,b:3,a:"Brookefields Mall",v:1,z:"abs-absolute-barbecues-race-course-coimbatore"},
{n:"On The Rocks",c:"Coimbatore",cu:["North Indian","Continental","Bar"],r:4.2,b:2,a:"Race Course",v:1,z:"on-the-rocks-race-course-coimbatore"},

// Indore (24 more)
{n:"Joshi Dahi Bada House",c:"Indore",cu:["Street Food","Chaat"],r:4.4,b:1,a:"Chappan Dukan, New Palasia",v:1,z:"joshi-dahi-bada-house-new-palasia-indore"},
{n:"Vijay Chaat House",c:"Indore",cu:["Chaat","Street Food"],r:4.3,b:1,a:"Chappan Dukan, New Palasia",v:1,z:"vijay-chaat-house-new-palasia-indore"},
{n:"Young Tarang",c:"Indore",cu:["Chinese","Quick Bites"],r:4.2,b:1,a:"Chappan Dukan, New Palasia",v:1,z:"young-tarang-new-palasia-indore"},
{n:"Madhuram Sweets",c:"Indore",cu:["Sweets","Desserts"],r:4.3,b:1,a:"Chappan Dukan, New Palasia",v:1,z:"madhuram-sweets-new-palasia-indore"},
{n:"Johnny Hot Dog",c:"Indore",cu:["Street Food","Burgers"],r:4.4,b:1,a:"Sarafa Bazaar",v:1,z:"johnny-hot-dog-sarafa-bazaar-indore"},
{n:"Guru Ki Dal Bafle",c:"Indore",cu:["North Indian","Street Food"],r:4.2,b:1,a:"Sapna Sangeeta Road",v:1,z:"guru-ki-dal-bafle-sapna-sangeeta-indore"},
{n:"Sanchora Castle",c:"Indore",cu:["North Indian","Mughlai"],r:4.3,b:2,a:"AB Road, Vijay Nagar",v:1,z:"sanchora-castle-vijay-nagar-indore"},
{n:"The Olive House",c:"Indore",cu:["Italian","Continental"],r:4.4,b:2,a:"Vijay Nagar",v:1,z:"the-olive-house-vijay-nagar-indore"},
{n:"1st Avenue Cafe",c:"Indore",cu:["Cafe","Continental"],r:4.3,b:2,a:"Vijay Nagar",v:1,z:"1st-avenue-cafe-vijay-nagar-indore"},
{n:"Cafe Coffee Affair",c:"Indore",cu:["Cafe","Italian"],r:4.2,b:2,a:"Vijay Nagar",v:1,z:"cafe-coffee-affair-vijay-nagar-indore"},
{n:"Shree Sagar Garden",c:"Indore",cu:["South Indian","North Indian"],r:4.1,b:1,a:"Palasia",v:1,z:"shree-sagar-garden-palasia-indore"},
{n:"Status Restaurant",c:"Indore",cu:["North Indian","Chinese"],r:4.2,b:2,a:"Sapna Sangeeta",v:1,z:"status-restaurant-sapna-sangeeta-indore"},
{n:"Hotel Kalyan",c:"Indore",cu:["North Indian","Mughlai"],r:4.1,b:1,a:"MG Road",v:1,z:"hotel-kalyan-mg-road-indore"},
{n:"Bombay Pav Bhaji",c:"Indore",cu:["Street Food","Quick Bites"],r:4.3,b:1,a:"Sarafa Bazaar",v:1,z:"bombay-pav-bhaji-sarafa-bazaar-indore"},
{n:"Agarwal Bhojnalaya",c:"Indore",cu:["North Indian","Vegetarian"],r:4.2,b:1,a:"Rajwada",v:1,z:"agarwal-bhojnalaya-rajwada-indore"},
{n:"Cafe Terazza",c:"Indore",cu:["Continental","Italian"],r:4.3,b:2,a:"AB Road",v:1,z:"cafe-terazza-ab-road-indore"},
{n:"Pind Balluchi Indore",c:"Indore",cu:["North Indian","Punjabi"],r:4.1,b:2,a:"Vijay Nagar",v:1,z:"pind-balluchi-vijay-nagar-indore"},
{n:"Imperial Restaurant",c:"Indore",cu:["Mughlai","North Indian"],r:4.2,b:2,a:"MG Road",v:1,z:"imperial-restaurant-mg-road-indore"},
{n:"Shreemaya Celebration",c:"Indore",cu:["North Indian","Family"],r:4.3,b:3,a:"RNT Marg",v:1,z:"shreemaya-celebration-rnt-marg-indore"},
{n:"Mayur Hotel Veg",c:"Indore",cu:["North Indian","South Indian"],r:4.0,b:1,a:"RNT Marg",v:1,z:"mayur-hotel-veg-restaurant-indore"},
{n:"Hawkers Restaurant",c:"Indore",cu:["Asian","Chinese"],r:4.2,b:2,a:"AB Road, Vijay Nagar",v:1,z:"hawkers-restaurant-vijay-nagar-indore"},
{n:"Saravana Bhavan Indore",c:"Indore",cu:["South Indian","Vegetarian"],r:4.3,b:2,a:"Vijay Nagar",v:1,z:"saravana-bhavan-vijay-nagar-indore"},
{n:"56 Dukan",c:"Indore",cu:["Street Food","Chaat"],r:4.4,b:1,a:"New Palasia",v:1,z:"56-dukan-new-palasia-indore"},
{n:"Chappan Bhog",c:"Indore",cu:["Sweets","Desserts","Street Food"],r:4.3,b:1,a:"Sarafa Bazaar",v:1,z:"chappan-bhog-sarafa-bazaar-indore"},

// Jaipur (24 more)
{n:"Niros",c:"Jaipur",cu:["North Indian","Continental"],r:4.3,b:2,a:"MI Road",v:1,z:"niros-mi-road-jaipur"},
{n:"Spice Court",c:"Jaipur",cu:["Rajasthani","North Indian"],r:4.4,b:2,a:"Civil Lines",v:1,z:"spice-court-civil-lines-jaipur"},
{n:"Peacock Rooftop Restaurant",c:"Jaipur",cu:["North Indian","Family"],r:4.5,b:2,a:"Hotel Pearl Palace",v:1,z:"peacock-rooftop-restaurant-jaipur"},
{n:"Anokhi Cafe",c:"Jaipur",cu:["Cafe","Continental"],r:4.4,b:2,a:"C-Scheme",v:1,z:"anokhi-cafe-c-scheme-jaipur"},
{n:"Handi Restaurant",c:"Jaipur",cu:["North Indian","Mughlai"],r:4.3,b:2,a:"MI Road",v:1,z:"handi-restaurant-mi-road-jaipur"},
{n:"Four Seasons Jaipur",c:"Jaipur",cu:["North Indian","Chinese"],r:4.2,b:2,a:"Subhash Marg, C-Scheme",v:1,z:"four-seasons-c-scheme-jaipur"},
{n:"Sankalp Jaipur",c:"Jaipur",cu:["South Indian","Vegetarian"],r:4.2,b:2,a:"MI Road",v:1,z:"sankalp-mi-road-jaipur"},
{n:"Mohan Mahal Rambagh",c:"Jaipur",cu:["Modern Indian","Continental","Fine Dining"],r:4.6,b:3,a:"Rambagh Palace, Bhawani Singh Road",v:1,z:"mohan-mahal-rambagh-palace-jaipur"},
{n:"Bar Palladio",c:"Jaipur",cu:["Italian","Mediterranean"],r:4.5,b:3,a:"Narain Niwas Palace, Kanota Bagh",v:1,z:"bar-palladio-narain-niwas-jaipur"},
{n:"Steam at Rambagh",c:"Jaipur",cu:["Italian","Pizza","Continental"],r:4.4,b:3,a:"Rambagh Palace",v:1,z:"steam-rambagh-jaipur"},
{n:"Cafe Palladio",c:"Jaipur",cu:["Cafe","Mediterranean"],r:4.5,b:3,a:"Hathroi Fort, Ajmer Road",v:1,z:"cafe-palladio-ajmer-road-jaipur"},
{n:"Tattoo Cafe and Lounge",c:"Jaipur",cu:["Cafe","Continental"],r:4.3,b:2,a:"Hawa Mahal Road",v:1,z:"tattoo-cafe-lounge-hawa-mahal-jaipur"},
{n:"Wind View Cafe",c:"Jaipur",cu:["Cafe","North Indian"],r:4.2,b:1,a:"Hawa Mahal Road",v:1,z:"wind-view-cafe-hawa-mahal-jaipur"},
{n:"Padao Restaurant",c:"Jaipur",cu:["Rajasthani","North Indian"],r:4.3,b:2,a:"Nahargarh Fort",v:1,z:"padao-nahargarh-fort-jaipur"},
{n:"On The House",c:"Jaipur",cu:["Continental","Italian"],r:4.3,b:2,a:"Vaishali Nagar",v:1,z:"on-the-house-vaishali-nagar-jaipur"},
{n:"The Forresta Kitchen and Bar",c:"Jaipur",cu:["Continental","Asian","Bar"],r:4.4,b:3,a:"Jaisinghpura, Amer",v:1,z:"forresta-kitchen-bar-amer-jaipur"},
{n:"Masala Chowk",c:"Jaipur",cu:["Street Food","Rajasthani"],r:4.2,b:1,a:"Ram Niwas Garden",v:1,z:"masala-chowk-ram-niwas-jaipur"},
{n:"Sahu Chai Wala",c:"Jaipur",cu:["Cafe","Quick Bites"],r:4.3,b:1,a:"MI Road",v:1,z:"sahu-chai-wala-mi-road-jaipur"},
{n:"Pandit Kulfi",c:"Jaipur",cu:["Desserts","Sweets"],r:4.4,b:1,a:"MI Road",v:1,z:"pandit-kulfi-mi-road-jaipur"},
{n:"Rawat Kachori",c:"Jaipur",cu:["Street Food","Sweets"],r:4.4,b:1,a:"Sindhi Camp",v:1,z:"rawat-kachori-sindhi-camp-jaipur"},
{n:"Samrat Restaurant Jaipur",c:"Jaipur",cu:["Rajasthani","Family"],r:4.2,b:2,a:"MI Road",v:1,z:"samrat-mi-road-jaipur"},
{n:"Natraj Restaurant",c:"Jaipur",cu:["North Indian","South Indian"],r:4.2,b:2,a:"MI Road",v:1,z:"natraj-mi-road-jaipur"},
{n:"Jaipur Modern Kitchen",c:"Jaipur",cu:["Continental","Modern Indian"],r:4.4,b:3,a:"C-Scheme",v:1,z:"jaipur-modern-kitchen-c-scheme-jaipur"},
{n:"Curious Life Coffee Roasters",c:"Jaipur",cu:["Cafe","Bakery"],r:4.5,b:2,a:"C-Scheme",v:1,z:"curious-life-coffee-roasters-jaipur"},

// Kochi (24 more)
{n:"Fusion Bay",c:"Kochi",cu:["Seafood","Kerala"],r:4.4,b:2,a:"Elamkulam",v:1,z:"fusion-bay-elamkulam-kochi"},
{n:"Oceanos Restaurant",c:"Kochi",cu:["Seafood","Continental"],r:4.3,b:2,a:"Panampilly Nagar",v:1,z:"oceanos-panampilly-nagar-kochi"},
{n:"Loafer's Corner Cafe",c:"Kochi",cu:["Cafe","Continental"],r:4.3,b:2,a:"Princess Street, Fort Kochi",v:1,z:"loafers-corner-fort-kochi"},
{n:"Brunton Boatyard",c:"Kochi",cu:["Continental","Kerala","Fine Dining"],r:4.5,b:3,a:"Calvathy, Fort Kochi",v:1,z:"brunton-boatyard-fort-kochi"},
{n:"Grand Pavilion",c:"Kochi",cu:["North Indian","South Indian","Family"],r:4.4,b:3,a:"Grand Hotel, MG Road",v:1,z:"grand-pavilion-mg-road-kochi"},
{n:"Mocha Art Cafe",c:"Kochi",cu:["Cafe","Continental"],r:4.2,b:2,a:"Marine Drive",v:1,z:"mocha-art-cafe-marine-drive-kochi"},
{n:"Rice Boat",c:"Kochi",cu:["Seafood","Kerala","Fine Dining"],r:4.5,b:3,a:"Taj Malabar, Willingdon Island",v:1,z:"rice-boat-taj-malabar-kochi"},
{n:"Thaff Restaurant",c:"Kochi",cu:["Lebanese","Mughlai","Biryani"],r:4.3,b:2,a:"Kaloor",v:1,z:"thaff-restaurant-kaloor-kochi"},
{n:"Kayees Rahmathulla Hotel",c:"Kochi",cu:["Biryani","Mughlai"],r:4.4,b:1,a:"Mattancherry",v:1,z:"kayees-rahmathulla-mattancherry-kochi"},
{n:"Pai Brothers",c:"Kochi",cu:["South Indian","Vegetarian"],r:4.3,b:1,a:"MG Road",v:1,z:"pai-brothers-mg-road-kochi"},
{n:"Caza Maria",c:"Kochi",cu:["Mediterranean","Continental"],r:4.4,b:3,a:"Jew Town, Mattancherry",v:1,z:"caza-maria-jew-town-kochi"},
{n:"Teapot Cafe",c:"Kochi",cu:["Cafe","Continental"],r:4.3,b:2,a:"Peter Celli Street, Fort Kochi",v:1,z:"teapot-cafe-fort-kochi"},
{n:"Seagull Restaurant",c:"Kochi",cu:["Seafood","Continental"],r:4.2,b:2,a:"Calvathy Road, Fort Kochi",v:1,z:"seagull-restaurant-fort-kochi"},
{n:"Malabar Junction",c:"Kochi",cu:["Continental","Kerala","Fine Dining"],r:4.5,b:3,a:"Malabar House, Fort Kochi",v:1,z:"malabar-junction-fort-kochi"},
{n:"Dal Roti",c:"Kochi",cu:["North Indian","Mughlai"],r:4.4,b:2,a:"Lily Street, Fort Kochi",v:1,z:"dal-roti-fort-kochi"},
{n:"Solar Cafe",c:"Kochi",cu:["Cafe","Vegan"],r:4.3,b:2,a:"Fort Kochi",v:1,z:"solar-cafe-fort-kochi"},
{n:"History Restaurant",c:"Kochi",cu:["Kerala","Continental"],r:4.4,b:3,a:"Brunton Boatyard, Fort Kochi",v:1,z:"history-restaurant-fort-kochi"},
{n:"Kashi Art Gallery Cafe",c:"Kochi",cu:["Cafe","Continental"],r:4.3,b:2,a:"Mattancherry",v:1,z:"kashi-gallery-cafe-mattancherry-kochi"},
{n:"Avocado Restaurant",c:"Kochi",cu:["Continental","Family"],r:4.2,b:2,a:"Panampilly Nagar",v:1,z:"avocado-restaurant-panampilly-nagar-kochi"},
{n:"Chillies Restaurant",c:"Kochi",cu:["Chinese","Asian"],r:4.3,b:2,a:"Panampilly Nagar",v:1,z:"chillies-panampilly-nagar-kochi"},
{n:"Le Colonial Kochi",c:"Kochi",cu:["Continental","Asian"],r:4.4,b:3,a:"Forte Kochi, Fort Kochi",v:1,z:"le-colonial-fort-kochi"},
{n:"Saffron Crowne Plaza",c:"Kochi",cu:["North Indian","Mughlai"],r:4.3,b:2,a:"Crowne Plaza, Kundannoor",v:1,z:"saffron-crowne-plaza-kochi"},
{n:"Ginger House",c:"Kochi",cu:["Kerala","Seafood"],r:4.3,b:2,a:"Heritage Arts, Jew Town",v:1,z:"ginger-house-jew-town-kochi"},
{n:"Arca Nova",c:"Kochi",cu:["Seafood","Continental"],r:4.3,b:3,a:"Old Harbour Hotel, Fort Kochi",v:1,z:"arca-nova-fort-kochi"},

// Lucknow (24 more)
{n:"Wahid Biryani",c:"Lucknow",cu:["Mughlai","Biryani"],r:4.3,b:2,a:"Aminabad",v:1,z:"wahid-biryani-aminabad-lucknow"},
{n:"Mubeen's",c:"Lucknow",cu:["Mughlai","Kebabs"],r:4.2,b:2,a:"Aminabad",v:1,z:"mubeens-aminabad-lucknow"},
{n:"Rahim's Kulcha Nihari",c:"Lucknow",cu:["Mughlai","Kebabs"],r:4.4,b:1,a:"Chowk",v:1,z:"rahims-chowk-lucknow"},
{n:"Prakash Kulfi",c:"Lucknow",cu:["Desserts","Sweets"],r:4.5,b:1,a:"Aminabad",v:1,z:"prakash-ki-mashhoor-kulfi-aminabad-lucknow"},
{n:"Ram Asrey",c:"Lucknow",cu:["Sweets","Desserts"],r:4.5,b:1,a:"Hazratganj",v:1,z:"ram-asrey-hazratganj-lucknow"},
{n:"Sakhawat",c:"Lucknow",cu:["Mughlai","Kebabs"],r:4.2,b:2,a:"Husainganj",v:1,z:"sakhawat-husainganj-lucknow"},
{n:"Naushijaan",c:"Lucknow",cu:["Mughlai","Biryani"],r:4.3,b:2,a:"Hazratganj",v:1,z:"naushijaan-hazratganj-lucknow"},
{n:"Lalla Biryani",c:"Lucknow",cu:["Biryani","Mughlai"],r:4.1,b:1,a:"Akbari Gate, Chowk",v:1,z:"lalla-biryani-chowk-lucknow"},
{n:"Bhola Ki Lassi",c:"Lucknow",cu:["Street Food"],r:4.4,b:1,a:"Chowk",v:1,z:"bhola-ki-lassi-chowk-lucknow"},
{n:"Indian Coffee House Lucknow",c:"Lucknow",cu:["South Indian","Cafe"],r:4.1,b:1,a:"Hazratganj",v:1,z:"indian-coffee-house-hazratganj-lucknow"},
{n:"Tundey Kababi",c:"Lucknow",cu:["Mughlai","Kebabs"],r:4.3,b:2,a:"Aminabad",v:1,z:"tundey-kababi-aminabad-lucknow"},
{n:"Falaknuma Lucknow",c:"Lucknow",cu:["North Indian","Mughlai","Fine Dining"],r:4.3,b:3,a:"Clarks Avadh, Hazratganj",v:1,z:"falaknuma-clarks-avadh-hazratganj-lucknow"},
{n:"The Mughals Dastarkhwan",c:"Lucknow",cu:["Mughlai","Kebabs"],r:4.2,b:2,a:"Gomti Nagar",v:1,z:"the-mughals-dastarkhwan-gomti-nagar-lucknow"},
{n:"Azrak",c:"Lucknow",cu:["Mughlai","Fine Dining"],r:4.4,b:3,a:"Lebua, Hazratganj",v:1,z:"azrak-lebua-hazratganj-lucknow"},
{n:"Barbeque Nation Lucknow",c:"Lucknow",cu:["BBQ","North Indian"],r:4.3,b:3,a:"Gomti Nagar",v:1,z:"barbeque-nation-gomti-nagar-lucknow"},
{n:"Cafe Repertwahr",c:"Lucknow",cu:["Cafe","Continental"],r:4.4,b:2,a:"Gomti Nagar",v:1,z:"cafe-repertwahr-gomti-nagar-lucknow"},
{n:"Mocha Hazratganj",c:"Lucknow",cu:["Cafe","Italian"],r:4.2,b:2,a:"Hazratganj",v:1,z:"mocha-hazratganj-lucknow"},
{n:"Pind Balluchi Lucknow",c:"Lucknow",cu:["North Indian","Punjabi"],r:4.0,b:2,a:"Gomti Nagar",v:1,z:"pind-balluchi-gomti-nagar-lucknow"},
{n:"Mainland China Lucknow",c:"Lucknow",cu:["Chinese","Asian"],r:4.3,b:3,a:"Hazratganj",v:1,z:"mainland-china-hazratganj-lucknow"},
{n:"Big Bowl",c:"Lucknow",cu:["Chinese","Asian"],r:4.1,b:2,a:"Gomti Nagar",v:1,z:"big-bowl-gomti-nagar-lucknow"},
{n:"Cravvings Patisserie",c:"Lucknow",cu:["Bakery","Desserts"],r:4.5,b:2,a:"Gomti Nagar",v:1,z:"cravvings-patisserie-gomti-nagar-lucknow"},
{n:"Chowk by Vineet Bhatia",c:"Lucknow",cu:["Modern Indian","Fine Dining"],r:4.4,b:3,a:"Renaissance, Vibhuti Khand",v:1,z:"chowk-renaissance-gomti-nagar-lucknow"},
{n:"The Hazratganj Social",c:"Lucknow",cu:["North Indian","Continental","Bar"],r:4.2,b:2,a:"Hazratganj",v:1,z:"hazratganj-social-hazratganj-lucknow"},
{n:"Sharma Ji Ki Chai",c:"Lucknow",cu:["Cafe","Street Food"],r:4.3,b:1,a:"Lalbagh",v:1,z:"sharma-ji-ki-chai-lalbagh-lucknow"},

// Chandigarh (24 more)
{n:"Backpackers Cafe",c:"Chandigarh",cu:["Cafe","Continental"],r:4.4,b:2,a:"Sector 9",v:1,z:"backpackers-cafe-sector-9-chandigarh"},
{n:"Pirates of Grill",c:"Chandigarh",cu:["BBQ","North Indian"],r:4.3,b:3,a:"Elante Mall",v:1,z:"pirates-of-grill-elante-mall-chandigarh"},
{n:"Hops n Grains",c:"Chandigarh",cu:["Brewery","Continental"],r:4.3,b:3,a:"Sector 26",v:1,z:"hops-n-grains-sector-26-chandigarh"},
{n:"Gopal Sweets",c:"Chandigarh",cu:["Sweets","North Indian"],r:4.3,b:1,a:"Sector 35",v:1,z:"gopal-sweets-sector-35-chandigarh"},
{n:"Sindhi Sweets",c:"Chandigarh",cu:["Sweets","Street Food"],r:4.2,b:1,a:"Sector 17",v:1,z:"sindhi-sweets-sector-17-chandigarh"},
{n:"Bhoj Chandigarh",c:"Chandigarh",cu:["North Indian","Family"],r:4.3,b:2,a:"Sector 22",v:1,z:"bhoj-sector-22-chandigarh"},
{n:"Saffron JW Marriott",c:"Chandigarh",cu:["North Indian","Mughlai","Fine Dining"],r:4.4,b:3,a:"JW Marriott, Sector 35",v:1,z:"saffron-jw-marriott-sector-35-chandigarh"},
{n:"Black Lotus Taj",c:"Chandigarh",cu:["Pan-Asian","Chinese","Fine Dining"],r:4.4,b:3,a:"Taj, Sector 17",v:1,z:"black-lotus-taj-sector-17-chandigarh"},
{n:"Garlic and Greens",c:"Chandigarh",cu:["Mediterranean","Italian"],r:4.5,b:3,a:"Sector 26",v:1,z:"garlic-and-greens-sector-26-chandigarh"},
{n:"The Brew Estate",c:"Chandigarh",cu:["Brewery","Continental"],r:4.3,b:3,a:"Sector 26",v:1,z:"the-brew-estate-sector-26-chandigarh"},
{n:"Brewmaster",c:"Chandigarh",cu:["Brewery","North Indian"],r:4.2,b:3,a:"Sector 26",v:1,z:"brewmaster-sector-26-chandigarh"},
{n:"Olive Garden Panchkula",c:"Chandigarh",cu:["North Indian","Continental"],r:4.2,b:2,a:"Sector 5, Panchkula",v:1,z:"olive-garden-sector-5-panchkula"},
{n:"Mehfil Chandigarh",c:"Chandigarh",cu:["North Indian","Mughlai"],r:4.1,b:2,a:"Sector 17",v:1,z:"mehfil-restaurant-sector-17-chandigarh"},
{n:"Khyber Chandigarh",c:"Chandigarh",cu:["North Indian","Mughlai"],r:4.2,b:3,a:"Sector 35",v:1,z:"khyber-sector-35-chandigarh"},
{n:"Barbeque Nation Chandigarh",c:"Chandigarh",cu:["BBQ","North Indian"],r:4.3,b:3,a:"Sector 26",v:1,z:"barbeque-nation-sector-26-chandigarh"},
{n:"Sagar Ratna Chandigarh",c:"Chandigarh",cu:["South Indian","Vegetarian"],r:4.0,b:2,a:"Sector 17",v:1,z:"sagar-ratna-sector-17-chandigarh"},
{n:"Yellow Chilli",c:"Chandigarh",cu:["North Indian","Mughlai"],r:4.2,b:2,a:"Elante Mall",v:1,z:"yellow-chilli-elante-mall-chandigarh"},
{n:"The Willow Cafe",c:"Chandigarh",cu:["Cafe","Continental"],r:4.4,b:2,a:"Sector 9",v:1,z:"the-willow-cafe-sector-9-chandigarh"},
{n:"Cafe JCs",c:"Chandigarh",cu:["Cafe","Italian"],r:4.4,b:2,a:"Sector 7",v:1,z:"cafe-jcs-sector-7-chandigarh"},
{n:"Tehal Singh's Chicken",c:"Chandigarh",cu:["North Indian","Punjabi"],r:4.2,b:2,a:"Sector 23",v:1,z:"tehal-singhs-chicken-sector-23-chandigarh"},
{n:"Katani Dhaba",c:"Chandigarh",cu:["North Indian","Punjabi"],r:4.3,b:1,a:"Sector 28",v:1,z:"katani-dhaba-sector-28-chandigarh"},
{n:"Peddlers",c:"Chandigarh",cu:["Continental","North Indian"],r:4.2,b:2,a:"Sector 35",v:1,z:"peddlers-sector-35-chandigarh"},
{n:"Swagath Chandigarh",c:"Chandigarh",cu:["South Indian","Coastal"],r:4.3,b:3,a:"Sector 26",v:1,z:"swagath-sector-26-chandigarh"},
{n:"Underdoggs Sports Bar",c:"Chandigarh",cu:["Continental","Bar","Pub"],r:4.2,b:3,a:"Elante Mall",v:1,z:"underdoggs-elante-mall-chandigarh"},

// Visakhapatnam (24 more)
{n:"Sri Subbayya Gari Hotel",c:"Visakhapatnam",cu:["Andhra","South Indian"],r:4.3,b:2,a:"Dwaraka Nagar",v:1,z:"sri-subbayya-gari-hotel-dwaraka-nagar-visakhapatnam"},
{n:"Fishermen's Wharf",c:"Visakhapatnam",cu:["Seafood","Coastal"],r:4.4,b:3,a:"Beach Road",v:1,z:"fishermens-wharf-beach-road-visakhapatnam"},
{n:"Eat Street",c:"Visakhapatnam",cu:["Street Food","Family"],r:4.2,b:2,a:"Beach Road",v:1,z:"eat-street-beach-road-visakhapatnam"},
{n:"Sahari Restaurant",c:"Visakhapatnam",cu:["Andhra","Biryani"],r:4.3,b:2,a:"MVP Colony",v:1,z:"sahari-mvp-colony-visakhapatnam"},
{n:"Raju Gari Dhaba",c:"Visakhapatnam",cu:["Andhra","South Indian"],r:4.2,b:2,a:"Madhurawada",v:1,z:"raju-gari-dhaba-madhurawada-visakhapatnam"},
{n:"Tenali Ramakrishna",c:"Visakhapatnam",cu:["Andhra","Biryani"],r:4.1,b:2,a:"Dwaraka Nagar",v:1,z:"tenali-ramakrishna-dwaraka-nagar-visakhapatnam"},
{n:"Kakatiya Restaurant",c:"Visakhapatnam",cu:["Andhra","Hyderabadi"],r:4.2,b:2,a:"Daba Gardens",v:1,z:"kakatiya-restaurant-daba-gardens-visakhapatnam"},
{n:"Paradise Biryani Vizag",c:"Visakhapatnam",cu:["Biryani","Hyderabadi"],r:4.2,b:2,a:"Siripuram",v:1,z:"paradise-biryani-siripuram-visakhapatnam"},
{n:"Bay Leaf Novotel",c:"Visakhapatnam",cu:["North Indian","Continental","Fine Dining"],r:4.4,b:3,a:"Novotel, Beach Road",v:1,z:"bay-leaf-novotel-beach-road-visakhapatnam"},
{n:"The Square Novotel",c:"Visakhapatnam",cu:["North Indian","South Indian","Family"],r:4.4,b:3,a:"Novotel, Beach Road",v:1,z:"the-square-novotel-beach-road-visakhapatnam"},
{n:"Infinity The Park",c:"Visakhapatnam",cu:["North Indian","Continental","Family"],r:4.3,b:3,a:"The Park, Beach Road",v:1,z:"infinity-the-park-beach-road-visakhapatnam"},
{n:"Aqua The Park",c:"Visakhapatnam",cu:["Continental","Mediterranean","Fine Dining"],r:4.3,b:3,a:"The Park, Beach Road",v:1,z:"aqua-the-park-beach-road-visakhapatnam"},
{n:"Spice 6",c:"Visakhapatnam",cu:["North Indian","Asian","Fine Dining"],r:4.3,b:3,a:"Radisson Blu, Rushikonda",v:1,z:"spice-6-radisson-blu-rushikonda-visakhapatnam"},
{n:"Dakshin Chola",c:"Visakhapatnam",cu:["South Indian","Andhra"],r:4.2,b:2,a:"Dwaraka Nagar",v:1,z:"dakshin-chola-dwaraka-nagar-visakhapatnam"},
{n:"Pinnacle Revolving Restaurant",c:"Visakhapatnam",cu:["North Indian","Continental","Fine Dining"],r:4.2,b:3,a:"Daspalla Hotel, Suryabagh",v:1,z:"pinnacle-daspalla-suryabagh-visakhapatnam"},
{n:"Hotel Daspalla",c:"Visakhapatnam",cu:["Andhra","North Indian"],r:4.1,b:2,a:"Suryabagh",v:1,z:"hotel-daspalla-suryabagh-visakhapatnam"},
{n:"Ten Downing Street",c:"Visakhapatnam",cu:["Continental","Bar","Pub"],r:4.2,b:3,a:"Beach Road",v:1,z:"ten-downing-street-beach-road-visakhapatnam"},
{n:"Sea View Restaurant",c:"Visakhapatnam",cu:["Seafood","Family"],r:4.1,b:2,a:"Ramakrishna Beach",v:1,z:"sea-view-rk-beach-visakhapatnam"},
{n:"Flying Spaghetti Monster",c:"Visakhapatnam",cu:["Italian","Cafe"],r:4.4,b:2,a:"Beach Road",v:1,z:"flying-spaghetti-monster-beach-road-visakhapatnam"},
{n:"Cafe Coast 2 Coast",c:"Visakhapatnam",cu:["Cafe","Continental"],r:4.3,b:2,a:"Siripuram",v:1,z:"cafe-coast-2-coast-siripuram-visakhapatnam"},
{n:"Tiki Bar and Kitchen",c:"Visakhapatnam",cu:["Asian","Continental","Bar"],r:4.3,b:3,a:"Beach Road",v:1,z:"tiki-bar-kitchen-beach-road-visakhapatnam"},
{n:"Nautica Welcomhotel",c:"Visakhapatnam",cu:["Continental","Asian","Fine Dining"],r:4.2,b:3,a:"Welcomhotel, Beach Road",v:1,z:"nautica-welcomhotel-beach-road-visakhapatnam"},
{n:"Ulavacharu Vizag",c:"Visakhapatnam",cu:["Andhra","Biryani"],r:4.3,b:2,a:"Siripuram",v:1,z:"ulavacharu-siripuram-visakhapatnam"},
{n:"Ginger Cafe",c:"Visakhapatnam",cu:["Cafe","Continental"],r:4.1,b:2,a:"Asilmetta",v:1,z:"ginger-cafe-asilmetta-visakhapatnam"}
{n:"Wind & Waves",c:"Bhopal",cu:["Multi-Cuisine","Lakeside","Indian"],r:4.5,b:2,a:"Boat Club Road, Shyamla Hills",v:1,z:"wind-and-waves-shyamla-hills-bhopal"},
{n:"Under The Mango Tree",c:"Bhopal",cu:["North Indian","Mughlai","Continental"],r:4.4,b:2,a:"Jehan Numa Palace Hotel, Shamla Hills",v:1,z:"under-the-mango-tree-jehan-numa-bhopal"},
{n:"La Kuchina",c:"Bhopal",cu:["Italian","Pizza","Pasta"],r:4.3,b:2,a:"Plot 30, Press Complex, MP Nagar",v:0,z:"la-kuchina-mp-nagar-bhopal"},
{n:"Bapu Ki Kutia",c:"Bhopal",cu:["North Indian","Vegetarian","Thali"],r:4.4,b:1,a:"DB Mall, Arera Hills",v:0,z:"bapu-ki-kutia-arera-hills-bhopal"},
{n:"Manohar Dairy & Restaurant",c:"Bhopal",cu:["South Indian","Vegetarian","Sweets"],r:4.5,b:1,a:"Hamidia Road, opposite Bharat Talkies",v:0,z:"manohar-dairy-hamidia-bhopal"},
{n:"Filfora",c:"Bhopal",cu:["Lebanese","Mediterranean","Cafe"],r:4.4,b:2,a:"E-3/85, Arera Colony",v:0,z:"filfora-arera-colony-bhopal"},
{n:"Spice Bazaar",c:"Bhopal",cu:["Bhopali","Mughlai","Biryani"],r:4.3,b:2,a:"Hotel Lake View Ashok, Shamla Hills",v:1,z:"spice-bazaar-lake-view-bhopal"},
{n:"New Inn Cafe",c:"Bhopal",cu:["Cafe","Continental","Italian"],r:4.2,b:1,a:"Plot 31, Zone-II, MP Nagar",v:0,z:"new-inn-cafe-mp-nagar-bhopal"},
{n:"Sagar Gaire",c:"Bhopal",cu:["North Indian","Chinese","Fast Food"],r:4.3,b:1,a:"Bittan Market, Arera Colony",v:0,z:"sagar-gaire-bittan-market-bhopal"},
{n:"Indian Coffee House",c:"Bhopal",cu:["South Indian","Cafe","Snacks"],r:4.4,b:1,a:"Ahmedabad Palace, New Market",v:0,z:"indian-coffee-house-new-market-bhopal"},
{n:"Zero Degrees",c:"Nagpur",cu:["Multi-Cuisine","Continental","Indian"],r:4.4,b:2,a:"Centre Point Hotel, Ramdaspeth",v:1,z:"zero-degrees-centre-point-nagpur"},
{n:"Haldiram's Thaba",c:"Nagpur",cu:["North Indian","Sweets","Vegetarian"],r:4.5,b:1,a:"Wardha Road, Pratap Nagar",v:0,z:"haldirams-thaba-pratap-nagar-nagpur"},
{n:"Krishnum",c:"Nagpur",cu:["North Indian","Mughlai","Tandoor"],r:4.4,b:2,a:"Ramdaspeth, opposite IMA Hall",v:0,z:"krishnum-ramdaspeth-nagpur"},
{n:"The Gondwana",c:"Nagpur",cu:["Saoji","Vidarbha","Spicy"],r:4.5,b:2,a:"Hotel Tuli Imperial, Central Bazaar Road",v:1,z:"the-gondwana-tuli-imperial-nagpur"},
{n:"Ashoka Hotel",c:"Nagpur",cu:["Saoji","North Indian","Mutton"],r:4.4,b:1,a:"Trimurti Nagar, Khamla",v:0,z:"ashoka-saoji-trimurti-nagar-nagpur"},
{n:"Barbeque Nation",c:"Nagpur",cu:["Multi-Cuisine","Buffet","Grill"],r:4.3,b:2,a:"Empress City Mall, Pratap Nagar",v:0,z:"barbeque-nation-empress-mall-nagpur"},
{n:"Ranjit Hotel",c:"Nagpur",cu:["Maharashtrian","North Indian","Thali"],r:4.4,b:1,a:"Sitabuldi Main Road",v:0,z:"ranjit-hotel-sitabuldi-nagpur"},
{n:"Cafe Coffee Bean & Tea Leaf",c:"Nagpur",cu:["Cafe","Continental","Desserts"],r:4.2,b:2,a:"Eternity Mall, Sitabuldi",v:0,z:"coffee-bean-eternity-mall-nagpur"},
{n:"Sahil Restaurant",c:"Nagpur",cu:["Saoji","Mutton","Local"],r:4.5,b:1,a:"Mominpura, Old City",v:0,z:"sahil-saoji-mominpura-nagpur"},
{n:"Mr Beans Cafe",c:"Nagpur",cu:["Cafe","Italian","Continental"],r:4.4,b:2,a:"Dharampeth, near Maharaj Bagh",v:0,z:"mr-beans-cafe-dharampeth-nagpur"},
{n:"Vinayaka Mylari",c:"Mysore",cu:["South Indian","Dosa","Breakfast"],r:4.6,b:1,a:"Nazarbad, opposite Mysore Race Club",v:0,z:"vinayaka-mylari-nazarbad-mysore"},
{n:"Hotel RRR",c:"Mysore",cu:["Andhra","South Indian","Meals"],r:4.5,b:1,a:"Gandhi Square, Chamrajpura",v:0,z:"hotel-rrr-gandhi-square-mysore"},
{n:"Lalith Mahal Palace Dining Hall",c:"Mysore",cu:["Multi-Cuisine","Heritage","Continental"],r:4.4,b:3,a:"Lalitha Mahal Palace Hotel, T Narasipura Road",v:1,z:"lalitha-mahal-palace-dining-mysore"},
{n:"Hanumanthu Mess",c:"Mysore",cu:["Mangalorean","Seafood","Chicken"],r:4.5,b:1,a:"Salem Street, Mandi Mohalla",v:0,z:"hanumanthu-mess-mandi-mohalla-mysore"},
{n:"Olive Garden",c:"Mysore",cu:["Italian","Continental","Cafe"],r:4.3,b:2,a:"Ramanuja Road, Yadavagiri",v:0,z:"olive-garden-yadavagiri-mysore"},
{n:"Le Olive Garden",c:"Mysore",cu:["Multi-Cuisine","Continental","Garden Dining"],r:4.4,b:2,a:"Plot 113, KRS Road",v:0,z:"le-olive-garden-krs-road-mysore"},
{n:"Mahesh Prasad",c:"Mysore",cu:["South Indian","Vegetarian","Thali"],r:4.4,b:1,a:"Sayyaji Rao Road, Devaraja Mohalla",v:0,z:"mahesh-prasad-sayyaji-rao-mysore"},
{n:"Tiger Trail",c:"Mysore",cu:["North Indian","Mughlai","Multi-Cuisine"],r:4.5,b:3,a:"Royal Orchid Metropole, JLB Road",v:1,z:"tiger-trail-royal-orchid-mysore"},
{n:"Old House",c:"Mysore",cu:["Cafe","Continental","Italian"],r:4.4,b:2,a:"Vinoba Road, Jayalakshmipuram",v:0,z:"old-house-jayalakshmipuram-mysore"},
{n:"GTR (Gayatri Tiffin Room)",c:"Mysore",cu:["South Indian","Dosa","Breakfast"],r:4.5,b:1,a:"Krishnamurthypuram, behind Mysuru Palace",v:0,z:"gtr-krishnamurthypuram-mysore"},
{n:"Mandap",c:"Vadodara",cu:["Gujarati","Thali","Vegetarian"],r:4.5,b:2,a:"Welcomhotel by ITC, RC Dutt Road",v:1,z:"mandap-welcomhotel-vadodara"},
{n:"Canopy",c:"Vadodara",cu:["Multi-Cuisine","Continental","Buffet"],r:4.4,b:2,a:"Vivanta Vadodara, Akota Gardens",v:1,z:"canopy-vivanta-akota-vadodara"},
{n:"Sayaji Sweets & Restaurant",c:"Vadodara",cu:["Gujarati","Sweets","Vegetarian"],r:4.5,b:1,a:"Sayajigunj, near railway station",v:0,z:"sayaji-sweets-sayajigunj-vadodara"},
{n:"Rajdhani Thali",c:"Vadodara",cu:["Gujarati","Rajasthani","Thali"],r:4.4,b:2,a:"Inorbit Mall, Gotri Road",v:0,z:"rajdhani-thali-inorbit-vadodara"},
{n:"Mahalaxmi Bhojanalay",c:"Vadodara",cu:["Gujarati","Thali","Home-Style"],r:4.6,b:1,a:"Raopura, opposite Nyay Mandir",v:0,z:"mahalaxmi-bhojanalay-raopura-vadodara"},
{n:"Kalyan Restaurant",c:"Vadodara",cu:["Punjabi","North Indian","Tandoor"],r:4.4,b:2,a:"Race Course Circle, Alkapuri",v:0,z:"kalyan-restaurant-alkapuri-vadodara"},
{n:"Cafe Goodness",c:"Vadodara",cu:["Cafe","Healthy","Continental"],r:4.5,b:2,a:"Old Padra Road, Akota",v:0,z:"cafe-goodness-akota-vadodara"},
{n:"Peshawri",c:"Vadodara",cu:["North West Frontier","Tandoor","Fine Dining"],r:4.5,b:3,a:"Welcomhotel by ITC, RC Dutt Road",v:1,z:"peshawri-welcomhotel-vadodara"},
{n:"Hari Krishna",c:"Vadodara",cu:["South Indian","Vegetarian","Dosa"],r:4.4,b:1,a:"Sayajigunj, opposite Express Hotel",v:0,z:"hari-krishna-sayajigunj-vadodara"},
{n:"Black Taj",c:"Vadodara",cu:["Mughlai","North Indian","Biryani"],r:4.3,b:2,a:"Fatehgunj, opposite EME Temple",v:0,z:"black-taj-fatehgunj-vadodara"},
{n:"Bansi Vihar",c:"Patna",cu:["North Indian","Vegetarian","Thali"],r:4.5,b:2,a:"Boring Road, Shrikrishna Nagar",v:0,z:"bansi-vihar-boring-road-patna"},
{n:"Chacha Ki Hotel",c:"Patna",cu:["Bihari","Litti Chokha","Local"],r:4.6,b:1,a:"Boring Road, near Panchmukhi Hanuman Mandir",v:0,z:"chacha-ki-hotel-boring-road-patna"},
{n:"Kabila",c:"Patna",cu:["Multi-Cuisine","Mughlai","Tandoor"],r:4.4,b:2,a:"Hotel Maurya, South Gandhi Maidan",v:1,z:"kabila-hotel-maurya-patna"},
{n:"Pind Balluchi",c:"Patna",cu:["Punjabi","North Indian","Tandoor"],r:4.3,b:2,a:"Patliputra Industrial Estate",v:0,z:"pind-balluchi-patliputra-patna"},
{n:"Takshila",c:"Patna",cu:["North Indian","Continental","Multi-Cuisine"],r:4.5,b:3,a:"Hotel Maurya, South Gandhi Maidan",v:1,z:"takshila-hotel-maurya-patna"},
{n:"Mainland China",c:"Patna",cu:["Chinese","Asian","Pan-Asian"],r:4.4,b:2,a:"Maurya Lok Complex, Dak Bungalow Road",v:0,z:"mainland-china-maurya-lok-patna"},
{n:"Litti Hub",c:"Patna",cu:["Bihari","Litti Chokha","Street Food"],r:4.5,b:1,a:"Frazer Road, near Heritage Hotel",v:0,z:"litti-hub-frazer-road-patna"},
{n:"Cafe Coffee Day The Square",c:"Patna",cu:["Cafe","Continental","Desserts"],r:4.2,b:2,a:"Boring Canal Road, near Panchmukhi Mandir",v:0,z:"ccd-square-boring-canal-patna"},
{n:"Banaras Restaurant",c:"Patna",cu:["North Indian","Banarasi","Vegetarian"],r:4.4,b:1,a:"Exhibition Road, Gandhi Maidan",v:0,z:"banaras-restaurant-exhibition-road-patna"},
{n:"Nirvana Restaurant",c:"Patna",cu:["Multi-Cuisine","Mughlai","Tandoor"],r:4.3,b:2,a:"Lemon Tree Hotel, Frazer Road",v:1,z:"nirvana-lemon-tree-patna"},
{n:"Jharokha",c:"Bhopal",cu:["North Indian","Mughlai","Awadhi"],r:4.4,b:2,a:"Hotel Noor Us Sabah Palace, V I P Road",v:1,z:"jharokha-noor-us-sabah-bhopal"},
{n:"The Reds",c:"Bhopal",cu:["Continental","Italian","Cafe"],r:4.2,b:2,a:"Plot 14, MP Nagar Zone-1",v:0,z:"the-reds-mp-nagar-bhopal"},
{n:"Nukkad Bhopal",c:"Bhopal",cu:["Street Food","Chaat","North Indian"],r:4.4,b:1,a:"DB Mall, Arera Hills",v:0,z:"nukkad-db-mall-bhopal"},
{n:"Cafe Mocha",c:"Bhopal",cu:["Cafe","Continental","Italian"],r:4.3,b:2,a:"DB City Mall, Arera Hills",v:0,z:"cafe-mocha-db-city-bhopal"},
{n:"Naan Stop",c:"Bhopal",cu:["North Indian","Mughlai","Tandoor"],r:4.3,b:2,a:"Plot 36, Press Complex, MP Nagar",v:0,z:"naan-stop-mp-nagar-bhopal"},
{n:"7 Spice Restaurant",c:"Nagpur",cu:["North Indian","Mughlai","Multi-Cuisine"],r:4.4,b:2,a:"Wardha Road, Pratap Nagar",v:0,z:"7-spice-pratap-nagar-nagpur"},
{n:"Vidarbha Saoji",c:"Nagpur",cu:["Saoji","Maharashtrian","Mutton"],r:4.4,b:1,a:"Khamla Road, near MIDC",v:0,z:"vidarbha-saoji-khamla-nagpur"},
{n:"Naivedyam Nagpur",c:"Nagpur",cu:["South Indian","Vegetarian","Dosa"],r:4.3,b:1,a:"Dharampeth, Shankar Nagar Square",v:1,z:"naivedyam-dharampeth-nagpur"},
{n:"The Orchid Cafe",c:"Nagpur",cu:["Continental","Italian","Cafe"],r:4.3,b:2,a:"The Orchid Hotel, Pratap Nagar",v:0,z:"orchid-cafe-pratap-nagar-nagpur"},
{n:"Anand Bhandar",c:"Nagpur",cu:["Maharashtrian","Vegetarian","Thali"],r:4.4,b:1,a:"Mahal, near Cotton Market",v:1,z:"anand-bhandar-mahal-nagpur"},
{n:"Hotel Mahesh Prasad Annex",c:"Mysore",cu:["South Indian","Vegetarian","Andhra"],r:4.3,b:1,a:"Sayyaji Rao Road, Devaraja Mohalla",v:1,z:"mahesh-prasad-annex-sayyaji-rao-mysore"},
{n:"Cosmo Village Restaurant",c:"Mysore",cu:["Multi-Cuisine","Continental","Indian"],r:4.2,b:2,a:"Hyderali Road, Yadavagiri",v:0,z:"cosmo-village-yadavagiri-mysore"},
{n:"Depth N Green",c:"Mysore",cu:["Continental","Italian","Cafe"],r:4.3,b:2,a:"Vinoba Road, Jayalakshmipuram",v:0,z:"depth-n-green-jayalakshmipuram-mysore"},
{n:"Mylari Original",c:"Mysore",cu:["South Indian","Dosa","Breakfast"],r:4.5,b:1,a:"Nazarbad Main Road",v:0,z:"mylari-original-nazarbad-mysore"},
{n:"Park Lane Hotel",c:"Mysore",cu:["Multi-Cuisine","Continental","Indian"],r:4.3,b:2,a:"2716 Sri Harsha Road, Lashkar Mohalla",v:0,z:"park-lane-hotel-lashkar-mysore"},
{n:"Hocco Eatery",c:"Vadodara",cu:["Continental","Italian","Cafe"],r:4.4,b:2,a:"Race Course Circle, Alkapuri",v:0,z:"hocco-eatery-alkapuri-vadodara"},
{n:"Volga Restaurant",c:"Vadodara",cu:["North Indian","Mughlai","Tandoor"],r:4.3,b:2,a:"Sayajigunj, near railway station",v:0,z:"volga-sayajigunj-vadodara"},
{n:"Real Veg",c:"Vadodara",cu:["Gujarati","Vegetarian","Multi-Cuisine"],r:4.3,b:2,a:"Inorbit Mall, Gotri Road",v:1,z:"real-veg-inorbit-vadodara"},
{n:"Cafe Brera",c:"Vadodara",cu:["Italian","Continental","Cafe"],r:4.4,b:2,a:"Old Padra Road, Akota",v:0,z:"cafe-brera-akota-vadodara"},
{n:"Punjabi Adda",c:"Vadodara",cu:["Punjabi","North Indian","Tandoor"],r:4.2,b:2,a:"Sun Pharma Road, Atladara",v:0,z:"punjabi-adda-atladara-vadodara"},
{n:"Anandi Vatika",c:"Patna",cu:["North Indian","Vegetarian","Multi-Cuisine"],r:4.3,b:2,a:"Boring Road, Patliputra Colony",v:1,z:"anandi-vatika-boring-road-patna"},
{n:"Hare Krishna Restaurant",c:"Patna",cu:["South Indian","Vegetarian","Dosa"],r:4.3,b:1,a:"Boring Canal Road, opposite Panchmukhi Hanuman Mandir",v:1,z:"hare-krishna-boring-canal-patna"},
{n:"Pinky Palace",c:"Patna",cu:["Bihari","Mutton","Champaran"],r:4.4,b:1,a:"Patna Junction Area, near GPO",v:0,z:"pinky-palace-junction-patna"},
{n:"Cafe Coffee Day Maurya Lok",c:"Patna",cu:["Cafe","Continental","Desserts"],r:4.1,b:2,a:"Maurya Lok Complex, Dak Bungalow Road",v:0,z:"ccd-maurya-lok-patna"},
{n:"Nukkadwala Patna",c:"Patna",cu:["Street Food","Chaat","Bihari"],r:4.4,b:1,a:"Boring Road, opposite Panchmukhi Hanuman",v:0,z:"nukkadwala-boring-road-patna"},
{n:"Sasumaa",c:"Surat",cu:["Gujarati","Thali","Vegetarian"],r:4.5,b:2,a:"Citylight Road, Athwa",v:1,z:"sasumaa-citylight-surat"},
{n:"Kansar Gujarati Thali",c:"Surat",cu:["Gujarati","Thali","Vegetarian"],r:4.4,b:2,a:"Surat Marriott Hotel, Athwa Lines",v:1,z:"kansar-marriott-surat"},
{n:"Surati Locho King",c:"Surat",cu:["Gujarati","Surati","Street Food"],r:4.5,b:1,a:"Lal Darwaja, Bhagal",v:1,z:"surati-locho-king-bhagal-surat"},
{n:"Coal Barbecues",c:"Surat",cu:["Multi-Cuisine","Buffet","Grill"],r:4.3,b:2,a:"VR Mall, Dumas Road",v:0,z:"coal-barbecues-vr-mall-surat"},
{n:"Dholu Maharaj",c:"Surat",cu:["Gujarati","Surati","Snacks"],r:4.4,b:1,a:"Chowk Bazaar, near Old City",v:1,z:"dholu-maharaj-chowk-bazaar-surat"},
{n:"Royal Albert Hotel",c:"Surat",cu:["North Indian","Continental","Multi-Cuisine"],r:4.3,b:2,a:"Vesu Main Road, near Surat Diamond Bourse",v:0,z:"royal-albert-vesu-surat"},
{n:"Pure South Indian Restaurant",c:"Surat",cu:["South Indian","Vegetarian","Dosa"],r:4.4,b:1,a:"Nanpura, opposite Saiba Hospital",v:1,z:"pure-south-indian-nanpura-surat"},
{n:"Cafe Hosh",c:"Surat",cu:["Cafe","Continental","Italian"],r:4.4,b:2,a:"Citylight Road, Parle Point",v:0,z:"cafe-hosh-citylight-surat"},
{n:"Sufiyana",c:"Surat",cu:["Mughlai","North Indian","Biryani"],r:4.3,b:2,a:"Adajan Patia, opposite Hari Krishna Diamonds",v:0,z:"sufiyana-adajan-surat"},
{n:"Jugaadi Adda",c:"Surat",cu:["North Indian","Continental","Cafe"],r:4.3,b:2,a:"Piplod, near LP Savani School",v:0,z:"jugaadi-adda-piplod-surat"},
{n:"Giri Manja's",c:"Mangalore",cu:["Mangalorean","Seafood","Konkani"],r:4.6,b:2,a:"Bunder, near Old Port",v:0,z:"giri-manjas-bunder-mangalore"},
{n:"Machali",c:"Mangalore",cu:["Mangalorean","Seafood","Coastal"],r:4.5,b:2,a:"Maximus Mall, Light House Hill Road",v:0,z:"machali-maximus-mangalore"},
{n:"Ocean Pearl",c:"Mangalore",cu:["Mangalorean","Continental","Seafood"],r:4.4,b:3,a:"Hotel Ocean Pearl, Navabharath Circle",v:1,z:"ocean-pearl-navabharath-mangalore"},
{n:"Hao Ming",c:"Mangalore",cu:["Chinese","Pan-Asian","Cantonese"],r:4.4,b:2,a:"Bharath Mall, Bejai",v:0,z:"hao-ming-bharath-mall-mangalore"},
{n:"Spindrift",c:"Mangalore",cu:["Multi-Cuisine","Continental","Cafe"],r:4.4,b:2,a:"Goldfinch Hotel, Bunts Hostel Road",v:0,z:"spindrift-goldfinch-mangalore"},
{n:"Pabbas Ideal Ice Cream",c:"Mangalore",cu:["Desserts","Ice Cream","Sweets"],r:4.5,b:1,a:"Lalbagh Main Road",v:1,z:"pabbas-ideal-lalbagh-mangalore"},
{n:"Hotel Janatha Deluxe",c:"Mangalore",cu:["Mangalorean","Vegetarian","South Indian"],r:4.3,b:1,a:"K S Rao Road, Hampankatta",v:1,z:"janatha-deluxe-hampankatta-mangalore"},
{n:"Panchakajjaya",c:"Mangalore",cu:["Mangalorean","South Indian","Vegetarian"],r:4.4,b:1,a:"Balmatta, near Kankanady",v:1,z:"panchakajjaya-balmatta-mangalore"},
{n:"Liquid Lounge",c:"Mangalore",cu:["Cafe","Continental","Italian"],r:4.3,b:2,a:"Bharath Mall, Bejai",v:0,z:"liquid-lounge-bharath-mangalore"},
{n:"Gajalee Mangalore",c:"Mangalore",cu:["Mangalorean","Seafood","Goan"],r:4.4,b:2,a:"Hotel Deepa Comforts, M G Road",v:0,z:"gajalee-deepa-comforts-mangalore"},
{n:"Dalma Restaurant",c:"Bhubaneswar",cu:["Odia","Vegetarian","Thali"],r:4.6,b:2,a:"Saheed Nagar, near AG Square",v:1,z:"dalma-saheed-nagar-bhubaneswar"},
{n:"Hare Krishna Restaurant",c:"Bhubaneswar",cu:["South Indian","Vegetarian","Thali"],r:4.5,b:2,a:"Master Canteen Square, Sahid Nagar",v:1,z:"hare-krishna-master-canteen-bhubaneswar"},
{n:"Truptee",c:"Bhubaneswar",cu:["Odia","Vegetarian","Sweets"],r:4.4,b:1,a:"Saheed Nagar Main Road",v:1,z:"truptee-saheed-nagar-bhubaneswar"},
{n:"Mauli Tiffin Centre",c:"Bhubaneswar",cu:["Odia","Bengali","Sweets"],r:4.5,b:1,a:"Old Town, near Lingaraj Temple",v:1,z:"mauli-tiffin-old-town-bhubaneswar"},
{n:"Kanika Mayfair",c:"Bhubaneswar",cu:["Odia","Continental","Multi-Cuisine"],r:4.4,b:3,a:"Mayfair Lagoon, Jaydev Vihar",v:1,z:"kanika-mayfair-jaydev-vihar-bhubaneswar"},
{n:"Chappan Bhog",c:"Bhubaneswar",cu:["Odia","Sweets","Vegetarian"],r:4.5,b:1,a:"Master Canteen Square",v:1,z:"chappan-bhog-master-canteen-bhubaneswar"},
{n:"Tangerine 9",c:"Bhubaneswar",cu:["Continental","Italian","Cafe"],r:4.4,b:2,a:"Esplanade One Mall, Rasulgarh",v:0,z:"tangerine-9-esplanade-bhubaneswar"},
{n:"Wildflower at Mayfair",c:"Bhubaneswar",cu:["Multi-Cuisine","Continental","Asian"],r:4.5,b:3,a:"Mayfair Lagoon, Jaydev Vihar",v:0,z:"wildflower-mayfair-bhubaneswar"},
{n:"Cafe Coffee Day Janpath",c:"Bhubaneswar",cu:["Cafe","Continental","Desserts"],r:4.1,b:2,a:"Janpath Road, Master Canteen",v:0,z:"ccd-janpath-bhubaneswar"},
{n:"Odisha Hotel",c:"Bhubaneswar",cu:["Odia","Bengali","Thali"],r:4.5,b:1,a:"Bapuji Nagar, near Forest Park",v:0,z:"odisha-hotel-bapuji-nagar-bhubaneswar"},
{n:"Khorikaa",c:"Guwahati",cu:["Assamese","Naga","Tribal"],r:4.6,b:2,a:"GS Road, Bhangagarh",v:0,z:"khorikaa-bhangagarh-guwahati"},
{n:"Paradise Restaurant",c:"Guwahati",cu:["Assamese","Bengali","Multi-Cuisine"],r:4.4,b:2,a:"GNB Road, Silpukhuri",v:0,z:"paradise-silpukhuri-guwahati"},
{n:"Heritage Khorikaa",c:"Guwahati",cu:["Assamese","Tribal","Vegetarian"],r:4.5,b:2,a:"6 Mile, VIP Road",v:0,z:"heritage-khorikaa-six-mile-guwahati"},
{n:"Beatrouts",c:"Guwahati",cu:["Cafe","Continental","Italian"],r:4.4,b:2,a:"Zoo Road, near Hub Mall",v:0,z:"beatrouts-zoo-road-guwahati"},
{n:"Kiran's Kitchen",c:"Guwahati",cu:["North Indian","Mughlai","Tandoor"],r:4.3,b:2,a:"Sundarpur, Beltola",v:0,z:"kirans-kitchen-beltola-guwahati"},
{n:"Mainland China Guwahati",c:"Guwahati",cu:["Chinese","Asian","Pan-Asian"],r:4.3,b:2,a:"Hub Mall, Zoo Road",v:0,z:"mainland-china-hub-mall-guwahati"},
{n:"Sundarban Resort",c:"Guwahati",cu:["Bengali","Assamese","Multi-Cuisine"],r:4.3,b:3,a:"VIP Road, near Khanapara",v:0,z:"sundarban-resort-khanapara-guwahati"},
{n:"Cafe Hendrix",c:"Guwahati",cu:["Cafe","Continental","Mexican"],r:4.4,b:2,a:"GS Road, Christian Basti",v:0,z:"cafe-hendrix-christian-basti-guwahati"},
{n:"Naga Kitchen",c:"Guwahati",cu:["Naga","Tribal","Smoked Meat"],r:4.4,b:2,a:"Hatigaon, Lachit Nagar",v:0,z:"naga-kitchen-hatigaon-guwahati"},
{n:"Saffron Mayfair",c:"Guwahati",cu:["Multi-Cuisine","Continental","Indian"],r:4.4,b:3,a:"Vivanta Guwahati, Khanapara",v:0,z:"saffron-vivanta-guwahati"},
{n:"Villa Maya",c:"Trivandrum",cu:["Continental","European","Fine Dining"],r:4.5,b:3,a:"Airport Road, Anayara",v:0,z:"villa-maya-anayara-trivandrum"},
{n:"Mathrubhumi Hotel",c:"Trivandrum",cu:["Kerala","South Indian","Sadya"],r:4.5,b:1,a:"Statue Junction, near Secretariat",v:1,z:"mathrubhumi-statue-junction-trivandrum"},
{n:"Kalavara Restaurant",c:"Trivandrum",cu:["Kerala","Seafood","South Indian"],r:4.4,b:2,a:"Press Road, Statue Junction",v:0,z:"kalavara-press-road-trivandrum"},
{n:"Travancore Court",c:"Trivandrum",cu:["Multi-Cuisine","Continental","Indian"],r:4.4,b:3,a:"Hotel Travancore Court, Thycaud",v:0,z:"travancore-court-thycaud-trivandrum"},
{n:"Ariya Niwas",c:"Trivandrum",cu:["Kerala","South Indian","Vegetarian"],r:4.4,b:1,a:"Aristo Junction, Manorama Road",v:1,z:"ariya-niwas-aristo-trivandrum"},
{n:"Cafe Coffee Day Statue",c:"Trivandrum",cu:["Cafe","Continental","Desserts"],r:4.1,b:2,a:"Statue Junction, M G Road",v:0,z:"ccd-statue-trivandrum"},
{n:"Sea Shells Restaurant",c:"Trivandrum",cu:["Kerala","Seafood","Continental"],r:4.3,b:2,a:"Hotel Mascot, Palayam",v:0,z:"sea-shells-mascot-trivandrum"},
{n:"Hotel Rahmaniya",c:"Trivandrum",cu:["Kerala","Mughlai","Biryani"],r:4.4,b:1,a:"Vazhuthacaud, near GPO",v:0,z:"rahmaniya-vazhuthacaud-trivandrum"},
{n:"Cafe Mojo",c:"Trivandrum",cu:["Cafe","Continental","Italian"],r:4.3,b:2,a:"Mall of Travancore, Chackai",v:0,z:"cafe-mojo-mall-of-travancore-trivandrum"},
{n:"Zam Zam Restaurant",c:"Trivandrum",cu:["Kerala","Malabar","Biryani"],r:4.4,b:1,a:"Pulimoodu, near Connemara Market",v:0,z:"zam-zam-pulimoodu-trivandrum"},
{n:"Kaveri Restaurant",c:"Ranchi",cu:["North Indian","Mughlai","Tandoor"],r:4.4,b:2,a:"Main Road, near Albert Ekka Chowk",v:0,z:"kaveri-main-road-ranchi"},
{n:"Jharkhand Tribal Kitchen",c:"Ranchi",cu:["Jharkhandi","Tribal","Local"],r:4.5,b:2,a:"Argora Square, near Birsa Park",v:0,z:"jharkhand-tribal-kitchen-argora-ranchi"},
{n:"Capitol Hill Hotel Restaurant",c:"Ranchi",cu:["Multi-Cuisine","Continental","Indian"],r:4.3,b:2,a:"Main Road, Sujata Chowk",v:0,z:"capitol-hill-main-road-ranchi"},
{n:"Yellow Sapphire",c:"Ranchi",cu:["Multi-Cuisine","Continental","Asian"],r:4.4,b:3,a:"Radisson Blu, Main Road",v:0,z:"yellow-sapphire-radisson-ranchi"},
{n:"Punjabi Rasoi",c:"Ranchi",cu:["Punjabi","North Indian","Tandoor"],r:4.3,b:2,a:"Lalpur Chowk, Kanke Road",v:0,z:"punjabi-rasoi-lalpur-ranchi"},
{n:"Cafe Regal",c:"Ranchi",cu:["Cafe","Continental","Italian"],r:4.3,b:2,a:"Main Road, near Hotel BNR Chanakya",v:0,z:"cafe-regal-main-road-ranchi"},
{n:"Hotel Yuvraj Restaurant",c:"Ranchi",cu:["North Indian","Bengali","Mughlai"],r:4.2,b:2,a:"Doranda, near Big Bazaar",v:0,z:"yuvraj-doranda-ranchi"},
{n:"Domino's Pizza Lalpur",c:"Ranchi",cu:["Italian","Pizza","Fast Food"],r:4.1,b:2,a:"Lalpur, near Albert Ekka Chowk",v:0,z:"dominos-lalpur-ranchi"},
{n:"Litti Galli",c:"Ranchi",cu:["Bihari","Jharkhandi","Litti Chokha"],r:4.4,b:1,a:"Kachehri Chowk, near Jail Chowk",v:0,z:"litti-galli-kachehri-ranchi"},
{n:"The Big Banyan",c:"Ranchi",cu:["Multi-Cuisine","Continental","Indian"],r:4.3,b:2,a:"Ranchi Club Road, near Albert Ekka Chowk",v:0,z:"big-banyan-ranchi-club-ranchi"},
{n:"Town Table",c:"Dehradun",cu:["Multi-Cuisine","Continental","Indian"],r:4.5,b:3,a:"Jaypee Residency Manor, Hotel Manor",v:0,z:"town-table-jaypee-dehradun"},
{n:"Polo House",c:"Dehradun",cu:["Continental","Italian","Cafe"],r:4.4,b:3,a:"100 Rajpur Road",v:0,z:"polo-house-rajpur-road-dehradun"},
{n:"Doon Darbar",c:"Dehradun",cu:["Garhwali","North Indian","Pahari"],r:4.5,b:2,a:"Astley Hall, Rajpur Road",v:0,z:"doon-darbar-astley-hall-dehradun"},
{n:"Kumar Sweets",c:"Dehradun",cu:["Vegetarian","Sweets","North Indian"],r:4.4,b:1,a:"Paltan Bazaar, near Clock Tower",v:1,z:"kumar-sweets-paltan-bazaar-dehradun"},
{n:"Cafe De La Maison",c:"Dehradun",cu:["Cafe","Continental","French"],r:4.4,b:2,a:"42 Rajpur Road, near IT Park",v:0,z:"cafe-de-la-maison-rajpur-road-dehradun"},
{n:"Mussoorie Express",c:"Dehradun",cu:["North Indian","Mughlai","Tandoor"],r:4.3,b:2,a:"Convent Road, near Astley Hall",v:0,z:"mussoorie-express-convent-dehradun"},
{n:"Black Pepper",c:"Dehradun",cu:["Multi-Cuisine","Continental","Chinese"],r:4.3,b:2,a:"Rajpur Road, near IT Park",v:0,z:"black-pepper-rajpur-road-dehradun"},
{n:"Yeti The Himalayan Kitchen",c:"Dehradun",cu:["Tibetan","Nepali","Asian"],r:4.4,b:2,a:"Rajpur Road, near Income Tax Office",v:0,z:"yeti-himalayan-kitchen-dehradun"},
{n:"Anand Sweets",c:"Dehradun",cu:["South Indian","Vegetarian","Sweets"],r:4.4,b:1,a:"Paltan Bazaar, near Tehsil Chowk",v:1,z:"anand-sweets-paltan-bazaar-dehradun"},
{n:"Buddies Cafe",c:"Dehradun",cu:["Cafe","Continental","Italian"],r:4.3,b:2,a:"Pacific Mall, Saharanpur Road",v:0,z:"buddies-cafe-pacific-mall-dehradun"},
{n:"Garam Masala",c:"Raipur",cu:["North Indian","Mughlai","Tandoor"],r:4.4,b:2,a:"Civil Lines, near Telibandha Talab",v:0,z:"garam-masala-civil-lines-raipur"},
{n:"Chhattisgarh Bhojnalay",c:"Raipur",cu:["Chhattisgarhi","Tribal","Thali"],r:4.5,b:1,a:"Devendra Nagar, near Magneto Mall",v:1,z:"chhattisgarh-bhojnalay-devendra-nagar-raipur"},
{n:"Mehfil-E-Khaas",c:"Raipur",cu:["Mughlai","North Indian","Biryani"],r:4.4,b:2,a:"Pandri Bus Stand area",v:0,z:"mehfil-e-khaas-pandri-raipur"},
{n:"Tatva The Multicuisine Restaurant",c:"Raipur",cu:["Multi-Cuisine","Continental","Indian"],r:4.4,b:3,a:"Hyatt Regency, GE Road",v:0,z:"tatva-hyatt-raipur"},
{n:"Rasoi Express",c:"Raipur",cu:["North Indian","South Indian","Multi-Cuisine"],r:4.3,b:2,a:"Magneto Mall, Devendra Nagar",v:0,z:"rasoi-express-magneto-raipur"},
{n:"Cafe Coffee Day Civil Lines",c:"Raipur",cu:["Cafe","Continental","Desserts"],r:4.1,b:2,a:"Civil Lines, near Vidhan Sabha",v:0,z:"ccd-civil-lines-raipur"},
{n:"Bawarchi Restaurant",c:"Raipur",cu:["North Indian","Mughlai","Vegetarian"],r:4.3,b:2,a:"Shankar Nagar, near Marine Drive",v:1,z:"bawarchi-shankar-nagar-raipur"},
{n:"Sayaji Hotel Restaurant",c:"Raipur",cu:["Multi-Cuisine","Continental","Asian"],r:4.4,b:3,a:"Sayaji Hotel, VIP Road, Telibandha",v:0,z:"sayaji-hotel-vip-road-raipur"},
{n:"Annapurna Restaurant",c:"Raipur",cu:["Chhattisgarhi","Vegetarian","Thali"],r:4.4,b:1,a:"Jaistambh Chowk, near Railway Station",v:1,z:"annapurna-jaistambh-raipur"},
{n:"Cafe Hangout",c:"Raipur",cu:["Cafe","Italian","Continental"],r:4.3,b:2,a:"VIP Road, Telibandha",v:0,z:"cafe-hangout-vip-road-raipur"},
];
