window.WIB_SEARCH_INDEX = [
  {l:"Home",u:"/",c:"Page"},
  {l:"About",u:"/about/",c:"Page"},
  {l:"Editorial Process",u:"/editorial-process/",c:"Page"},
  {l:"Reader Reviews",u:"/reviews/",c:"Page"},
  {l:"Contact",u:"/contact/",c:"Page"},
  {l:"AI Compare",u:"/compare/ai/",c:"Tool"},
  {l:"Decide for me",u:"/decide/",c:"Tool"},
  {l:"Quiz",u:"/quiz/",c:"Tool"},
  {l:"Price Finder",u:"/price-finder",c:"Tool"},
  {l:"Schools",u:"/schools/",c:"Category"},
  {l:"Colleges",u:"/colleges/",c:"Category"},
  {l:"Electronics",u:"/electronics/",c:"Category"},
  {l:"Cars",u:"/cars/",c:"Category"},
  {l:"Hospitals",u:"/hospitals/",c:"Category"},
  {l:"Travel",u:"/travel/",c:"Category"},
  {l:"Restaurants",u:"/restaurants/",c:"Category"},
  {l:"Accessories",u:"/accessories/",c:"Category"},
  {l:"Real estate",u:"/real-estate/",c:"Category"},
  {l:"Jobs",u:"/jobs/",c:"Category"},
  {l:"Blog",u:"/blog/",c:"Category"},
  {l:"Hospitals in Ahmedabad",u:"/hospitals/ahmedabad/",c:"City"},
  {l:"Hospitals in Bangalore",u:"/hospitals/bangalore/",c:"City"},
  {l:"Hospitals in Chennai",u:"/hospitals/chennai/",c:"City"},
  {l:"Hospitals in Delhi",u:"/hospitals/delhi/",c:"City"},
  {l:"Hospitals in Hyderabad",u:"/hospitals/hyderabad/",c:"City"},
  {l:"Hospitals in Kolkata",u:"/hospitals/kolkata/",c:"City"},
  {l:"Hospitals in Mumbai",u:"/hospitals/mumbai/",c:"City"},
  {l:"Hospitals in Pune",u:"/hospitals/pune/",c:"City"},
  {l:"Restaurants in Ahmedabad",u:"/restaurants/ahmedabad/",c:"City"},
  {l:"Restaurants in Bangalore",u:"/restaurants/bangalore/",c:"City"},
  {l:"Restaurants in Chandigarh",u:"/restaurants/chandigarh/",c:"City"},
  {l:"Restaurants in Chennai",u:"/restaurants/chennai/",c:"City"},
  {l:"Restaurants in Coimbatore",u:"/restaurants/coimbatore/",c:"City"},
  {l:"Restaurants in Delhi",u:"/restaurants/delhi/",c:"City"},
  {l:"Restaurants in Hyderabad",u:"/restaurants/hyderabad/",c:"City"},
  {l:"Restaurants in Indore",u:"/restaurants/indore/",c:"City"},
  {l:"Restaurants in Jaipur",u:"/restaurants/jaipur/",c:"City"},
  {l:"Restaurants in Kochi",u:"/restaurants/kochi/",c:"City"},
  {l:"Restaurants in Kolkata",u:"/restaurants/kolkata/",c:"City"},
  {l:"Restaurants in Lucknow",u:"/restaurants/lucknow/",c:"City"},
  {l:"Restaurants in Mumbai",u:"/restaurants/mumbai/",c:"City"},
  {l:"Restaurants in Pune",u:"/restaurants/pune/",c:"City"},
  {l:"Restaurants in Visakhapatnam",u:"/restaurants/visakhapatnam/",c:"City"},
  {l:"Schools in Ahmedabad",u:"/schools/ahmedabad/",c:"City"},
  {l:"Schools in Bhopal",u:"/schools/bhopal/",c:"City"},
  {l:"Schools in Chandigarh",u:"/schools/chandigarh/",c:"City"},
  {l:"Schools in Coimbatore",u:"/schools/coimbatore/",c:"City"},
  {l:"Schools in Indore",u:"/schools/indore/",c:"City"},
  {l:"Schools in Jaipur",u:"/schools/jaipur/",c:"City"},
  {l:"Schools in Kanpur",u:"/schools/kanpur/",c:"City"},
  {l:"Schools in Kochi",u:"/schools/kochi/",c:"City"},
  {l:"Schools in Lucknow",u:"/schools/lucknow/",c:"City"},
  {l:"Schools in Madurai",u:"/schools/madurai/",c:"City"},
  {l:"Schools in Mangalore",u:"/schools/mangalore/",c:"City"},
  {l:"Schools in Mysore",u:"/schools/mysore/",c:"City"},
  {l:"Schools in Nagpur",u:"/schools/nagpur/",c:"City"},
  {l:"Schools in Nashik",u:"/schools/nashik/",c:"City"},
  {l:"Schools in Patna",u:"/schools/patna/",c:"City"},
  {l:"Schools in Pune",u:"/schools/pune/",c:"City"},
  {l:"Schools in Surat",u:"/schools/surat/",c:"City"},
  {l:"Schools in Trichy",u:"/schools/trichy/",c:"City"},
  {l:"Schools in Vadodara",u:"/schools/vadodara/",c:"City"},
  {l:"Schools in Visakhapatnam",u:"/schools/visakhapatnam/",c:"City"},
  {l:"Colleges in Ahmedabad",u:"/colleges/ahmedabad/",c:"City"},
  {l:"Colleges in Bhopal",u:"/colleges/bhopal/",c:"City"},
  {l:"Colleges in Chandigarh",u:"/colleges/chandigarh/",c:"City"},
  {l:"Colleges in Coimbatore",u:"/colleges/coimbatore/",c:"City"},
  {l:"Colleges in Indore",u:"/colleges/indore/",c:"City"},
  {l:"Colleges in Jaipur",u:"/colleges/jaipur/",c:"City"},
  {l:"Colleges in Kanpur",u:"/colleges/kanpur/",c:"City"},
  {l:"Colleges in Kochi",u:"/colleges/kochi/",c:"City"},
  {l:"Colleges in Lucknow",u:"/colleges/lucknow/",c:"City"},
  {l:"Colleges in Madurai",u:"/colleges/madurai/",c:"City"},
  {l:"Colleges in Mangalore",u:"/colleges/mangalore/",c:"City"},
  {l:"Colleges in Mysore",u:"/colleges/mysore/",c:"City"},
  {l:"Colleges in Nagpur",u:"/colleges/nagpur/",c:"City"},
  {l:"Colleges in Nashik",u:"/colleges/nashik/",c:"City"},
  {l:"Colleges in Patna",u:"/colleges/patna/",c:"City"},
  {l:"Colleges in Pune",u:"/colleges/pune/",c:"City"},
  {l:"Colleges in Surat",u:"/colleges/surat/",c:"City"},
  {l:"Colleges in Trichy",u:"/colleges/trichy/",c:"City"},
  {l:"Colleges in Vadodara",u:"/colleges/vadodara/",c:"City"},
  {l:"Colleges in Visakhapatnam",u:"/colleges/visakhapatnam/",c:"City"},
  {l:"Best Cardiology in Ahmedabad",u:"/hospitals/ahmedabad/best-cardiology/",c:"Hospital Specialty"},
  {l:"Best Gastroenterology in Ahmedabad",u:"/hospitals/ahmedabad/best-gastroenterology/",c:"Hospital Specialty"},
  {l:"Best Gynaecology in Ahmedabad",u:"/hospitals/ahmedabad/best-gynaecology/",c:"Hospital Specialty"},
  {l:"Best Neurology in Ahmedabad",u:"/hospitals/ahmedabad/best-neurology/",c:"Hospital Specialty"},
  {l:"Best Oncology in Ahmedabad",u:"/hospitals/ahmedabad/best-oncology/",c:"Hospital Specialty"},
  {l:"Best Orthopedics in Ahmedabad",u:"/hospitals/ahmedabad/best-orthopedics/",c:"Hospital Specialty"},
  {l:"Best Paediatrics in Ahmedabad",u:"/hospitals/ahmedabad/best-paediatrics/",c:"Hospital Specialty"},
  {l:"Best Cardiology in Bangalore",u:"/hospitals/bangalore/best-cardiology/",c:"Hospital Specialty"},
  {l:"Best Gastroenterology in Bangalore",u:"/hospitals/bangalore/best-gastroenterology/",c:"Hospital Specialty"},
  {l:"Best Gynaecology in Bangalore",u:"/hospitals/bangalore/best-gynaecology/",c:"Hospital Specialty"},
  {l:"Best Neurology in Bangalore",u:"/hospitals/bangalore/best-neurology/",c:"Hospital Specialty"},
  {l:"Best Oncology in Bangalore",u:"/hospitals/bangalore/best-oncology/",c:"Hospital Specialty"},
  {l:"Best Orthopedics in Bangalore",u:"/hospitals/bangalore/best-orthopedics/",c:"Hospital Specialty"},
  {l:"Best Paediatrics in Bangalore",u:"/hospitals/bangalore/best-paediatrics/",c:"Hospital Specialty"},
  {l:"Best Cardiology in Chennai",u:"/hospitals/chennai/best-cardiology/",c:"Hospital Specialty"},
  {l:"Best Gastroenterology in Chennai",u:"/hospitals/chennai/best-gastroenterology/",c:"Hospital Specialty"},
  {l:"Best Gynaecology in Chennai",u:"/hospitals/chennai/best-gynaecology/",c:"Hospital Specialty"},
  {l:"Best Neurology in Chennai",u:"/hospitals/chennai/best-neurology/",c:"Hospital Specialty"},
  {l:"Best Oncology in Chennai",u:"/hospitals/chennai/best-oncology/",c:"Hospital Specialty"},
  {l:"Best Orthopedics in Chennai",u:"/hospitals/chennai/best-orthopedics/",c:"Hospital Specialty"},
  {l:"Best Paediatrics in Chennai",u:"/hospitals/chennai/best-paediatrics/",c:"Hospital Specialty"},
  {l:"Best Cardiology in Delhi",u:"/hospitals/delhi/best-cardiology/",c:"Hospital Specialty"},
  {l:"Best Gastroenterology in Delhi",u:"/hospitals/delhi/best-gastroenterology/",c:"Hospital Specialty"},
  {l:"Best Gynaecology in Delhi",u:"/hospitals/delhi/best-gynaecology/",c:"Hospital Specialty"},
  {l:"Best Neurology in Delhi",u:"/hospitals/delhi/best-neurology/",c:"Hospital Specialty"},
  {l:"Best Oncology in Delhi",u:"/hospitals/delhi/best-oncology/",c:"Hospital Specialty"},
  {l:"Best Orthopedics in Delhi",u:"/hospitals/delhi/best-orthopedics/",c:"Hospital Specialty"},
  {l:"Best Paediatrics in Delhi",u:"/hospitals/delhi/best-paediatrics/",c:"Hospital Specialty"},
  {l:"Best Cardiology in Hyderabad",u:"/hospitals/hyderabad/best-cardiology/",c:"Hospital Specialty"},
  {l:"Best Gastroenterology in Hyderabad",u:"/hospitals/hyderabad/best-gastroenterology/",c:"Hospital Specialty"},
  {l:"Best Neurology in Hyderabad",u:"/hospitals/hyderabad/best-neurology/",c:"Hospital Specialty"},
  {l:"Best Oncology in Hyderabad",u:"/hospitals/hyderabad/best-oncology/",c:"Hospital Specialty"},
  {l:"Best Orthopedics in Hyderabad",u:"/hospitals/hyderabad/best-orthopedics/",c:"Hospital Specialty"},
  {l:"Best Cardiology in Kolkata",u:"/hospitals/kolkata/best-cardiology/",c:"Hospital Specialty"},
  {l:"Best Gastroenterology in Kolkata",u:"/hospitals/kolkata/best-gastroenterology/",c:"Hospital Specialty"},
  {l:"Best Gynaecology in Kolkata",u:"/hospitals/kolkata/best-gynaecology/",c:"Hospital Specialty"},
  {l:"Best Neurology in Kolkata",u:"/hospitals/kolkata/best-neurology/",c:"Hospital Specialty"},
  {l:"Best Oncology in Kolkata",u:"/hospitals/kolkata/best-oncology/",c:"Hospital Specialty"},
  {l:"Best Orthopedics in Kolkata",u:"/hospitals/kolkata/best-orthopedics/",c:"Hospital Specialty"},
  {l:"Best Paediatrics in Kolkata",u:"/hospitals/kolkata/best-paediatrics/",c:"Hospital Specialty"},
  {l:"Best Cardiology in Mumbai",u:"/hospitals/mumbai/best-cardiology/",c:"Hospital Specialty"},
  {l:"Best Gastroenterology in Mumbai",u:"/hospitals/mumbai/best-gastroenterology/",c:"Hospital Specialty"},
  {l:"Best Gynaecology in Mumbai",u:"/hospitals/mumbai/best-gynaecology/",c:"Hospital Specialty"},
  {l:"Best Neurology in Mumbai",u:"/hospitals/mumbai/best-neurology/",c:"Hospital Specialty"},
  {l:"Best Oncology in Mumbai",u:"/hospitals/mumbai/best-oncology/",c:"Hospital Specialty"},
  {l:"Best Orthopedics in Mumbai",u:"/hospitals/mumbai/best-orthopedics/",c:"Hospital Specialty"},
  {l:"Best Paediatrics in Mumbai",u:"/hospitals/mumbai/best-paediatrics/",c:"Hospital Specialty"},
  {l:"Best Cardiology in Pune",u:"/hospitals/pune/best-cardiology/",c:"Hospital Specialty"},
  {l:"Best Gastroenterology in Pune",u:"/hospitals/pune/best-gastroenterology/",c:"Hospital Specialty"},
  {l:"Best Gynaecology in Pune",u:"/hospitals/pune/best-gynaecology/",c:"Hospital Specialty"},
  {l:"Best Neurology in Pune",u:"/hospitals/pune/best-neurology/",c:"Hospital Specialty"},
  {l:"Best Oncology in Pune",u:"/hospitals/pune/best-oncology/",c:"Hospital Specialty"},
  {l:"Best Orthopedics in Pune",u:"/hospitals/pune/best-orthopedics/",c:"Hospital Specialty"},
  {l:"Best Paediatrics in Pune",u:"/hospitals/pune/best-paediatrics/",c:"Hospital Specialty"},
  {l:"Best Gujarati thali in Ahmedabad",u:"/restaurants/ahmedabad/best-gujarati-thali/",c:"Restaurant Cuisine"},
  {l:"Best Biryani in Bangalore",u:"/restaurants/bangalore/best-biryani/",c:"Restaurant Cuisine"},
  {l:"Best Cafes in Bangalore",u:"/restaurants/bangalore/best-cafes/",c:"Restaurant Cuisine"},
  {l:"Best Pubs breweries in Bangalore",u:"/restaurants/bangalore/best-pubs-breweries/",c:"Restaurant Cuisine"},
  {l:"Best South indian in Bangalore",u:"/restaurants/bangalore/best-south-indian/",c:"Restaurant Cuisine"},
  {l:"Best North indian in Chandigarh",u:"/restaurants/chandigarh/best-north-indian/",c:"Restaurant Cuisine"},
  {l:"Best Biryani in Chennai",u:"/restaurants/chennai/best-biryani/",c:"Restaurant Cuisine"},
  {l:"Best Chettinad in Chennai",u:"/restaurants/chennai/best-chettinad/",c:"Restaurant Cuisine"},
  {l:"Best South indian in Chennai",u:"/restaurants/chennai/best-south-indian/",c:"Restaurant Cuisine"},
  {l:"Best South indian in Coimbatore",u:"/restaurants/coimbatore/best-south-indian/",c:"Restaurant Cuisine"},
  {l:"Best Cafes in Delhi",u:"/restaurants/delhi/best-cafes/",c:"Restaurant Cuisine"},
  {l:"Best Mughlai in Delhi",u:"/restaurants/delhi/best-mughlai/",c:"Restaurant Cuisine"},
  {l:"Best Andhra in Hyderabad",u:"/restaurants/hyderabad/best-andhra/",c:"Restaurant Cuisine"},
  {l:"Best Biryani in Hyderabad",u:"/restaurants/hyderabad/best-biryani/",c:"Restaurant Cuisine"},
  {l:"Best Street food in Indore",u:"/restaurants/indore/best-street-food/",c:"Restaurant Cuisine"},
  {l:"Best Rajasthani in Jaipur",u:"/restaurants/jaipur/best-rajasthani/",c:"Restaurant Cuisine"},
  {l:"Best Kerala food in Kochi",u:"/restaurants/kochi/best-kerala-food/",c:"Restaurant Cuisine"},
  {l:"Best Seafood in Kochi",u:"/restaurants/kochi/best-seafood/",c:"Restaurant Cuisine"},
  {l:"Best Bengali in Kolkata",u:"/restaurants/kolkata/best-bengali/",c:"Restaurant Cuisine"},
  {l:"Best Chinese in Kolkata",u:"/restaurants/kolkata/best-chinese/",c:"Restaurant Cuisine"},
  {l:"Best Awadhi in Lucknow",u:"/restaurants/lucknow/best-awadhi/",c:"Restaurant Cuisine"},
  {l:"Best Kebabs in Lucknow",u:"/restaurants/lucknow/best-kebabs/",c:"Restaurant Cuisine"},
  {l:"Best Cafes in Mumbai",u:"/restaurants/mumbai/best-cafes/",c:"Restaurant Cuisine"},
  {l:"Best Seafood in Mumbai",u:"/restaurants/mumbai/best-seafood/",c:"Restaurant Cuisine"},
  {l:"Best Street food in Mumbai",u:"/restaurants/mumbai/best-street-food/",c:"Restaurant Cuisine"},
  {l:"Best Cafes in Pune",u:"/restaurants/pune/best-cafes/",c:"Restaurant Cuisine"},
  {l:"Best Maharashtrian in Pune",u:"/restaurants/pune/best-maharashtrian/",c:"Restaurant Cuisine"},
  {l:"Best Andhra in Visakhapatnam",u:"/restaurants/visakhapatnam/best-andhra/",c:"Restaurant Cuisine"},
  {l:"Best Cbse in Bangalore",u:"/schools/bangalore/best-cbse/",c:"School Board"},
  {l:"Best Icse in Bangalore",u:"/schools/bangalore/best-icse/",c:"School Board"},
  {l:"Best International in Bangalore",u:"/schools/bangalore/best-international/",c:"School Board"},
  {l:"Best State board in Bangalore",u:"/schools/bangalore/best-state-board/",c:"School Board"},
  {l:"Best Cbse in Chennai",u:"/schools/chennai/best-cbse/",c:"School Board"},
  {l:"Best Icse in Chennai",u:"/schools/chennai/best-icse/",c:"School Board"},
  {l:"Best International in Chennai",u:"/schools/chennai/best-international/",c:"School Board"},
  {l:"Best State board in Chennai",u:"/schools/chennai/best-state-board/",c:"School Board"},
  {l:"Best Cbse in Delhi",u:"/schools/delhi/best-cbse/",c:"School Board"},
  {l:"Best Icse in Delhi",u:"/schools/delhi/best-icse/",c:"School Board"},
  {l:"Best International in Delhi",u:"/schools/delhi/best-international/",c:"School Board"},
  {l:"Best State board in Delhi",u:"/schools/delhi/best-state-board/",c:"School Board"},
  {l:"Best Cbse in Hyderabad",u:"/schools/hyderabad/best-cbse/",c:"School Board"},
  {l:"Best Icse in Hyderabad",u:"/schools/hyderabad/best-icse/",c:"School Board"},
  {l:"Best International in Hyderabad",u:"/schools/hyderabad/best-international/",c:"School Board"},
  {l:"Best State board in Hyderabad",u:"/schools/hyderabad/best-state-board/",c:"School Board"},
  {l:"Best Cbse in Mumbai",u:"/schools/mumbai/best-cbse/",c:"School Board"},
  {l:"Best Icse in Mumbai",u:"/schools/mumbai/best-icse/",c:"School Board"},
  {l:"Best International in Mumbai",u:"/schools/mumbai/best-international/",c:"School Board"},
  {l:"Best State board in Mumbai",u:"/schools/mumbai/best-state-board/",c:"School Board"},
  {l:"Best Cbse in Pune",u:"/schools/pune/best-cbse/",c:"School Board"},
  {l:"Best Icse in Pune",u:"/schools/pune/best-icse/",c:"School Board"},
  {l:"Best International in Pune",u:"/schools/pune/best-international/",c:"School Board"},
  {l:"Best State board in Pune",u:"/schools/pune/best-state-board/",c:"School Board"},
  {l:"Best Arts in Bangalore",u:"/colleges/bangalore/best-arts/",c:"College Stream"},
  {l:"Best Commerce in Bangalore",u:"/colleges/bangalore/best-commerce/",c:"College Stream"},
  {l:"Best Engineering in Bangalore",u:"/colleges/bangalore/best-engineering/",c:"College Stream"},
  {l:"Best Mba in Bangalore",u:"/colleges/bangalore/best-mba/",c:"College Stream"},
  {l:"Best Medical in Bangalore",u:"/colleges/bangalore/best-medical/",c:"College Stream"},
  {l:"Best Arts in Chennai",u:"/colleges/chennai/best-arts/",c:"College Stream"},
  {l:"Best Commerce in Chennai",u:"/colleges/chennai/best-commerce/",c:"College Stream"},
  {l:"Best Engineering in Chennai",u:"/colleges/chennai/best-engineering/",c:"College Stream"},
  {l:"Best Mba in Chennai",u:"/colleges/chennai/best-mba/",c:"College Stream"},
  {l:"Best Medical in Chennai",u:"/colleges/chennai/best-medical/",c:"College Stream"},
  {l:"Best Arts in Delhi",u:"/colleges/delhi/best-arts/",c:"College Stream"},
  {l:"Best Commerce in Delhi",u:"/colleges/delhi/best-commerce/",c:"College Stream"},
  {l:"Best Engineering in Delhi",u:"/colleges/delhi/best-engineering/",c:"College Stream"},
  {l:"Best Mba in Delhi",u:"/colleges/delhi/best-mba/",c:"College Stream"},
  {l:"Best Medical in Delhi",u:"/colleges/delhi/best-medical/",c:"College Stream"},
  {l:"Best Arts in Hyderabad",u:"/colleges/hyderabad/best-arts/",c:"College Stream"},
  {l:"Best Commerce in Hyderabad",u:"/colleges/hyderabad/best-commerce/",c:"College Stream"},
  {l:"Best Engineering in Hyderabad",u:"/colleges/hyderabad/best-engineering/",c:"College Stream"},
  {l:"Best Mba in Hyderabad",u:"/colleges/hyderabad/best-mba/",c:"College Stream"},
  {l:"Best Medical in Hyderabad",u:"/colleges/hyderabad/best-medical/",c:"College Stream"},
  {l:"Best Arts in Mumbai",u:"/colleges/mumbai/best-arts/",c:"College Stream"},
  {l:"Best Commerce in Mumbai",u:"/colleges/mumbai/best-commerce/",c:"College Stream"},
  {l:"Best Engineering in Mumbai",u:"/colleges/mumbai/best-engineering/",c:"College Stream"},
  {l:"Best Mba in Mumbai",u:"/colleges/mumbai/best-mba/",c:"College Stream"},
  {l:"Best Medical in Mumbai",u:"/colleges/mumbai/best-medical/",c:"College Stream"},
  {l:"Best Arts in Pune",u:"/colleges/pune/best-arts/",c:"College Stream"},
  {l:"Best Commerce in Pune",u:"/colleges/pune/best-commerce/",c:"College Stream"},
  {l:"Best Engineering in Pune",u:"/colleges/pune/best-engineering/",c:"College Stream"},
  {l:"Best Mba in Pune",u:"/colleges/pune/best-mba/",c:"College Stream"},
  {l:"Best Medical in Pune",u:"/colleges/pune/best-medical/",c:"College Stream"},
  {l:"Best 1.5 Ton Inverter AC in India 2026: 5-Star Models Ranked",u:"/blog/best-1-5-ton-inverter-ac-india-2026/",c:"Blog"},
  {l:"Best AC Under ₹30,000 in India 2026: Top 7 1-Ton &amp; 1.5-Ton Models",u:"/blog/best-ac-under-30000-india-2026/",c:"Blog"},
  {l:"Best AC Under Rs 40,000 in India (June 2025)",u:"/blog/best-ac-under-40000-india/",c:"Blog"},
  {l:"Best Air Cooler for Home in India 2026: Desert vs Tower vs Personal",u:"/blog/best-air-cooler-home-india-2026/",c:"Blog"},
  {l:"Best Air Fryer in India 2025: Philips vs Inalsa vs Havells vs Cosori",u:"/blog/best-air-fryer-india/",c:"Blog"},
  {l:"Best Air Purifier in India 2026 — HEPA Models for Pollution",u:"/blog/best-air-purifier-india/",c:"Blog"},
  {l:"Best BBA Colleges in India 2026: Top 10 by Placements, Fees &amp; Selection Criteria",u:"/blog/best-bba-colleges-india-2026/",c:"Blog"},
  {l:"15 Best Beaches in India (2025 Traveller's Guide)",u:"/blog/best-beaches-india/",c:"Blog"},
  {l:"Best Two-Wheeler Insurance in India 2025: Bajaj Allianz vs ACKO vs Digit",u:"/blog/best-bike-insurance-india/",c:"Blog"},
  {l:"Best Bikes Under 1 Lakh in India 2026 — Mileage &amp; Power",u:"/blog/best-bike-under-1-lakh-india/",c:"Blog"},
  {l:"Best Bike Under Rs 2 Lakh in India (June 2025)",u:"/blog/best-bike-under-2-lakh-india/",c:"Blog"},
  {l:"Best Bluetooth Speaker Under ₹5,000 in India (2025)",u:"/blog/best-bluetooth-speaker-under-5000-india/",c:"Blog"},
  {l:"Best Broadband Plans in India 2025: JioFiber vs Airtel Xstream vs ACT",u:"/blog/best-broadband-plan-india/",c:"Blog"},
  {l:"Best Budget Hill Stations in India Under ₹10,000 Summer 2026",u:"/blog/best-budget-hill-stations-india-under-10000-2026/",c:"Blog"},
  {l:"Best Cancer Hospitals in India 2025: Top Oncology Centres",u:"/blog/best-cancer-hospitals-india/",c:"Blog"},
  {l:"Best Car Insurance in India 2025: ACKO vs HDFC ERGO vs Bajaj Allianz",u:"/blog/best-car-insurance-india/",c:"Blog"},
  {l:"Best Cars Under 10 Lakh in India 2026 — Top Picks",u:"/blog/best-car-under-10-lakh-india/",c:"Blog"},
  {l:"Best Ceiling Fan with Remote in India 2026: BLDC Models Ranked",u:"/blog/best-ceiling-fan-with-remote-india-2026/",c:"Blog"},
  {l:"Best IIT JEE Coaching in India 2025: Allen vs Resonance vs Vedantu",u:"/blog/best-coaching-iit-jee-india/",c:"Blog"},
  {l:"Best NEET Coaching in India 2026: Aakash vs Allen vs Physics Wallah",u:"/blog/best-coaching-neet-india/",c:"Blog"},
  {l:"Best Colleges After 12th Arts (Humanities) in India 2026: Top Picks &amp; Career Paths",u:"/blog/best-colleges-after-12th-arts-humanities-india-2026/",c:"Blog"},
  {l:"Best Colleges After 12th Commerce in India 2026: Top B.Com, BBA &amp; CA Foundation Paths",u:"/blog/best-colleges-after-12th-commerce-india-2026/",c:"Blog"},
  {l:"Best Colleges After 12th Science (PCB) in India 2026: MBBS, Biotech &amp; Paramedical",u:"/blog/best-colleges-after-12th-science-pcb-india-2026/",c:"Blog"},
  {l:"Best Colleges After 12th Science (PCM) in India 2026: Engineering, BSc &amp; Alternatives",u:"/blog/best-colleges-after-12th-science-pcm-india-2026/",c:"Blog"},
  {l:"Best Colleges in Chandigarh 2026 — Engineering, Arts, Science",u:"/blog/best-colleges-chandigarh/",c:"Blog"},
  {l:"Best Colleges in Jaipur 2026 — MNIT, Rajasthan University &amp; More",u:"/blog/best-colleges-jaipur/",c:"Blog"},
  {l:"Best Colleges in Trichy 2025: NIT vs SASTRA vs Bishop Heber",u:"/blog/best-colleges-trichy/",c:"Blog"},
  {l:"Best Credit Cards in India 2025: HDFC vs SBI vs Axis vs Amex",u:"/blog/best-credit-card-india/",c:"Blog"},
  {l:"Best Credit Cards for Tax Payment in India 2026: Earn Points on Income Tax",u:"/blog/best-credit-cards-for-tax-payment-india-2026/",c:"Blog"},
  {l:"Best DSLR Camera for Beginners in India 2025",u:"/blog/best-dslr-camera-for-beginners-india/",c:"Blog"},
  {l:"Best DTH Plan in India 2025: Tata Play vs Airtel Digital TV vs Dish TV",u:"/blog/best-dth-plan-india/",c:"Blog"},
  {l:"Best Earbuds Under 2000 in India 2026 — TWS &amp; ANC Picks",u:"/blog/best-earbuds-under-2000-india/",c:"Blog"},
  {l:"Best Education Loan in India 2025 for Studies Abroad and India",u:"/blog/best-education-loan-india/",c:"Blog"},
  {l:"Best Electric Cars in India 2026 — Range, Price, Charging",u:"/blog/best-electric-car-india/",c:"Blog"},
  {l:"Best Electric Scooters in India 2026 — Range &amp; Performance",u:"/blog/best-electric-scooter-india/",c:"Blog"},
  {l:"Best ELSS Mutual Funds in India 2026: Top Tax-Saving SIPs Ranked",u:"/blog/best-elss-mutual-funds-india-2026/",c:"Blog"},
  {l:"Best EV Charging Networks in India 2025: Tata Power EZ vs Statiq vs Ather Grid",u:"/blog/best-ev-charging-station-india/",c:"Blog"},
  {l:"Best Electric Scooter Under Rs 1 Lakh in India (June 2025)",u:"/blog/best-ev-scooter-under-1-lakh-india/",c:"Blog"},
  {l:"Best Gaming Laptop Under Rs 80,000 in India (June 2025)",u:"/blog/best-gaming-laptop-under-80000-india/",c:"Blog"},
  {l:"Best Gaming Phone Under ₹30,000 in India (2025)",u:"/blog/best-gaming-phone-under-30000-india/",c:"Blog"},
  {l:"Best GaN Chargers in India 2026 — Fast Charging Picks",u:"/blog/best-gan-charger-india/",c:"Blog"},
  {l:"Best Family Health Insurance in India 2025: Star Health vs HDFC ERGO vs Niva Bupa",u:"/blog/best-health-insurance-family-india/",c:"Blog"},
  {l:"Best Health Insurance for Tax 80D Benefit in India 2026",u:"/blog/best-health-insurance-for-tax-80d-india-2026/",c:"Blog"},
  {l:"Best Hill Stations from Bangalore for Summer 2026: Top 8 Within 400 km",u:"/blog/best-hill-stations-from-bangalore-summer-2026/",c:"Blog"},
  {l:"Best Hill Stations from Chennai for Summer 2026: Top 7 Options",u:"/blog/best-hill-stations-from-chennai-summer-2026/",c:"Blog"},
  {l:"Best Hill Stations from Delhi for Summer 2026: Top 10 Within 500 km",u:"/blog/best-hill-stations-from-delhi-summer-2026/",c:"Blog"},
  {l:"Best Hill Stations from Hyderabad for Summer 2026: Top 7 Picks",u:"/blog/best-hill-stations-from-hyderabad-summer-2026/",c:"Blog"},
  {l:"Best Hill Stations from Mumbai for Summer 2026: Top 8 Within 400 km",u:"/blog/best-hill-stations-from-mumbai-summer-2026/",c:"Blog"},
  {l:"20 Best Hill Stations in India (2025 Travel Guide)",u:"/blog/best-hill-stations-india/",c:"Blog"},
  {l:"Best Home Loan Banks in India 2025: SBI vs HDFC vs ICICI vs LIC HFL",u:"/blog/best-home-loan-bank-india/",c:"Blog"},
  {l:"Best Homestays in Coorg 2025: Plantation Stays Ranked",u:"/blog/best-homestays-coorg/",c:"Blog"},
  {l:"Best Honeymoon Destinations in India 2025",u:"/blog/best-honeymoon-destinations-india/",c:"Blog"},
  {l:"Best Hospitals in Bangalore 2026 — Multi-Specialty Picks",u:"/blog/best-hospitals-bangalore/",c:"Blog"},
  {l:"Best Hospitals in Chennai 2026 — Apollo, MIOT, Fortis &amp; More",u:"/blog/best-hospitals-chennai/",c:"Blog"},
  {l:"Best Hospitals in Coimbatore 2025: KMCH vs PSG vs Ganga Hospital",u:"/blog/best-hospitals-coimbatore/",c:"Blog"},
  {l:"Best Hospitals in Delhi 2026 — AIIMS, Max, Apollo &amp; More",u:"/blog/best-hospitals-delhi/",c:"Blog"},
  {l:"Best Hospitals in Hyderabad 2026 — Care, Apollo, KIMS &amp; More",u:"/blog/best-hospitals-hyderabad/",c:"Blog"},
  {l:"Best Hospitals in Jaipur 2026 — SMS, Fortis, Narayana &amp; More",u:"/blog/best-hospitals-jaipur/",c:"Blog"},
  {l:"Best Hospitals in Mumbai 2026 — Hinduja, Lilavati, Tata &amp; More",u:"/blog/best-hospitals-mumbai/",c:"Blog"},
  {l:"Best Hotels in Goa 2025: Top Picks for Every Budget",u:"/blog/best-hotels-goa/",c:"Blog"},
  {l:"Best Hotels in Jaipur 2025: Palaces, Havelis, and Boutique Stays",u:"/blog/best-hotels-jaipur/",c:"Blog"},
  {l:"Best Hotels in Manali 2025: Old Manali to Solang",u:"/blog/best-hotels-manali/",c:"Blog"},
  {l:"Best Instant Water Heater (Geyser) in India 2026: 3L to 6L Models Ranked",u:"/blog/best-instant-geyser-india-2026/",c:"Blog"},
  {l:"Best JEE Coaching for Droppers in India 2026: Top 6 Repeat-Year Programs",u:"/blog/best-jee-coaching-for-droppers-india-2026/",c:"Blog"},
  {l:"Best Laptop for Students in India (2025)",u:"/blog/best-laptop-for-students-2025/",c:"Blog"},
  {l:"Best Laptops Under 50000 in India 2026 — Top Picks",u:"/blog/best-laptop-under-50000-india/",c:"Blog"},
  {l:"Best Mattress in India 2025: Wakefit vs Sleepwell vs SleepyCat vs Duroflex",u:"/blog/best-mattress-india/",c:"Blog"},
  {l:"Best MBA Colleges in India 2025: IIMs and Top Private B-Schools",u:"/blog/best-mba-colleges-india/",c:"Blog"},
  {l:"Best Microwave Oven in India (June 2025): Solo vs Grill vs Convection",u:"/blog/best-microwave-oven-india/",c:"Blog"},
  {l:"Best Mirrorless Camera Under Rs 1,00,000 in India 2025",u:"/blog/best-mirrorless-camera-under-100000-india/",c:"Blog"},
  {l:"Best Mobile Plan in India 2025: Jio vs Airtel vs Vi vs BSNL",u:"/blog/best-mobile-plan-india/",c:"Blog"},
  {l:"Best Monitors for Work From Home in India 2026",u:"/blog/best-monitor-work-from-home-india/",c:"Blog"},
  {l:"Best Mutual Fund App in India 2025: Groww vs Zerodha Coin vs Kuvera",u:"/blog/best-mutual-fund-app-india/",c:"Blog"},
  {l:"Best NEET Coaching for Droppers in India 2026: Top 6 Repeat-Year Programs",u:"/blog/best-neet-coaching-for-droppers-india-2026/",c:"Blog"},
  {l:"Best Online Therapy Platforms in India 2025: MindPeers vs Amaha vs Practo",u:"/blog/best-online-therapy-india/",c:"Blog"},
  {l:"Best Pension Plans in India 2026: NPS vs Pension MFs vs Annuities",u:"/blog/best-pension-plans-india-2026/",c:"Blog"},
  {l:"Best Personal Loan in India 2025: HDFC vs SBI vs Bajaj Finserv vs Kreditbee",u:"/blog/best-personal-loan-india/",c:"Blog"},
  {l:"Best Pet Insurance in India 2025: Bajaj Allianz vs Future Generali vs Vetina",u:"/blog/best-pet-insurance-india/",c:"Blog"},
  {l:"Best Phone for Photography in 2025 (India Edition)",u:"/blog/best-phone-for-photography-2025/",c:"Blog"},
  {l:"Best Phones Under 10000 in India 2026 — Budget Picks",u:"/blog/best-phone-under-10000-india/",c:"Blog"},
  {l:"Best Phones Under 15000 in India 2026 — Top Smartphones",u:"/blog/best-phone-under-15000-india/",c:"Blog"},
  {l:"Best Phones Under 20000 in India 2026 — Top Picks",u:"/blog/best-phone-under-20000-india/",c:"Blog"},
  {l:"Best Phones Under 30000 in India 2026 — Mid-Premium Picks",u:"/blog/best-phone-under-30000-india/",c:"Blog"},
  {l:"Best Phone Under Rs 50,000 in India (June 2025)",u:"/blog/best-phone-under-50000-india/",c:"Blog"},
  {l:"Best Places for Summer Vacation in India (2025)",u:"/blog/best-places-summer-vacation-india/",c:"Blog"},
  {l:"Best Places to Visit in Himachal Pradesh 2025",u:"/blog/best-places-to-visit-himachal/",c:"Blog"},
  {l:"Best Places to Visit in Kerala 2025: Ranked Guide",u:"/blog/best-places-to-visit-kerala/",c:"Blog"},
  {l:"Best Places to Visit in Rajasthan 2025: A 10-Day Itinerary",u:"/blog/best-places-to-visit-rajasthan/",c:"Blog"},
  {l:"Best Places to Visit in India in April 2026",u:"/blog/best-places-visit-india-april/",c:"Blog"},
  {l:"Best Places to Visit in India in December 2026",u:"/blog/best-places-visit-india-december/",c:"Blog"},
  {l:"Best Power Banks in India 2026 — 10000mAh to 20000mAh",u:"/blog/best-power-bank-india/",c:"Blog"},
  {l:"Best Refrigerators in India 2026 — Single, Double, Side-by-Side",u:"/blog/best-refrigerator-india/",c:"Blog"},
  {l:"Best Refrigerator for Large Family in India 2026: 500L+ Double-Door &amp; Side-by-Side",u:"/blog/best-refrigerator-large-family-india-2026/",c:"Blog"},
  {l:"Best Refrigerator Under ₹25,000 in India (2025)",u:"/blog/best-refrigerator-under-25000-india/",c:"Blog"},
  {l:"Best Resorts in Kerala 2025: Backwaters, Beaches, and Hills",u:"/blog/best-resorts-kerala/",c:"Blog"},
  {l:"Best Restaurants in Coimbatore 2025: From Annapoorna to Fine Dining",u:"/blog/best-restaurants-coimbatore/",c:"Blog"},
  {l:"Best Schools in Chandigarh 2026 — CBSE, ICSE, IB Picks",u:"/blog/best-schools-chandigarh/",c:"Blog"},
  {l:"Best Schools in Coimbatore 2025: CBSE, ICSE &amp; State Board Rankings",u:"/blog/best-schools-coimbatore/",c:"Blog"},
  {l:"Best Schools in Jaipur 2026 — Top CBSE, ICSE, IB Schools",u:"/blog/best-schools-jaipur/",c:"Blog"},
  {l:"Best Schools in Lucknow 2026 — La Martiniere, CMS, DPS",u:"/blog/best-schools-lucknow/",c:"Blog"},
  {l:"Best Sedan Under ₹10 Lakh in India (2025)",u:"/blog/best-sedan-under-10-lakh-india/",c:"Blog"},
  {l:"Best Smartwatches in India 2026 — Top Picks Under 25000",u:"/blog/best-smartwatch-india/",c:"Blog"},
  {l:"Best Solar Panels for Home in India 2025: Tata vs Adani vs Waaree",u:"/blog/best-solar-panel-home-india/",c:"Blog"},
  {l:"Best SUV Under ₹15 Lakh in India (2025)",u:"/blog/best-suv-under-15-lakh-india/",c:"Blog"},
  {l:"Best Tax-Saving FD in India 2026: Top Bank Fixed Deposits for 80C",u:"/blog/best-tax-saving-fd-india-2026/",c:"Blog"},
  {l:"Best Term Insurance in India 2025: HDFC Life vs LIC vs Max Life",u:"/blog/best-term-insurance-india/",c:"Blog"},
  {l:"Best TVs Under 30000 in India 2026 — 43&quot; 4K Smart TV Picks",u:"/blog/best-tv-under-30000-india/",c:"Blog"},
  {l:"Best Vacuum Cleaner in India 2025: Dyson vs Eureka Forbes vs Mi",u:"/blog/best-vacuum-cleaner-india/",c:"Blog"},
  {l:"Best Washing Machines in India 2026 — Front, Top Load Picks",u:"/blog/best-washing-machine-india/",c:"Blog"},
  {l:"Best Washing Machine Under ₹20,000 in India (2025)",u:"/blog/best-washing-machine-under-20000-india/",c:"Blog"},
  {l:"Best Stainless Steel Water Bottle in India 2025: Milton vs Cello vs Borosil",u:"/blog/best-water-bottle-stainless-steel/",c:"Blog"},
  {l:"Best Water Purifier for Hard Water in India 2026: RO+UV+UF Ranked",u:"/blog/best-water-purifier-hard-water-india-2026/",c:"Blog"},
  {l:"Best Water Purifiers in India 2026 — RO, UV, UF Picks",u:"/blog/best-water-purifier-india/",c:"Blog"},
  {l:"Best Wireless Earbuds Under Rs 5,000 in India (June 2025)",u:"/blog/best-wireless-earbuds-under-5000-india/",c:"Blog"},
  {l:"CBSE vs ICSE — Which Board Is Better for Your Child?",u:"/blog/cbse-vs-icse-which-is-better/",c:"Blog"},
  {l:"Goa Travel Guide 2026 — Beaches, Stays, Food, Itinerary",u:"/blog/goa-travel-guide/",c:"Blog"},
  {l:"Goa vs Kerala 2025: Which Is Better for Your Trip?",u:"/blog/goa-vs-kerala-which-is-better/",c:"Blog"},
  {l:"Government vs Private Hospital in India — Cost &amp; Care Compared",u:"/blog/government-vs-private-hospital-india/",c:"Blog"},
  {l:"How to Save ₹1.5 Lakh Under 80C in India 2026: 8 Options Compared",u:"/blog/how-to-save-1-5-lakh-under-80c-india-2026/",c:"Blog"},
  {l:"Hyundai Creta vs Tata Nexon 2026 — Full Comparison",u:"/blog/hyundai-creta-vs-tata-nexon/",c:"Blog"},
  {l:"iPhone 16 vs iPhone 15 (2025): Which to Buy in India?",u:"/blog/iphone-16-vs-iphone-15/",c:"Blog"},
  {l:"iPhone 16 vs Samsung Galaxy S25 — 2026 Comparison",u:"/blog/iphone-16-vs-samsung-s25/",c:"Blog"},
  {l:"Ladakh Bike Trip Guide 2026 — Routes, Permits, Cost",u:"/blog/ladakh-bike-trip-guide/",c:"Blog"},
  {l:"LIC vs Private Insurance Companies: Which is Better in 2025?",u:"/blog/lic-vs-private-insurance/",c:"Blog"},
  {l:"MacBook Air vs Dell XPS in India — 2026 Comparison",u:"/blog/macbook-air-vs-dell-xps-india/",c:"Blog"},
  {l:"Mahindra Thar vs Maruti Jimny (2025): Which 4x4 to Buy?",u:"/blog/mahindra-thar-vs-maruti-jimny/",c:"Blog"},
  {l:"Mamaearth vs Plum vs Sugar: Best Indian D2C Beauty Brand 2025",u:"/blog/mamaearth-vs-plum-vs-sugar/",c:"Blog"},
  {l:"Maruti Brezza vs Tata Nexon 2026 — Compact SUV Comparison",u:"/blog/maruti-brezza-vs-tata-nexon/",c:"Blog"},
  {l:"Old vs New Tax Regime in India 2026: Which Saves More for You?",u:"/blog/old-vs-new-tax-regime-india-2026/",c:"Blog"},
  {l:"OnePlus vs Samsung vs iPhone (2025): Which Brand to Buy?",u:"/blog/oneplus-vs-samsung-vs-iphone/",c:"Blog"},
  {l:"Ooty vs Kodaikanal — Which Hill Station Is Better?",u:"/blog/ooty-vs-kodaikanal-which-is-better/",c:"Blog"},
  {l:"PPF vs ELSS vs NPS in India 2026: Which Saves More Tax?",u:"/blog/ppf-vs-elss-vs-nps-india-2026/",c:"Blog"},
  {l:"Samsung vs iPhone — Which Is Better in India 2026?",u:"/blog/samsung-vs-iphone-which-is-better/",c:"Blog"},
  {l:"School Fees in India 2026 — City-wise Breakdown",u:"/blog/school-fees-india-guide/",c:"Blog"},
  {l:"Split AC vs Window AC in India 2026: Which Should You Buy?",u:"/blog/split-ac-vs-window-ac-india-2026/",c:"Blog"},
  {l:"Microsoft Surface Pro vs Surface Laptop — 2026 Comparison",u:"/blog/surface-pro-vs-surface-laptop/",c:"Blog"},
  {l:"Tata Punch vs Maruti Fronx (2025): Which Sub-Compact SUV?",u:"/blog/tata-punch-vs-maruti-fronx/",c:"Blog"},
  {l:"Tata Tiago EV vs MG Comet EV: Which Budget Electric Car Wins in 2025?",u:"/blog/tata-tiago-ev-vs-mg-comet/",c:"Blog"},
  {l:"Best Weekend Trips From Bangalore 2026 — Top Getaways",u:"/blog/weekend-trips-from-bangalore/",c:"Blog"},
  {l:"Best Weekend Trips From Chennai 2026 — Top Getaways",u:"/blog/weekend-trips-from-chennai/",c:"Blog"},
  {l:"Best Weekend Trips from Coimbatore 2025: 10 Destinations Within 300 km",u:"/blog/weekend-trips-from-coimbatore/",c:"Blog"},
  {l:"Best Weekend Trips From Delhi 2026 — Top Getaways",u:"/blog/weekend-trips-from-delhi/",c:"Blog"},
  {l:"Best Weekend Trips From Hyderabad 2026 — Top Getaways",u:"/blog/weekend-trips-from-hyderabad/",c:"Blog"},
  {l:"Best Weekend Trips From Jaipur 2026 — Top Getaways",u:"/blog/weekend-trips-from-jaipur/",c:"Blog"},
  {l:"Best Weekend Trips From Mumbai 2026 — Top Getaways",u:"/blog/weekend-trips-from-mumbai/",c:"Blog"},
  {l:"12 Best Weekend Trips from Pune (2025)",u:"/blog/weekend-trips-from-pune/",c:"Blog"},
  {l:"What to Do if You Fail Board Exam in India 2026: Complete Recovery Guide",u:"/blog/what-to-do-if-you-fail-board-exam-india-2026/",c:"Blog"}
];
