var EXPANSION_SCHOOLS=[
// Jaipur (5)
{name:"Maharaja Sawai Man Singh Vidyalaya",city:"Jaipur",board:"CBSE",annual_fees:95000,google_rating:4.3,facilities:["Smart Classes","Swimming Pool","Sports Complex","Science Labs","Library"],website:"https://www.msmvidyalaya.com",type:"Private",established:1959},
{name:"Neerja Modi School",city:"Jaipur",board:"CBSE",annual_fees:110000,google_rating:4.4,facilities:["Smart Classes","Robotics Lab","Sports Academy","Swimming Pool","Performing Arts"],website:"https://www.neerjamodi.com",type:"Private",established:1986},
{name:"Jayshree Periwal High School",city:"Jaipur",board:"CBSE",annual_fees:130000,google_rating:4.5,facilities:["Smart Classes","Swimming Pool","Horse Riding","Sports Complex","Innovation Lab"],website:"https://www.jphs.in",type:"Private",established:2006},
{name:"St. Xavier's School Jaipur",city:"Jaipur",board:"CBSE",annual_fees:65000,google_rating:4.2,facilities:["Sports Ground","Library","Science Labs","Computer Lab","Chapel"],website:"https://www.stxaviersjaipur.com",type:"Private",established:1943},
{name:"Kendriya Vidyalaya No.5 Jaipur",city:"Jaipur",board:"CBSE",annual_fees:12000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Computer Lab","NCC"],website:"https://www.kvsangathan.nic.in",type:"Government",established:1975},
// Lucknow (5)
{name:"City Montessori School Gomti Nagar",city:"Lucknow",board:"ICSE",annual_fees:75000,google_rating:4.5,facilities:["Smart Classes","Sports Complex","Swimming Pool","Music Academy","Science Labs"],website:"https://www.cmseducation.org",type:"Private",established:1959},
{name:"La Martiniere College Lucknow",city:"Lucknow",board:"ICSE",annual_fees:85000,google_rating:4.6,facilities:["Heritage Campus","Swimming Pool","Sports Complex","NCC","Chapel"],website:"https://www.lamartinierelucknow.org",type:"Private",established:1845},
{name:"Seth MR Jaipuria School",city:"Lucknow",board:"CBSE",annual_fees:120000,google_rating:4.3,facilities:["Smart Classes","Swimming Pool","Robotics","Sports Academy","Art Studio"],website:"https://www.jaipuria.edu.in",type:"Private",established:1992},
{name:"Lucknow Public School",city:"Lucknow",board:"CBSE",annual_fees:55000,google_rating:4.1,facilities:["Sports Ground","Library","Science Labs","Computer Lab","Music Room"],website:"https://www.lucknowpublicschool.com",type:"Private",established:1983},
{name:"Kendriya Vidyalaya Lucknow Cantt",city:"Lucknow",board:"CBSE",annual_fees:12000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Computer Lab","NCC"],website:"https://www.kvsangathan.nic.in",type:"Government",established:1968},
// Chandigarh (5)
{name:"St. John's High School Chandigarh",city:"Chandigarh",board:"ICSE",annual_fees:60000,google_rating:4.4,facilities:["Heritage Campus","Sports Ground","Swimming Pool","Library","Chapel"],website:"https://www.stjohnschd.com",type:"Private",established:1959},
{name:"Vivek High School",city:"Chandigarh",board:"CBSE",annual_fees:70000,google_rating:4.3,facilities:["Smart Classes","Sports Complex","Library","Science Labs","Music Room"],website:"https://www.vivekhighschool.com",type:"Private",established:1972},
{name:"Delhi Public School Chandigarh",city:"Chandigarh",board:"CBSE",annual_fees:95000,google_rating:4.2,facilities:["Smart Classes","Swimming Pool","Sports Academy","Robotics Lab","Music"],website:"https://www.dpschandigarh.com",type:"Private",established:2003},
{name:"Bhavan Vidyalaya Chandigarh",city:"Chandigarh",board:"CBSE",annual_fees:45000,google_rating:4.1,facilities:["Sports Ground","Library","Science Labs","Computer Lab","Cultural Activities"],website:"https://www.bhavanvidyalaya.com",type:"Private",established:1960},
{name:"Government Model Senior Secondary School Sector 10",city:"Chandigarh",board:"CBSE",annual_fees:5000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Computer Lab"],website:"#",type:"Government",established:1955},
// Kochi (5)
{name:"Chinmaya Vidyalaya Kochi",city:"Kochi",board:"CBSE",annual_fees:55000,google_rating:4.3,facilities:["Smart Classes","Sports Ground","Library","Science Labs","Yoga"],website:"https://www.chinmayavidyalaya.com",type:"Private",established:1969},
{name:"Choice School Kochi",city:"Kochi",board:"CBSE",annual_fees:120000,google_rating:4.5,facilities:["Smart Classes","Swimming Pool","Sports Academy","Robotics","Music"],website:"https://www.choiceschool.in",type:"Private",established:2004},
{name:"Rajagiri Public School",city:"Kochi",board:"CBSE",annual_fees:65000,google_rating:4.2,facilities:["Sports Ground","Library","Science Labs","Computer Lab","Art Room"],website:"https://www.rajagirischool.com",type:"Private",established:1960},
{name:"Toc H Public School",city:"Kochi",board:"ICSE",annual_fees:50000,google_rating:4.1,facilities:["Sports Ground","Library","Labs","Computer Lab","Music Room"],website:"https://www.tochpublicschool.org",type:"Private",established:1955},
{name:"Kendriya Vidyalaya Naval Base Kochi",city:"Kochi",board:"CBSE",annual_fees:12000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Computer Lab","NCC"],website:"https://www.kvsangathan.nic.in",type:"Government",established:1970},
// Bhopal (5)
{name:"Campion School Bhopal",city:"Bhopal",board:"ICSE",annual_fees:70000,google_rating:4.3,facilities:["Sports Complex","Swimming Pool","Library","Science Labs","Chapel"],website:"https://www.campionbhopal.com",type:"Private",established:1975},
{name:"Delhi Public School Bhopal",city:"Bhopal",board:"CBSE",annual_fees:95000,google_rating:4.2,facilities:["Smart Classes","Swimming Pool","Sports Academy","Robotics Lab","Music"],website:"https://www.dpsbhopal.com",type:"Private",established:2002},
{name:"Sagar Public School",city:"Bhopal",board:"CBSE",annual_fees:80000,google_rating:4.1,facilities:["Smart Classes","Sports Ground","Library","Science Labs","Computer Lab"],website:"https://www.sagarpublicschool.com",type:"Private",established:1990},
{name:"The Sanskaar Valley School",city:"Bhopal",board:"CBSE",annual_fees:140000,google_rating:4.5,facilities:["Smart Classes","Swimming Pool","Sports Complex","Innovation Lab","Performing Arts"],website:"https://www.sanskaarvalley.com",type:"Private",established:2002},
{name:"Kendriya Vidyalaya No.1 Bhopal",city:"Bhopal",board:"CBSE",annual_fees:12000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Computer Lab","NCC"],website:"https://www.kvsangathan.nic.in",type:"Government",established:1965},
// Indore (5)
{name:"Daly College Indore",city:"Indore",board:"CBSE/ISC",annual_fees:200000,google_rating:4.6,facilities:["Heritage Campus","Swimming Pool","Horse Riding","Sports Complex","Hostel"],website:"https://www.dalycollege.org",type:"Private",established:1882},
{name:"Choithram School Indore",city:"Indore",board:"CBSE",annual_fees:75000,google_rating:4.3,facilities:["Smart Classes","Sports Ground","Swimming Pool","Library","Science Labs"],website:"https://www.choithramschool.com",type:"Private",established:1974},
{name:"Delhi Public School Indore",city:"Indore",board:"CBSE",annual_fees:90000,google_rating:4.2,facilities:["Smart Classes","Swimming Pool","Sports Academy","Robotics","Music"],website:"https://www.dpsindore.com",type:"Private",established:2005},
{name:"Shri Vaishnav Vidyapeeth",city:"Indore",board:"CBSE",annual_fees:45000,google_rating:4.0,facilities:["Sports Ground","Library","Science Labs","Computer Lab","Cultural Activities"],website:"https://www.svvindore.org",type:"Trust",established:1960},
{name:"Kendriya Vidyalaya No.1 Indore",city:"Indore",board:"CBSE",annual_fees:12000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Computer Lab","NCC"],website:"https://www.kvsangathan.nic.in",type:"Government",established:1966},
// Coimbatore (5)
{name:"SSVM World School",city:"Coimbatore",board:"CBSE",annual_fees:95000,google_rating:4.4,facilities:["Smart Classes","Swimming Pool","Sports Academy","Robotics Lab","Music"],website:"https://www.ssvmworldschool.com",type:"Private",established:2010},
{name:"GD Matriculation Higher Secondary School",city:"Coimbatore",board:"State Board",annual_fees:35000,google_rating:4.2,facilities:["Sports Ground","Library","Science Labs","Computer Lab"],website:"https://www.gdmatric.com",type:"Private",established:1975},
{name:"Suguna RKV School",city:"Coimbatore",board:"CBSE",annual_fees:65000,google_rating:4.1,facilities:["Smart Classes","Sports Ground","Library","Labs","Dance"],website:"https://www.sugunarkv.com",type:"Private",established:1990},
{name:"CSI Bishop Appasamy College of Arts & Science",city:"Coimbatore",board:"State Board",annual_fees:25000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Chapel"],website:"#",type:"Private",established:1968},
{name:"Kendriya Vidyalaya Coimbatore",city:"Coimbatore",board:"CBSE",annual_fees:12000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Computer Lab","NCC"],website:"https://www.kvsangathan.nic.in",type:"Government",established:1972},
// Nagpur (5)
{name:"Centre Point School Katol Road",city:"Nagpur",board:"CBSE",annual_fees:65000,google_rating:4.4,facilities:["Smart Classes","Sports Complex","Swimming Pool","Library","Science Labs"],website:"https://www.centrepointschool.com",type:"Private",established:1980},
{name:"Bhavan's BP Vidya Mandir",city:"Nagpur",board:"CBSE",annual_fees:55000,google_rating:4.2,facilities:["Smart Classes","Sports Ground","Library","Science Labs","Cultural Activities"],website:"https://www.bhavansnagpur.com",type:"Private",established:1965},
{name:"Delhi Public School Kamptee Road",city:"Nagpur",board:"CBSE",annual_fees:85000,google_rating:4.1,facilities:["Smart Classes","Swimming Pool","Sports Academy","Robotics","Music"],website:"https://www.dpsnagpur.com",type:"Private",established:2008},
{name:"Somalwar High School & Jr College",city:"Nagpur",board:"State Board",annual_fees:30000,google_rating:4.0,facilities:["Sports Ground","Library","Science Labs","Computer Lab"],website:"https://www.somalwar.com",type:"Private",established:1952},
{name:"Kendriya Vidyalaya Nagpur",city:"Nagpur",board:"CBSE",annual_fees:12000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Computer Lab","NCC"],website:"https://www.kvsangathan.nic.in",type:"Government",established:1970},
// Patna (5)
{name:"Delhi Public School Patna",city:"Patna",board:"CBSE",annual_fees:85000,google_rating:4.2,facilities:["Smart Classes","Swimming Pool","Sports Academy","Robotics Lab","Music"],website:"https://www.dpspatna.com",type:"Private",established:2005},
{name:"Notre Dame Academy Patna",city:"Patna",board:"ICSE",annual_fees:55000,google_rating:4.3,facilities:["Sports Ground","Library","Science Labs","Computer Lab","Chapel"],website:"https://www.notredamepatna.com",type:"Private",established:1947},
{name:"DAV Public School Patna",city:"Patna",board:"CBSE",annual_fees:45000,google_rating:4.1,facilities:["Sports Ground","Library","Science Labs","Computer Lab","Yoga"],website:"https://www.davpatna.com",type:"Private",established:1970},
{name:"St. Michael's High School Patna",city:"Patna",board:"ICSE",annual_fees:50000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Computer Lab","Chapel"],website:"https://www.stmichaelspatna.com",type:"Private",established:1858},
{name:"Kendriya Vidyalaya Bailey Road Patna",city:"Patna",board:"CBSE",annual_fees:12000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Computer Lab","NCC"],website:"https://www.kvsangathan.nic.in",type:"Government",established:1966},
// Guwahati (5)
{name:"Delhi Public School Guwahati",city:"Guwahati",board:"CBSE",annual_fees:80000,google_rating:4.2,facilities:["Smart Classes","Swimming Pool","Sports Academy","Robotics Lab","Music"],website:"https://www.dpsguwahati.com",type:"Private",established:2003},
{name:"South Point School Guwahati",city:"Guwahati",board:"CBSE",annual_fees:60000,google_rating:4.1,facilities:["Smart Classes","Sports Ground","Library","Science Labs","Computer Lab"],website:"https://www.southpointschool.in",type:"Private",established:1990},
{name:"Maria's Public School",city:"Guwahati",board:"CBSE",annual_fees:55000,google_rating:4.0,facilities:["Sports Ground","Library","Science Labs","Computer Lab","Art Room"],website:"https://www.mariaspublicschool.com",type:"Private",established:1985},
{name:"Don Bosco School Guwahati",city:"Guwahati",board:"CBSE",annual_fees:50000,google_rating:4.2,facilities:["Sports Ground","Library","Science Labs","Computer Lab","Chapel"],website:"https://www.donboscoguwahati.com",type:"Private",established:1965},
{name:"Kendriya Vidyalaya Guwahati",city:"Guwahati",board:"CBSE",annual_fees:12000,google_rating:4.0,facilities:["Sports Ground","Library","Labs","Computer Lab","NCC"],website:"https://www.kvsangathan.nic.in",type:"Government",established:1968}
];
